### ISSUE TITLE
Material receipt label is printed for each TU on an LU

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1160]
### Is this a bug or feature request?
bug

**Comment by metas-ts** [comment]
SQL to check which TUs where printed and whehter they are top-level TUs or not.
Note that we can avout the archive an instead select via process-id..
```sql
select a.AD_Archive_ID, a.Name, a.Created,
	count(hu.M_HU_ID), array_agg(hu.M_HU_ID), array_agg(hu.M_HU_Item_Parent_ID)
from AD_Archive a
	JOIN T_Selection s ON s.AD_PInstance_ID=a.AD_PInstance_ID
		JOIN M_HU hu ON hu.M_HU_ID=s.T_Selection_ID
where true
	AND a.Name='Wareneingangsetikett'
	AND a.Created>'2017-03-17'
GROUP BY a.AD_Archive_ID, a.Name, a.Created
ORDER BY count(hu.M_HU_ID) desc
```

**Comment by metas-dh** [comment]
Results of IT1
tested on swing (tested by ts on WebUI)

* no material receipt label printed for each TU on an LU, only for the LU itself: OK
* material receipt label printed for TU only when TU = top level HU, not on LU: OK
* no material receipt label is printed for VPI, since no existing packaging: OK
* correct no. of material receipt labels printed if receipt contains e.g. 2 LUs, 3 free TUs and 1 VPI (=> 5 labels): OK
