### ISSUE TITLE
Don't try to create empties movements if empties warehouse same as current warehouse

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1247]
#### Which are the steps to reproduce?
consider you have a HU on same warehouse as the empties is configured

From Handling units POS (swing) try to split that HU to something else (just to trigger the empties movement generation => will fail because the movement is created to move from/to same locator.

### What is the expected or desired behavior?
don't generate movement/movement lines when the locator is the same as the empties WH/locator.

NOTE: this behaviour will be helpful to small deployments where you could have one warehouse for the start.

**Comment by teosarca** [comment]
pls integrate it together with #1248

**Comment by metas-ts** [comment]
AFAUI is should move this task to "test" since that's where #1248 already is..

right, @teosarca ?

**Comment by teosarca** [comment]
> AFAUI is should move this task to "test" since that's where #1248 already is..
> 
> right, @teosarca ?

exactly. all code is there.

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* in Handling Unit POS, split off HUs from existing HUs in empties warehouse: working fine, no error or exception bc of move from/to same locator: OK
* checked movement: no movement/movement lines were created, since the new HU has the same locator as the original (= empties warehouse): OK
