### ISSUE TITLE
How to use self-signed certs with metasfresh using installer 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1512]
### question

I started with a base Ubuntu 16.04 install and ran the installer script that came with the metafresh software download.

I am using the stock self-signed cert that aas created with the ssl-cert package and the metafresh-webui_ssl.conf file with the SSLCertificateFile and SSLCertificateKeyFile entries uncommented and referencing the self-signed cert.

I've also tried using a known working config file for Apache with SSL and the entries from the metafresh-webui_ssl.conf file added.

Result:
The website will not display if I try to use a secure webserver.
Viewing the source code for the http and https HTML webpages are the same.

If I append /login?redirect=true to the https URL I can get the login page to display but when I try to login I get "Connection problem".

I get the same results with Firefox and Chrome.

**Comment by metas-jb** [comment]
If you enabled the `metasfresh-webui_ssl.conf` for apache2 and made sure the apache-mod `ssl` is enabled as well (you should be able to enable it using `a2enmod ssl`), you'll also need to modify the file `config.js` which you are able to locate in `/opt/metasfresh-webui-frontend/dist/`. This way, your client's webbrowsers can connect to the metasfresh webui-api.

Can you check if you modified the `config.js` so the entries represent the new (SSL) URL?
The contents of the file should look similar to this:
```
const config =  {
    API_URL: 'https://{my.server.com}/rest/api',
    WS_URL: 'https://{my.server.com}/stomp'
}
```
Where `{my.server.com}` is the URL on which your clients are able to connect to the metasfresh-webui.
Note the `https` instead of `http`.

Can you also make sure the webui-api service is up and running? You can check by verifying the running processes: `ps aux | grep metasfresh-webui-api`.

**Comment by metas-jb** [comment]
Is this issue resolved? If so, please close it.
