### ISSUE TITLE
Provide Basic Test config Data for manufacturing / production 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1609]
### Is this a bug or feature request?
feature

### What is the current behavior?
ressource, workflow, empties warehouse & distribution and warehouse config are missing

#### Which are the steps to reproduce?
try to create a new pp order

### What is the expected or desired behavior?
be able to fill out the mandatory fields in window pp_order

**Comment by metas-dh** [comment]
Results of IT1
tested pn mf15releasetest during e2e

* PP_Order can be created, all mandatory fields can be set (production ressource, workflow etc.): OK

remaining problem: qty in PP_Order cannot be changed after mandatory fields are set, to be fixed in https://github.com/metasfresh/metasfresh/issues/1581
