### ISSUE TITLE
Fix "Create primary key" process

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1807]
The issue was described in https://github.com/metasfresh/metasfresh-webui-api/issues/449

Edit: Also added "Delete column" process which deletes a column but also the tab fields and the database column if asked.

**Comment by teosarca** [comment]
Note to IT: nothing to test

**Comment by metas-ts** [comment]
Hi @teosarca 
please note that we have to use this proces with care, even if it works better now.

one could run the process locally within seconds and push the migration script and then on a live system, that script be unusable because it would run for days. 

happened to me when i added the PK to M_HU_Attribute_Snapshot.

..just wanted to vent my 2 cents..

**Comment by metas-rc** [comment]
Results of IT
* Nothing to test.
