### ISSUE TITLE
Fix control amount and qty in payment data imported from camt.54

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1873]
### Is this a bug or feature request?
Bug
### What is the current behavior?
currently, when importing camt.54 data into ESR_Import records, The control amount amount remains zero which causes an error when the record is processed.

**Comment by teosarca** [comment]
rolled on w101

**Comment by cristinamghita** [comment]
# Results of IT - tested on webui
## Setup
### Setup ESR
* First the esr needs to be enable. See http://docs.metasfresh.org/howto_collection/Wie_konfiguriere_ich_den_ESR_Zahlschein.html
* The make sure that bank account of the bpartner of the org is properly setup. See bellow.
  ![image](https://user-images.githubusercontent.com/15378036/35161764-d7070852-fd49-11e7-9b43-1c422189fdbf.png)
### Restart sever
 * needs to be restarted because caching
## Generate an invoice
 * for the invoice generated, will be created reference numbers in table C_ReferenceNo. See bellow.
   ![image](https://user-images.githubusercontent.com/15378036/35161931-5f823d46-fd4a-11e7-860c-ea2af085b76e.png)
* Follow up task for webui windows [Webui Window: Create window for ReferenceNo and Reference Type](https://github.com/metasfresh/metasfresh/issues/3366)
## Prepare test files
* Here are the files for the test: https://drive.google.com/drive/folders/1EJDzqdoALVIAPAtjbNbeGCQfPI9JmSsp
* Each file has 2 invoices, for 2 lines
* In order that the impor tto work we need next steps:
   * esr post account no from the file is 010000004; So make sure that the bank use 01-000000-4
   * the total amout is found after <ntry> tag, in <Amt> tag. E.g. `<Amt Ccy="CHF">150.00</Amt>`
  * the number of lines is found after <NtryDtls> tag, in <NbOfTxs> tag. E.g. `<NbOfTxs>2</NbOfTxs>`
   * modify the reference no generated for your invoice. You can find in tag  _<RmtInf>_ , between tags _<Ref>_  .
   E..g:  
        `<RmtInf>
		<Strd>
			<CdtrRefInf>
				<Tp>
					<CdOrPrtry>
						<Prtry>ISR Reference</Prtry>
					</CdOrPrtry>
				</Tp>
				<Ref>123456700100000001001458318</Ref>
			</CdtrRefInf>
			<AddtlRmtInf>?REJECT?0</AddtlRmtInf>
		</Strd>
	</RmtInf>` 
## Test Cases
### Import a file with a perfect match
* Create a record in ESR import window with type camt54
* Drag and drop the file
* From actions, run the process for importing attached file
        ![image](https://user-images.githubusercontent.com/15378036/35223784-563f0f6e-ff8b-11e7-9aba-c78b3777d7c8.png)
* File is processed with no problem
* Invoices are paid **OK**
* ESR is processed **OK**
### Import a file with no ESR creditor reference
* Create a record in ESR import window with type camt54
* Drag and drop the file (see file https://drive.google.com/file/d/1YTQ6PbksELjy-KUF4G3sFn2L0KDyQnQz/view?usp=sharing)
* From actions, run the process for importing attached file
        ![image](https://user-images.githubusercontent.com/15378036/35223784-563f0f6e-ff8b-11e7-9aba-c78b3777d7c8.png)
* One line is loaded and processed
* the other one, with no ref, is loaded with a message error **OK**
