### ISSUE TITLE
Window Design WebUI : Purchase candidate

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2050]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window Purchase Candidate does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Purchase Candidate respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
purchase candidates

1. layout
top left: important fields OK
top right: active OK
bottom right: client and org are a bit higher NOK

2. grid view
order by date desc, product asc, bp asc (ok since there is no name)

3. included tabs
=> white background is missing NOK

follow-up: https://github.com/metasfresh/metasfresh/issues/2282
