### ISSUE TITLE
Window Design WebUI: Payment Allocation Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2077]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045
### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Payment Allocation does not respect our layout conventions.
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Payment Allocation Window respect our cornerstones and layout conventions

**Comment by metas-lc** [comment]
IT
Payment Allocation window - document window
1. doc view layout: 
top left: mandatory important OK
top right: Document type (missing but same on swing), no., date OK
(to check: in some places is document no instead of no and transaction date instead of date)
bottom right: docstatus, org OK

2. grid view:
first: doctype (missing in swing too), docno, date OK
last: docstatus, org OK
order by: doctade desc  (should be) NOK is ordered by docno desc

3. filters:
org, no NOK. 
org is wanted? missing: bpartner, date, doctype(?)

4. included tabs:
included tab has white background. OK

**Comment by metas-lc** [comment]
created follow-up https://github.com/metasfresh/metasfresh/issues/2188
closing this task
