### ISSUE TITLE
Window Design WebUI: Vendor Returns 

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2084]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window  Vendor Returns does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window  Vendor Returns respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
Vendor Returns - document window

1. doc view layout: 
top left: mandatory important OK
top right: Document type, no., date (in some places fields are called like Document No and Movement Date instead of no. and date)
bottom right: org, client OK

2. grid view:
first: doctype, docno, date OK
last: docstatus, org OK
order by: doctade desc  
(in some places is ordered by docno desc and bpartner field is first)

3. filters:
no, bp NOK. 
missing: date, doctype

4. included tabs:
included tab doesn't have white background. NOK

created followup https://github.com/metasfresh/metasfresh/issues/2193
