### ISSUE TITLE
Year-End P&L Process w/ multiple Organisations error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2141]
### Is this a bug or feature request?
Bug
### What is the current behavior?
In General Ledger Window, when creating the Year-End Accounting for P&L then the process/ action does not filter by ad_org_id of GL when running the process and both Orgs haven the identical Chart of accounts.
#### Which are the steps to reproduce?
Prepare multiple Organisations w/ identical coa. Create P&L relevant invoices in both Org. Check the Saldobilanz of both. Create the Year-End GL and run the P&L process/ action. You will see that in GL are now accounting of both Org.
### What is the expected or desired behavior?
The process/ action shall filter the selected accounting by GL Journal ad_org_id.

**Comment by metas-rc** [comment]
Note to IT:
* I was not able to dev test this because of role problems. I couldn't even open the GL Journal batch. Please, move back to dev if it doesn't work.

* The error I get is: 

>Ausnahme:
In der derzeitigen Rolle können Sie auf die Informationen nicht zugreifen.
 Sie haben nicht die notwendigen Zugriffsrechte (No tabs) Rolle: null Fenster: Hauptbuch - Journal (ID=132)

**Comment by metas-ts** [comment]
@metas-mk can you please verify whether works now?
It's already on the customer's test system.
Monday forenoon should be early enough..

**Comment by metas-mk** [comment]
Quick Test w/ GL Journal Batch and Accounting Date 30.06.2017: Numbers selected show the selector date of 31.12.2017. The Process shall only take the accounting date, so that also half-year.end accountings are possible.

**Comment by metas-ts** [comment]
cherry-picked to branch `2017-09`

**Comment by metas-mk** [comment]
Done.
