### ISSUE TITLE
Window Design WebUI : Product Category

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2175]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Product Category needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
Adopt the window Product Category to our design Guidelines and layout conventions

**Comment by metas-lc** [comment]
IT
product category

1. creating a new one => value is not set NOK

2. layout: 
tl: important ffields, OK
tr: active OK
br: org, client OK

3. grid
order by name asc OK

4. included tabs:
- cannot see advance edit on the first tab, because
Server error
Failed building where clause because there is no Key Column defined in SqlDocumentEntityDataBindingDescriptor{sqlTableName=M_Product_Category_Acct, sqlTableAlias=d1}

(same error when you check the actions ) 

second tab doesn't have white background (probably the first one is the same)

follow-up: https://github.com/metasfresh/metasfresh/issues/2288
