### ISSUE TITLE
Window Design WebUI : Product Category Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2288]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Product Category needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/2175
### What is the expected or desired behavior?
1. value should be set when you create a new one
2. included tabs/ checking the actions gets this error
Server error
Failed building where clause because there is no Key Column defined in SqlDocumentEntityDataBindingDescriptor{sqlTableName=M_Product_Category_Acct, sqlTableAlias=d1}
3. second tab doesn't have white background (probably the first one is the same)

**Comment by metas-rc** [comment]
Results of IT
* Cannot set the product category parent because of a NPE. Followup https://github.com/metasfresh/metasfresh/issues/2598

* OK: The value is set on creation and saved after save.

* OK:  No error when pening the first tab ( Accounting). It  has a white background. It is also functional. After setting the mandatory values it is saved and closes when I press done.

* OK: Second included tab (linked products)  has white background
