### ISSUE TITLE
Introduce source-HU to fine-Picking

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2298]
### Is this a bug or feature request?
Feature

### What is the current behavior?

* The processes `WEBUI_Picking_PickToNewHU` and `WEBUI_Picking_PickToExistingHU` are intended for "fine picking"
* In fine picking, the picked HUs and goods are currently created out of "thin air". So far that didn't matter to those few users who do fine picking, but now we need to close this gap

### What is the expected or desired behavior?

There needs to be a way to specify the source HU(s) for this processes.
After talking with @metas-mk:
* Prerequisite: we need to have a dedicated "picking slot" icon i'm not a photoshop artist, but i'm confident i can make a nice one :-D. Right now we use the LU icon for picking slots
* In the `WEBUI_Picking_OpenHUsToPick` process window we can have an action "Select for fine picking". So the user can select the HUs (possibly different HUs with different products etc) when they start a "fine picking session".
* when the user returns to the picking window with its picking-slot view on the right, they see not only their picking slots, but also the HUs they selected (read-only, and just the top-level HUs)
  * there we also need an action to "unselect a given HU for fine picking"
* then, when the user does fine-picking, the first matching HU from the selected ones is automatically taken as the source HU.

### Results

* picking slots now are not shown with the "LU" icon anymore, but with an icon that looks like a check list
* when the HU-Editor is opened in picking, one can now also (in additional to selecting an HU to pick) select an HU to be flagged as "Fine picking source HU".
* Fine picking is basically about the two actions called "pick-to-new-HU" and "pick-to-existing-HU"
* if stuff was picked, if can also be un-picked again (additional actions)
* if a source-HU is empty, it remains active until the picked HUs are processed. before it is destroyed, a HU-snapshot is taken. If the picked HUs are unprocessed, the destroyed source HU is restored so that stuff can be un-picked

This this issue also comes a fix regarding HU-tracing: no more multiple HU-trace records per transformation

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* picking slots now are not shown with the "LU" icon anymore, but with an icon that looks like a check list: OK
* when the HU-Editor is opened in picking, one can now also (in additional to selecting an HU to pick) select an HU to be flagged as "Fine picking source HU": OK
* Fine picking is basically about the two actions called "pick-to-new-HU" and "pick-to-existing-HU"
if stuff was picked, if can also be un-picked again (additional actions): OK
* If the picked HUs are unprocessed, the destroyed source HU is restored so that stuff can be un-picked: OK
* if a source-HU is empty, it remains active until the picked HUs are processed. before it is destroyed, a HU-snapshot is taken: the empty source HUs remained Active, and were still displayed in the picking window, after processing & creating the shipment 

more problems / questions:
1. i could not process HUs which contained different products after fine picking, only HUs which contained the same product; process was not available in actions (
2. HUs fom fine picking are still displayed in picking window, after picking was processed and shipment was created: shouldn't they disappear after picking was processed?
3. when using "Pick to new HU", "No Packing Item" can be selected as PI, so you can fine pick only CUs of products together; but, for processing the picking, you need an HU, so those finepicked CUs cannot be processed!
4. fine picking of different products: 
* possible if the products have the same packing item, which you select for picking: OK
* possible if you use no packing item, not sure about this, see 2
* not possible if products have same packing item but have different UOM, so you can't pick products with e.g. IFCO 6410 x 10 Stk & IFCO 6410 x 10kg together: is that wanted?
* not possible if the products have different packing items: OK? imho yes, but not sure
5. when you used 2 different products in fine picking with No Packing Item as PI, then the 1st product is displayed in picking window (right side) when this product is selected on the left; when the 2nd product is selected on the left, this product is not shown on the right side, why?
6. the qty CU originally displayed in "Pick to new HU" is always Qty to deliver, also after you have done some picking already there is Qty picked (planned): is that wanted?

**Comment by teosarca** [comment]
As discussed with @metas-mk , we will introduce M_PickingSlot.IsRackSystem flag.

Based on that flag, the picking candidate's Process and Close action will work as follows:

M_PickingSlot.IsRackSystem=Y:
* process:
	add to SS => row visible
* close:
	add to Picking Slot rack system => row not visible
	=> close will be triggered when closing the modal window



M_PickingSlot.IsRackSystem=N:
* process:
	add to SS => row visible
	add to Picking Slot => row STILL visible
	and also do close
