### ISSUE TITLE
New Window for Internal Usage in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2326]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Internal Usage in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the window for internal usage.

**Comment by metas-ts** [comment]
cherry-picked to `2017-09`

**Comment by metas-rc** [comment]
Results of IT

Note: This is actually the Internal use Inventory. It can be currently found in the menu with the name "EIgenverbrauch" . It is used for Material Disposal (Garbage)

*NOK: The window name and some of its fields (Referenz) are not translated into English.

* NOK: The Reference is displayed in the left side of the main view. It shall be in the right side, because this table is a codument and it should respect document cornerstones.

* NOK: The document specific filters are not added. 

For the problems above I created a followup: https://github.com/metasfresh/metasfresh/issues/2607

* OK: The rest of the cornerstones and layouts are respected
