### ISSUE TITLE
Pause subscription delivery for given timeframe

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2495]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to pause subscriptions for a given timeframe.
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
It shall be possible to pause subscriptions.

**Comment by metas-ts** [comment]
Hi eoss-sh @metasnw @metas-mk

i'm currently working in this implementation..i'm unclear about what to about **existing** delivery-pauses. My suggestions are:

* To remove pauses, add an action "remove pause" that is available if any pause-related Abo-Verlause (`C_SubscriptionProgress`) record is currently selected.
* to modify existing pauses, i suggest that whenever the "pause"-Process is called with dateFrom - dateTo values that overlap with an existing pause, then that existing pause is *removed* and the new one is created.

wdyt?

**Comment by metas-ts** [comment]
Also, there is an important implementation "detail" to note:
We have those already mentioned Abo-Verlauf (`C_SubscriptionProgress`) records, where one can see past deliveries and influence planned (future) deliveries.

Now, each night, `C_SubscriptionProgress` records are turned into shipment schedule (Lieferdispo) records. Inserting a pause is only possible **before** this happened. 
If a shipment schedule already exists, but there shall be a pause, then this needs to be dealt with in the Lieferdispo window itself.
If you disaggree, we can discuss why this is IMHO a good approach or how to do it differently.

Also note that we can configure how many days in advance a shipment schedule for a given `C_SubscriptionProgress` record is created.

**Comment by metas-rc** [comment]
Note: I tested this task on swing only, to see if it's fine functionally. 
Testing it on webui is not doable at the time being because the frontend part for the date range parameter is not yet implemented.
This is the frontend task that will take care of it: https://github.com/metasfresh/metasfresh-webui-frontend/issues/981

**Comment by metas-rc** [comment]
Results of IT


* I followed the stept described in the IT of this task, to prepare entries in the testing databse: #2502
* Notice that the C_SubscriptionProgress entries that have shipment schedule entries counterparts have status = Shipment Open
* Go to the created Contract, run the process C_SubscriptionProgress_InsertPause
* Select a date range that covers a part of the days for which you have shipment schedules ( e.g. tomorrow, the day after nd the day after)
* Run the process
* Go to the shipment schedules for those days
* OK: They are closed ( Processed = true)
* Check the C_SubscriptionProgress entries again
* OK: There are 2 new entries: one for the pause start date and one with the pause end date. These 2 mark the range of C_SubscriptionProgress that are on pause.
* OK: They have Contract Status "Shippment-Pause"
* NOK: The Status is still Shipment Open -> followup created https://github.com/metasfresh/metasfresh/issues/2685
* Rerun the process now from the day after tomorrow until next week
* OK: The C_SubscriptionProgress for tomorrow is no longer in pause ( when the pauses overlap with old pauses, those ols poses are deleted and the new onesoverrride them)
* Rerun the process for some future dates that are not yet covered by shipment schedules
* OK: There are 2 new C_SubscriptionProgress entries for the start date and end date of that future pause
* OK: THe Status for those entries are still "Planned" as they should be, because shipment schedules were not created yet
