### ISSUE TITLE
Stop Subscription shipment after 2nd dunning

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2499]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to automatically stop the shipment of Subscriptions through dunning status.
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Stop the shipment creation for subscriptions when the subscription is in Status of 2nd dunning already.

**Comment by metas-rc** [comment]
How to create testing data: 

* Subscriptions: See the documentation in https://github.com/metasfresh/metasfresh/issues/2502

**Comment by metas-rc** [comment]
How to configure dunning:

1) Dunning Type

Create a new Dunning Type:
* Give it a name to remember
* Set the Dunning Trigger (column DunningTimer) to Default Payment Condition (german: Standard Zahlungsbedingung)
* Open the included tab. Here is where the dunning levels are defined.
Create the first dunning level:
* Give it a name to remember (e.g. Dunning Level 1)
* Days after due date = the number of days between the date the payment should have been made and the date when the dunning is triggered.
* If the number is negative  it means days until due
* For testing reasons, I set here only 1 day ( could be as many as desired)
* Days between dunning = the number of days the system wayts until triggering a new dunning
*-> Note: The current Days between dunning defines how many days have to pass after the last dunning so this one is triggered.
* If we want delivery to be stopped after this dunning level, set Delivery stop to true
Create the second dunning level:
* Similar with the first one 
* The second dunning level only makes sense if there is a Previous dunning level for it
*-> What previous dunning level means: <previous "Days after due date"> + previous "Days between dunning" must be less than <current "Days after due date" + current "Days between dunning"> 
* If we want delivery to be stopped after this dunning level, set Delivery stop to true. If it was already stopped from the first level, this doesn't make much sense.

2) Setting in the partner, customer

* Go to the partner for whom this dunning type fits ( in our case, the partner we made the subscription for)
* Go to the included tab "Customer"
* Set the Dunning Type to this new type that was created before
* Set payment term to Immediately
* Set Dunning grace date to nothing

3) Invoice

* Create a sales invoice for the partner above
* Make sure the payment term is also Immediately
* Date the invoice so that the dunning levels are already fulfilled
* Complete the invoice

4) Create Dunning Candidates

* Run the process Create/Update Dunning candidates
* Check Dunning Candidates
* -> There should be an entry created for the invoice above

5) Create Dunning Documents

* Run the process Process Dunning Candidates
* Go to the window Dunning
* -> There should be an entry for the dunning candidate above

6) Process Dunning Documents
* Go to the dunning document created above
* Go to its actions
* Run Process dunning 
* -> The document shall be marked as processed

**Comment by metas-rc** [comment]
Results of IT

* Do as described above
* Go to the window Shipment Restrictions
* Note: I only checked on swing, the webui window is not yet added.
* OK:  There is  an entry for the processed dunning document
* OK:  The entry has  the right dunning level id (according to the configuration done in the first step) 
* Check the shipment schedule for the subscription for the particular day when the dunning is performed.
* -> The shipment schedule shall have QtyToDeliver = 0
* -> The shipment schedule should have the flag isDeliveryStop = true
* -> The shipment schedule should have the Shipment Constraint set.
