### ISSUE TITLE
Report Translations to en_US: menu reports

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2571]
### Is this a bug or feature request?
fr
### What is the current behavior?
Currently, a lot of Reports don't have any Translations to en_US Language.
#### Which are the steps to reproduce?
Open them and see in WebUI
List with reports from menu:
1. Artikelstatistik
2. ADR Auswertung
3. Bericht Reklamationen
4. Umsatzreport
5. Umsatzreport Woche
6. Business Partner Revenue
7. Umsatz Geschäftspartner Woche
8. Umsatz Geschäftspartner Woche m. Menge
9. Umsatzreport Geschäftspartner m. Menge
10. Statistik nach Mengen
11. Statistik nach Mengen Gesamt
12. Statistik nach Mengen Woche
13. Statistik nach Mengen Gesamt/ Woche
14. Sales Trace
15. Anbauplanung Auswertung
16. Anbauplanung Auswertung Excel
17. Purchase Trace
18. Inventory Valuation
19. Bankauszug
20. Bankauszug (FiBU)
21. Bilanz
22. Deckungsbeitragsrechnung
23. Deckungsbeitrag Kurzversion
24. Deckungsbeitrag Kurzversion mit Vorjahr
25. Fibukonto Kontoblatt
26. Konten Information
27. Saldobilanz
28. Offene Posten
29. Kostenstellenwechsel
30. Gebindeübersicht
31. Gebindesaldo Gesamt
32. Rüstliste

### What is the expected or desired behavior?
1. see if all are needed
2. see if they are working, if not, fix
3. translate to en_US

**Comment by metas-lc** [comment]
Problems found while implementing this task
run Artikelstatistik -> console: https://pastebin.com/WbdRhxPu (it works in rest)

**Comment by metas-lc** [comment]
devtest
1. Artikelstatistik - works OK
2. ADR Auswertung - works OK
3. Bericht Reklamationen
4. Umsatzreport - works OK
5. Umsatzreport Woche - works OK
6. Business Partner Revenue - works OK
7. Umsatz Geschäftspartner Woche - works OK
8. Umsatz Geschäftspartner Woche m. Menge - works OK
9. Umsatzreport Geschäftspartner m. Menge - works OK
10. Statistik nach Mengen - works OK
11. Statistik nach Mengen Gesamt - works OK
12. Statistik nach Mengen Woche - works OK
13. Statistik nach Mengen Gesamt/ Woche - works OK
14. Sales Trace  - works OK
15. Anbauplanung Auswertung - works OK
16. Anbauplanung Auswertung Excel - works OK
17. Purchase Trace  - works OK
18. Inventory Valuation  - works OK
19. Bankauszug - works OK
20. Bankauszug (FiBU) - works OK
21. Bilanz - works OK
22. Deckungsbeitragsrechnung - works OK
23. Deckungsbeitrag Kurzversion - works OK
24. Deckungsbeitrag Kurzversion mit Vorjahr - works OK
25. Fibukonto Kontoblatt - works OK
26. Konten Information - works OK
27. Saldobilanz - works OK
28. Offene Posten - works OK
29. Kostenstellenwechsel - works OK
30. Gebindeübersicht - works OK
31. Gebindesaldo Gesamt - works OK
32. Rüstliste - works OK

Only thing it's not working nice is that when you have to set a period, you MUST select an year...it should work without needing to select an year

**Comment by metas-dh** [comment]
Results of IT1
tested in sp80

1. "Saldobilanz" not translated in menu
2. period can't be set by itself, year has to be set first
3. e.g. Artikelstatistik: qty all 0 shown? is that ok? 
4. "Reclamations" in report header, although it's called "Complaints Report" in menu?
5. CHF set where it can't be selected in modal window? or depending on Org currency?
6. Statistics by week Qty: "Einheit" instead of "Unit"
7. month abbrevations: Okt instead of Oct, maybe others too
8. if no data available, just empty page, no info for user about "no data available"?
9. bank statement: cut-offs: Document No.: "Docume", Valuta Date: "Valuta", Line No.: "Line", Account Summary Booking: "Account Summary"
10. bank statement (accounting) cut-offs: only "Bank Statement" in header, Line No.: "Line"
11. Marginal Costing: not translated? german report opens
12. Marginal Costing Short Version with previous year: cut-offs: Account: "Accoun", Prev.: shall be Prev. Year?
13. Accounts - Information: cut-offs: only "Accounts -" in header, Counter Acct.: "Counter"
14. Open Items: Days Due: empty, maybe "Unlimited" is cut-off?
15. Cost Center Movements: cut-off: in Period, the last digit of the date is missing: 01.06.201 - 30.06.2017
16. Picking List: "Pick List" in menu and modal window, not "Picking"?
17. "Package" for Gebinde, not Packing Material (as in Picking List)? => in reports for Gebindesaldo / -übersicht

**Comment by metas-lc** [comment]
1. "Saldobilanz" not translated in menu . SOLVED (now is Balance)
2. period can't be set by itself, year has to be set first NOT Solved (task: https://github.com/metasfresh/metasfresh/issues/2888)
3. e.g. Artikelstatistik: qty all 0 shown? is that ok? - OK - according to sql it's ok to be 0 if there are no fact_accts with no qty for those periods. Not related with this task (see Fact_Acct)
4. "Reclamations" in report header, although it's called "Complaints Report" in menu? - SOLVED. renamed process to Reclamations Report
5. CHF set where it can't be selected in modal window? or depending on Org currency? - OK - is taken from C_AcctSchema (for your client/org)
6. Statistics by week Qty: "Einheit" instead of "Unit" - SOLVED
7. month abbrevations: Okt instead of Oct, maybe others too - where? probably they are taken from calendar? or from the parameter?
8. if no data available, just empty page, no info for user about "no data available"? - not task related
9. bank statement: cut-offs: Document No.: "Docume", Valuta Date: "Valuta", Line No.: "Line", Account Summary Booking: "Account Summary" - SOLVED (renamed fields)
10. bank statement (accounting) cut-offs: only "Bank Statement" in header, Line No.: "Line" - SOLVED
11. Marginal Costing: not translated? german report opens - SOLVED
12. Marginal Costing Short Version with previous year: cut-offs: Account: "Accoun", Prev.: shall be Prev. Year?- SOLVED
13. Accounts - Information: cut-offs: only "Accounts -" in header, Counter Acct.: "Counter" - SOLVED
14. Open Items: Days Due: empty, maybe "Unlimited" is cut-off? - SOLVED
15. Cost Center Movements: cut-off: in Period, the last digit of the date is missing: 01.06.201 - 30.06.2017- SOLVED
16. Picking List: "Pick List" in menu and modal window, not "Picking"? - SOLVED
17. "Package" for Gebinde, not Packing Material (as in Picking List)? => in reports for Gebindesaldo / -übersicht - if it's really NOK i can change. I noticed in de_CH are different as well (Gebndeart and Packvorschrift). If it's really nok, i can change

**Comment by metas-dh** [comment]
Results of IT2
tested in sp80

7. about month abbrevations: Okt instead of Oct: taken from translations, where it's Okt for en_US, so OK
11. Marginal Costing: not translated? => most of the report is still in german, like the stuff on the left, e.g. Deckungsbeitrag => customer related info, OK
14. Open Items: Days Due: empty, maybe "Unlimited" is cut-off: i get no Unlimited when i leave the param empty, but if i set e.g. 99 in days due, i get the 99 overwriting the Unlimited: NOK
15. Cost Center Movements: cut-off: in Period, the last digit of the date is missing: i still get this, although there seems plenty of space, NOK

**Comment by metas-dh** [comment]
Results of IT3
tested in customer db

* Open Items: Days Due: no more overwriting of "Unlimited" when set, but field is empty when param is not set, no "Unlimited", like in Swing: creating a follow-up for this: #3497
* Cost Center Movements: no more cut-offs, looks fine: OK
