### ISSUE TITLE
Change Default Address Layout for B2C Partners for country CH

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2781]
### Is this a bug or feature request?
bug

### What is the current behavior?
if partner is company = N and has got a contact
the address in order, invoice, etc. is rendered without name for country CH

### What is the expected or desired behavior?
shall be the same as for country DE

**Comment by cristinamghita** [comment]
## Result of IT
### Tested on webui
* Created a new bpartner which is not company
* Add 2 locations:
  * one for DE
  * one for CH
* Created order and then invoice, using DE location
  * Address generated does not show the country since is local. The client is in DE. **OK**
* Created order and then invoice, using CH location
  * Address generated shows the country **OK**
    ![image](https://user-images.githubusercontent.com/15378036/35104490-b0a0297e-fc71-11e7-88ba-408b011287da.png)
