### ISSUE TITLE
Pre-enddate termination of flatrate created compensation sales order

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2859]
### Is this a bug or feature request?
FR

### What is the current behavior?
Pre-enddate termination of flatrate created compensation sales order

#### Which are the steps to reproduce?
1. configure condition like here: https://github.com/metasfresh/metasfresh/issues/2858#issuecomment-340212943
1. have a year contract
1. terminate any date before
1. NOK: sales order with compensation product is created

### What is the expected or desired behavior?
have a way to configure this to either turn it on or off

**Comment by cristinamghita** [comment]
I modified the code so that if **in the Contract Change is not defined a product**, no compensation order will be created.
![image](https://user-images.githubusercontent.com/15378036/32138148-d45d9188-bc36-11e7-9be6-9e09f92624fd.png)

Also, the  Open  Subscription Progress will have the contract status Quit. The rest are deleted, as before.
![image](https://user-images.githubusercontent.com/15378036/32138143-c0143772-bc36-11e7-9ed3-466cfdadb698.png)

**Comment by metasnw** [comment]
IT was Ok
