### ISSUE TITLE
Provide Doc Action voiding for contract period

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2908]
### Is this a bug or feature request?
FR

### What is the current behavior?
you can terminate a contract but you cant void

#### Which are the steps to reproduce?
1. create a contract via http://docs.metasfresh.org/webui_collection/EN/Create_contract.html

### What is the expected or desired behavior?
have either a docaction or process that allows to void a single period

purpose: give user or admin a way to get rid of a falsely created contract period.

effects:

- [x] contractstatus is set to voided (VO)
- [x] autorenew = N
- [ ] invoice candidate is closed if if has not been invoiced yet
- [ ] leave the invoice as it is if exists
- [ ] subscription progress is set to terminated
- [ ] does not work if it has got successor. error message is thrown
- [ ] reverses contract extension of predecessor (set next_flatrate_term_id to null)
- [ ] make sure changelog is activated for flatrate_term to log those changes

@metasnw **Implemented by using the existent process of cancelling a contract. The action happens if the flag 'OnlyTerminateCurrentTerm' is set on Y.**

**Comment by cristinamghita** [comment]
**Concept**
* We need a handler for  handling behaviour on voiding - a class which implements DocumentHandlerProvider
* we will have a method which will set
** DocStatus = Voided
** DocAction set to None("--")
** ContractStatus - introduce a new state - Voided
** Autorenew = N
** Set in predecessor next_flatrate_term_id to null (if exists)
* Trigger voiding only if does not have a succesor
** Throw error otherwise
* Have  anethod which will close the unprocessed ICs
* Have a method which will delete all subscription progress line created and shipment schedules
** Question: what happens if somehting was shipped ? 
* Have a method which make sure that we have changelog and log this

**Comment by cristinamghita** [comment]
Dev test:
* Try to terminat an extended contract
![image](https://user-images.githubusercontent.com/15378036/32791148-fc6af802-c968-11e7-96d7-cbf90cd3c548.png)

**Comment by cristinamghita** [comment]
After talking with @metasnw , we conclude that we need a new action, called **VoidSingleContract** in the cancelling process so that user to see it better and also the contract cancelled like that will have the ContractStatus **Voided.** and DocStatus **Closed**.

**Comment by metas-rc** [comment]
* Note: VoidSingleContract = Einzelne Periode stornieren ( in German); it has no English translation

Results of IT

NOK: The invoice candidate and the shipment schedules are not closed, because of an exception thrown from here: de.metas.inoutcandidate.api.impl.ShipmentSchedulePA.retrieveForInvoiceCandidate(I_C_Invoice_Candidate)
Looks like the table C_Flatrate_Term is not supported in the invoice candidate
Please, add implementation so it is supported in the future

**Comment by cristinamghita** [comment]
See contract and subscription progress after voiding:
![image](https://user-images.githubusercontent.com/15378036/34039360-d0da3350-e197-11e7-904e-1b1bb123620b.png)

See shipment schedule
![image](https://user-images.githubusercontent.com/15378036/34039402-faa27e36-e197-11e7-9b6e-acb3e85f591d.png)

See invoice candidate. Notice that is processed and can't be invoiced.
![image](https://user-images.githubusercontent.com/15378036/34039429-111ffeb8-e198-11e7-9751-d4215197e795.png)

**Comment by metas-rc** [comment]
Moving to Done after talking with Torby.
