### ISSUE TITLE
WebUI: New Window for Import Formats

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3029]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for Import Formats.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the window for Import Formats WebUI.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: The window was added to the menu
* OK: The window respects our layout conventions and cornerstones
* OK: The window and included tab have all the fields in both English and German
* OK: The included tab has white background
* NOK: The window is not functional in webui  because the Processing column does not have a default value. Since the Processing field is not displayed, I cannot set a value to it so I am not able to add new entries. 
Please, set a default value = 'N'  in the column AD_ImpFormat.Processing.

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


OK: The window is not functional. I was able to add a new entry and also entries in the subtab.
