### ISSUE TITLE
C_Bpartner: new Additional fields

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3042]
### Is this a bug or feature request?
FR
### What is the expected or desired behavior?
* Add next columns in C_BPartner
   - name3
   - pharmaproductpermlaw52
   - isSEPASigned
   - isPharmaciePermission
* add columns in import table
* add the code responsible for that

**Comment by metas-lc** [comment]
IT
open c_bpartner window and notice new fields:
Name3
Short Description
Pharmaproductpermlaw52
Pharmacie Permission
SEPA Signed
OK

importing: 
go to import-formate window and create a new one
db-tabelle Import - Geschäftspartner, format - tabulator-separiert
on subtab add: bp's value, name3, pharmaproductpermlaw52, isSEPASigned and isPharmaciePermission
set a startno for each of them.. from 1 to 5
go to Ladeprogramm fur impost datei, set your import format and upload a file with the text separated by tab
go to import bpartner window and import them 
=> can't see the data in this window. Created a task https://github.com/metasfresh/metasfresh/issues/3138
will postpone this IT until the bug is fixed
