### ISSUE TITLE
Warehouse picking group

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3079]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3078

### What is the expected or desired behavior?
* introduce M_Warehouse_PickingGroup
* a dropdown in warehouse window to set the picking group (not mandatory)
* shipment schedules: when searching for QtyOnHand consider all warehouses from same picking group as shipment schedule's warehouse
* shipment schedules: shall use the new material-dispo to fetch the available QtyOnHand (and not de.metas.storage as it is now)
* nice to have: drop de.metas.storage project if is possible and easy

### Note to IT
* when allocating QtyOnHand to shipment schedules, all warehouses from same picking group as the shipment schedule's warehouse shall be considered
* **full regression on how the QtyOnHand is allocated to shipment schedules => we switched to material-dispo module for fetching available stock**

**Comment by metas-dh** [comment]
issue when using batch entry: searching for a product in batch entry causes internal server error:

> "No matching group found for StockResult.AddToResultGroupRequest(warehouseId=540008, productId=2000616, storageAttributesKey=, bpartnerId=-2, qty=5) in StockResult(resultGroups=[StockResult.ResultGroup(warehouseId=-1, productId=2000616, storageAttributesKey=-1000, bpartnerId=-1, qty=0), StockResult.ResultGroup(warehouseId=-1, productId=2005599, storageAttributesKey=-1000, bpartnerId=-1, qty=0)])"
> path
> "/rest/api/window/143/1000017/1/quickInput/1/field/M_Product_ID/typeahead"

**Comment by teosarca** [comment]
@metas-dh  fixed by https://github.com/metasfresh/metasfresh/commit/91d26b17fa1b72bb228226181ef70f8b345467aa

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Warehouse picking group: dropdown in warehouse window (in Advanced Edit mode): OK
* Warehouse picking group: to be set in new Warehouse picking group window: OK

**Comment by teosarca** [comment]
@metas-dh  shall work, but just saying, pls make sure the quantity displayed in Order line,  batch entry, product lookup is still working as it was before.

**Comment by metas-dh** [comment]
continued testing (in mf15)

=> created 2 new warehouses and a warehouse picking group for both

I. QtyOnHand from manufacturing: tested with existing product Convenience Salat:
* QtyOnHand from manufacturing in the same warehouse: considered correctly in shipment schedule, OK
* QtyOnHand from manufacturing in another warehouse: not considered in shipment schedule, OK
* QtyOnHand from manufacturing in another warehouse, but same warehouse picking group: not considered in shipment schedule, NOK

II. QtyOnHand from material receipt: tested with new product Testsalat:
* QtyOnHand from material receipt in the same warehouse: not considered correctly in shipment schedule, NOK 
* QtyOnHand from material receipt in another warehouse: not considered in shipment schedule, OK
* QtyOnHand from material receipt in another warehouse, but same warehouse picking group: not considered in shipment schedule, NOK

=> need to check again with a new product since 
* e.g. QtyOnHand from material receipt in the same warehouse was working the 1st time, but not after sev. material receipts, and 
* e.g. the qty displayed when selecting the product in batch entry was correct (see pic), but then not correct in the shipment schedule

![2017-12-11 15_53_26-metasfresh](https://user-images.githubusercontent.com/18696715/33842770-ca75bcea-de9b-11e7-9479-8a4056a21294.png)

* m_attributesetinstance_id for the MD_Candidates from sales orders was always 0, but the one for the MD_Candidates from material receipts  was always a different one, although no attributes were set: not sure if this has an influence on the QtyOnHand? for the MD_Candidate from manufacturing order, m_attributesetinstance_id was also 0

**Comment by metas-dh** [comment]
**Update:**

I. QtyOnHand from manufacturing: tested with existing product that wasn't used anywhere before, to make sure the qties from other testing did not get in the way:
* production of 100kg
* sales order for 10kg for the next day, same warehouse: shipment schedule QtyOnHand: 90 (=> is the reduction for this shipment schedule already considered?) if so, then it's OK
* sales order for 10kg for the next day, different warehouse but same warehouse group: shipment schedule QtyOnHand: -10, NOK
* sales order for 10kg for the same day, different warehouse but same warehouse group: shipment schedule QtyOnHand: -20, NOK

II. QtyOnHand from material receipt: tested again with another new product, where the product category does not have any ASI set:
* material receipt of 50 Stk
* sales order for 10 Stk for the next day, same warehouse: shipment schedule QtyOnHand: 40 (=> is the reduction for this shipment schedule already considered?) if so, then it's OK
* sales order for 10 Stk for the next day, different warehouse but same warehouse group: shipment schedule QtyOnHand: 30, OK
* sales order for 10 Stk for the same day, same warehouse: shipment schedule QtyOnHand: 40 (=> is the sales order for the earlier date promised considered first, although it was created later?) if so, then it's OK
* sales order for 10 Stk for the same day, different warehouse: shipment schedule QtyOnHand: -10, OK

=> warehouse group picking works fine for QtyOnHand coming from material receipt, if m_attributesetinstance_id  is 0 for all
=> warehouse group picking did not work for QtyOnHand coming from manufacturing

**Comment by metas-dh** [comment]
=> problem with incorrect QtyOnHand from warehouse picking group in shipment schedules will be solved in different task, see above. closing this one.
