### ISSUE TITLE
Material Receipt candidates action for batch serial No on selected HU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3209]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
In Material Receipt Candidates HU Editor we don't have a functionality yet to add serial No in bulk to CU.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
In Material Receipt Candidates HU Editor it shall be possible to select a CU you want to receive, then start an action "Add Serial No." The Action Parm window opens, and there is a text field that allows adding a comma, semicolon or linebreak separated Serial No. After pressing Start, the action will transform the CU 1:1 and add a serial No. to each (new Attribute). If there are more CU qty than Serial No. then leave the remaining CU untouched. If the CU are part of a LU or TU combination, then leave the 1:1 CU in the combination too.
This needs to be done in WebUI.

Examples:
before: CU5 + 3 Serial No (sn) in Bulk
after: CU2, CU1+sn, CU1+sn, CU1+sn

before LU1-TU1-CU5 + 3 Serial No (sn) in Bulk
after: LU1-TU1-CU2, CU1+sn, CU1+sn, CU1+sn

before LU1-TU1-CU5 + 5 Serial No (sn) in Bulk
after: LU1-TU1-CU1+sn, CU1+sn, CU1+sn, CU1+sn, CU1+sn,

**Comment by metas-lc** [comment]
1. one problem comes from transform, i documented it here https://github.com/metasfresh/metasfresh-webui-api/issues/764
if you have TUs and CUs and you put serial nos on some CUs

2. sometimes happens when you have LU + TU + CUs and you first put like 4 serial NOs, and then you put something like 11. Then a TU gets off from LU NOK

**Comment by metas-rc** [comment]
Problems found while testing:

* When dealing with mahy HUs (e.g. creating 12 new CUs with serial numbers) there are a lot of calls to de.metas.ui.web.websocket.WebsocketSender.WebsocketEventsQueue.sendEvent(String, Object, boolean). 
* On my local, the console is flooded with lines like these: https://pastebin.com/97jp503G. In the end, the HUs are correctly created and the process ends OK.
* But on our testing system, the connection is sometimes lost, probably because of the huge amount of sends to the web socket. This is from the testing log file: https://pastebin.com/yQ7yFtxq
* Noticed that a lot of calls come from de.metas.ui.web.window.model.DocumentCacheInvalidationDispatcher.reset(CacheInvalidateMultiRequest)
* Probably the reason is that my serial nnumber process has to call invalidateView() many times, but this cannot be avoided. The process needs the new HUs always up to date.

**Comment by metasnw** [comment]
@teosarca I noticed this issue is still in dev although IT was done. is there more stuff todo?
I am asking cause the result is needed in master next week

**Comment by metas-rc** [comment]
Update: I made a working increment. Now the logic is more decoupled from the frontend
TODO: Refactor so the new process also has access to something similar with de.metas.ui.web.handlingunits.process.WEBUI_M_HU_Transform.updateViewFromResult(WebuiHUTransformCommandResult).
ATM there is one case when the view is not updated instantly (when we have CUs with no parent).
Also, I need to add some docu in the code.
I'll take care of these tomorrow

**Comment by metas-rc** [comment]
Update: I made abother WI with refactored code. I also moved some methods in a separate class to shorten some of the classes before. 
Remaining problems: 
1) When adding serial numbers to top level CUs or for singular CUs, the modification is not observable instantly. 
2) I am not sure if the frontend flooding console was solved.

**Comment by metas-lc** [comment]
IT
I. LU-TU-CU
1. open hu editor with 1 LU 5 TU and 10 CU
2. select the line with CU, run Add CUs with serial number
3. add e.g. 10 serialNos, separated by comma, semicolon or linebreak  
=> a new ifco was created, with 10 CUs OK
=> CUs have the serial numbers i added OK
=> the connection was fine OK

4. select the CU line with the remaining qty (40), run Add CUs with serial number
5. add 11 serialNos
=> new TU with 10 CUs created - each with serialno
=> new TU with 9 aggregated CUs created without serial no and 1 TU with serial No OK

6. pick another CU and this time Add CUs with serial number, writing more serialNos than the number of the CUs you selected (e.g. select the line with 9 CUs and write 12 serial nos)
=> only those 9 CUs were updated with serial Nos OK

7. pick a random CU line, one that has serial No, run Add CUs with serial number
=> serial no was updated to the latest one OK
(but you need to change the line and get back because there is a refresh issue and you can't see the change right away)

8. create material receipt 
=> i have 20 product lines (because of different attributes), correct qty (50 in total)
=> 1 line for TU qty 5 OK
=> 1 line for LU, qty 1 OK

II. TU-CU
1. open HU editor with 5 TU and 10 CU
2. repeat similar cases from above: add serial numbers to <=10, >10, update a serial number and create material receipt
=> "Add CUs with serial number" worked fine
=> inout was created with 5 TUs OK
=> one line for 5 TUs OK
=> but on the product line, the qty was 31 instead of 50 NOK
(have to check why and how)

II. TU-CU
1. open HU editor with 10 CU
2. repeat similar cases from above: add serial numbers to <=10, >10, update a serial number and create material receipt
=> "Add CUs with serial number" worked fine
=> inout was created with 10 product lines (because of different attributes), correct qty OK

**Comment by metas-lc** [comment]
IT
repeated the testcases above:
1. LU-TU-CU OK
2. TU-CU we have follow-up: https://github.com/metasfresh/metasfresh/issues/3452
3. CU OK
4. other: 1 LU 1 TU 10CU OK
