### ISSUE TITLE
Picking Tray Clearing: right side view shall display only the HUs for current BP/Location

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3211]
### Is this a bug or feature request?
FR
part of https://github.com/metasfresh/metasfresh/issues/3190

### What is the current behavior?
No matter what picking slot you select, on the right side view we see all HUs from all after picking locators.

### What is the expected or desired behavior?
On right side view we shall show only the HUs which are matching the selected picking slot.
If on left side, an HU row is selected, on right side we shall show the HUs which are matching the picking slot from where that HU belongs.

In this context, HUs are matching a picking slot if:
* they are from any after picking locator
* they have the same BPartner/Location as the Locator

#### Take out HU action
When taking an HU out, that action shall make sure the HU will have the BP/Location of picking slot set.
Hence, it will vanish from left side and it will be displayed on right side view.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

pls note: i tested with a new db so all picking slots were empty and no picking / picking clearing had been done before; also, all picking slots were dynamic and not rack system from the beginning.

1. Create 3 sales orders:
* 1) for bpartner A, address 1, testproduct
* 2) for bpartner A, address 2, testproduct
* 3) for bpartner B, testproduct
2. Create purchase order & material receipts for testproduct
3. Do picking & process it for each sales order:
* 1) picking slot 102
* 2) picking slot 103
* 3) picking slot 104
4. Check picking tray clearing for each picking slot:
* left side: each slot used shows the bpartner, with address & HUs picked: OK
* right side: is empty for all: OK
5. Take out the HUs from slot 102, check the other slots:
* slot 102:  left side is empty, HUs are now shown on the right side: OK
* slots 103 & 104: right side is empty bc slot is used for different address / bpartner: OK
6. Take out the HUs from slot 103, check the other slots:
* slot 104: right side is empty bc slot is used for different bpartner: OK
* slots 102 & 103: all HUs formerly in these 2 slots are now shown on the right side, bc slots are not used for a certain bpartner / address anymore: OK
* other slots not yet used: all HUs formerly picked in 102 & 103 are now shown on the right side: OK
7. Take out the HUs from slot 104 as well, so that left side is empty
8. Create another sales order for bpartner A, address 2, testproduct
9. Do picking for the last sales order, use picking slot 103 again (do not process the picking yet!)
10. Check picking tray clearing again:
* slots 102 & 104 and the rest: all HUs formerly picked in slots 102-104 are now shown on the right side, bc slots are not used for a certain bpartner / address anymore: OK
* slot 103:  
  * left side shows the bpartner, with address, but no HUs since picking wasn't processed yet: OK
  * right side shows only the HUs formerly picked in this slot bc the slot is already used for the same bpartner & address as before: OK
11. Open picking slots, and set slot 111 as
* IsDynamic='N'
* for bpartner C
12. Check picking tray clearing again:
* slot 111:  right side is empty bc slot is used for different bpartner now: OK
* rest is the same as in 10.: OK

=> picking tray clearing window:  i noticed that it sometimes took a little while / needed a refresh to show e.g. all HUs taken out on the right side /  i had to click on the breadcrumb again to have the new bpartner displayed in picking slot, i guess this is a frontend issue / thing?
