### ISSUE TITLE
New Filter for datepromised in Sales/ Purchase Order

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3275]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Filter for datepromised in Sales/ Purchase Order in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Filter for datepromised in both windows.

**Comment by metas-lc** [comment]
1. checked promised date filter in sales and purchase order. It looks like this 2018-01-08T02:00:00.000+02:00 and if you set an hour and then you want to set it again by leaving it on 12 you get an error (undefined has an invalid date.)
both shall be solved in 
https://github.com/metasfresh/metasfresh-webui-frontend/issues/1387

2. also it looks like it doesn't work filtering for minutes. E.g. 09.01.2018 at 12:59 AM (noticed because there are seconds as well) NOK?
3. didn't work for purchase order NOK
