### ISSUE TITLE
Different subscription Receiver for ever

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3354]
### Is this a bug or feature request?
FR

### What is the current behavior?
behaves like described in #2496

### What is the expected or desired behavior?
the user needs the option to permanently change the delivery partner

**Comment by cristinamghita** [comment]
## Rough concept
* Modify process de.metas.contracts.subscription.process.C_SubscriptionProgress_ChangeRecipient to allow DateTo empty
* Modify de.metas.contracts.subscription.impl.subscriptioncommands.ChangeRecipient.createRecipienRecordsQuery(ChangeRecipientsRequest) so that filter all subscriptions, starting with date From and allowing to chande the receiver to all

**Comment by cristinamghita** [comment]
CPed to Release branch

**Comment by metas-rc** [comment]
Results of IT

* Have a contract
* Open the process for chaning receipient
* OK: The date parameter is hidden after I click on the permanent flag 
* NOK: I can't run the process because the date parameter is still mandatory 
```
Error: Mandatory field DateGeneral not...
Server error
Mandatory field DateGeneral not filled
```

![image](https://user-images.githubusercontent.com/16001442/37906136-cafb48cc-3109-11e8-83ad-2a8c135ab933.png)

**Comment by metas-rc** [comment]
Results of IT


Tested on webui

* prepared testing data using IT here: https://github.com/metasfresh/metasfresh/issues/2502

* OK: the process is runnable now with the flag IsPermanentReceipient on true
* OK: The date parameter dissapears after I set the flag on true
* OK: After I run the process, all the exisitng subscritpions from now on are changed to have the selected patner and location


Regression: 
* Use he process with a date range
* => OK: The subscription progress entries in the selected range are changed according to the parameters
* OK: The rest of the subsctiprions are left untouched.
