### ISSUE TITLE
Schema for Product Planning Data

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3405]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we don't have the possibility to define default Distribution Order Schema and Product Planning Data for certain workflows.
#### Which are the steps to reproduce?
Open try and see.
### What is the expected or desired behavior?
Create a data structure that allows defining Schemas for Distribution and Product Planning Data.

**Comment by metas-rc** [comment]
Concept

* The Schema for Product Planning Data shall contain all the Product Planning columns, except product and BOM;
* The Schema shall also contain a selector to tell us for what kind of product the schema is good for;
* For the fime being, this selector will be a placeholder column called M_ProductPlanningSchema_Selector. Behind it there is a ref list which would have all the product types we need (e.g. Fridges, Normal products e.t.c.)
* This selector will also be added to the product as column. 
* The value for the selector will come from the import file as string (e.g. "N" for Normal Product)
* Right after a product is imported, a PP_ProductPlanning entry will be created for it based on the schema with the same selector as the product.
* (In discussion) There could be several schemas for the same selector. When a new product comes, one PP_ProductPlanning will be created for each schema ( => If there are 3  "N" (Normal Product) Schemas, the new product will have 3 product plannings
* Currently, the PP_Product_Planning has a unique index on (ad_client_id, ad_org_id, m_warehouse_id, s_resource_id, m_product_id). It is wrong  to add the schema id to the unique index because if we have 2 schemas with the same warehouse (by mistake)  and same selector => the initial index is violated. 
*

**Comment by metas-rc** [comment]
To be tested together with https://github.com/metasfresh/metasfresh/issues/3406 and https://github.com/metasfresh/metasfresh/issues/3404

**Comment by metas-rc** [comment]
TODO webui ( I'll put here the TODOs for all the tasks related)
* Add the window for Product planning schema, with layout conventions, translations and so on
* Display the flag for the product planning schema selector in the Product window
* Display the product planing schema in the prodcut planning window (maybe create a relation between them)
*

**Comment by metas-lc** [comment]
window missing from menu

**Comment by metas-lc** [comment]
IT
tested only on swing
1. open product planning schema
=> fields similar with product planning like resource, planner, workflow, network distribution, warehouse etc OK
2. check mandatory fields:
=> only: product planning schema selector OK
=> product planning schema selector only has the value of 'N' for now (will be populated according to customer needs) OK

follow-up for webui window: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1574
