### ISSUE TITLE
Distribution Order/ Movement after Material Receipt

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3409]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, when creating Material Receipt Candidates, the Target Warehouse is automatically set, depending on the Product, the Product Planning Data for Material Receipt and the Material Receipt Warehouse. This Target Warehouse leads to a directly generated Movement after the Material Receipt is completed.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
It shall be possible to decide if a movement is done directly or if a DD Orderline shall be created instead (flags/ info in Planning Data, Material Receipt Candidates). After Material Receipt completed, the system shall create a movement od create a DD Order instead.

**Comment by metas-rc** [comment]
Note:
Talked with Teo and he adviced to use the same method de.metas.material.planning.IProductPlanningDAO.find(Properties, int, int, int, int, int) for finding the product planning as in the logic for receipt schedules.
So as in that logic, I will call this method with the parameters  M_Warehouse_ID and  S_Resource_ID as value 0.

**Comment by metas-rc** [comment]
This means the product plannings mut have no M_Warehouse and S_Resource_ID set!

**Comment by metas-rc** [comment]
Documentation:

1) Config:
* The product P must have a Product planning.
* The product planning must have the flag IsCreateDistributionOrder on true, otherwise it is considered to require movements, by defalut.
* The product planning must have null values in M_Warehouse_ID and S_Resource_ID. 
* The product planning must have a Distribution Network with lines that have WarehouseSource the same as the order warehouse (W)
*NOTE: There will be an error if the above are not fulfilled.

2) How to test
* Create an purchase order for a product P, warehouse W.
* A receipt schedule (material receipt candidate) will be created for this order. Check it, it shall have isCreateDistributionOrder = true.
* Select the material receipt candidate, receive some HUs
* Run " Create Material Receipt"
* If all is fine, a distribution order shall be created for each product line in your new inout. Each distribution order will have one line only and it will be completed.
* The warehouse from i nthe dd_orderLine shall be the one from receipt schedule
* The warehouse dest shall also be the one from the receipt schedule, wether it was taken from the Product Planning or it was manually set.


* The logic above is the exact same one as the one used for getting the warehouses from distribution network for movements. Please create a followup with other requirements if they shall differ in the case of DD_Orders.

**Comment by metas-dh** [comment]
Update:

* manually set dest. warehouse in material receipt cand: could not set warehouse if there was no distribution network existing: according to @metas-rc a distribution network is not necessary; but a warehouse is generally only selectable as dest. warehouser in material receipt cand if there is a distribution network, so imho that's pk; @metas-mk wdyt?
* product planning with different warehouse from and dest. warehouse: distritbution order shows  the warehouses as set in product planning: OK
* could set >1 product planning with IsCreateDistributionOrder=Y, is that ok? the warehouse pre-set in material receipt cand as dest warehouse was the one from the plannng with lower ID, but the other one was selectable as well

**Comment by metas-dh** [comment]
Update after checking metas-mk:

* should work w/ empty dest. warehouse in material receipt schedule, => DD_Order w/ empty warehouse shall be created then (to be set by user later): not working, error when dest. warehouse is empty: NOK
* destination warehouse manual selection: any warehouse shall be selectable, not just those where a distribution network exits: not working, only warehouses which are dest. warehouses in networks can be selected: NOK (not sure this shall be fixed by this task)

**Comment by metas-rc** [comment]
> should work w/ empty dest. warehouse in material receipt schedule, => DD_Order w/ empty warehouse shall be created then (to be set by user later): not working, error when dest. warehouse is empty: NOK

The logic that sets the warehouse dest in the receipt schedule is the same logic that we use for the DD_Order line's locator to. And DD_OrderLine.LocatorTO is a mandatory column!

How can we set this mandatory column automatically if there is no network distribution that fits it?

**Comment by metas-rc** [comment]
> destination warehouse manual selection: any warehouse shall be selectable, not just those where a distribution network exits: not working, only warehouses which are dest. warehouses in networks can be selected: NOK (not sure this shall be fixed by this task)

* This is in M_ReceiptSchedule, right? 
* If it is, this is the rule: 
```
EXISTS( 
select *
 from DD_NetworkDistributionLine ddl
join DD_NetworkDistribution dd on ddl.DD_NetworkDistribution_ID = dd.DD_NetworkDistribution_ID 
where ddl.M_WarehouseSource_ID = @M_Warehouse_ID@ 
and M_Warehouse.M_Warehouse_ID = ddl.M_Warehouse_ID
 and ddl.isActive = 'Y' 
and dd.isActive = 'Y')
```


* Shall I delete it in this task?

**Comment by metas-rc** [comment]
Talked with Mark and he advised to create a followup for the remaining issues and move this task to done.
Here is the followup https://github.com/metasfresh/metasfresh/issues/3625
