### ISSUE TITLE
Credit Limit data structure as subtab in Businesspartner

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3413]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently the Credit Limit functionality only allows 1 setting for credit limit of a business partner.
#### Which are the steps to reproduce?
Open and see,
### What is the expected or desired behavior?
Create a new Data Structure that has the following content (besides the default columns):
a) Reference List entry "credit limit type" e.g. managing director, insurance
b) "date"
c) "createdBy"
d) "credit limit amount"

Create a Credit Limit indicator in BusinessPartner Header (virtual column) that says something like "95%" (which means the business partner credit limit has reached 95%).

**Comment by cristinamghita** [comment]
##Rough concept
* Create a new table called C_BPartner_CreditLimit with next columns:
  * Type (ref list e.g. managing director, insurance)
  * Amount
  * Date
  * ApprovedBy
  * C_BPartner_ID
  * and the usual mandatory fields
* Create a virtual column in C_BPartner - CreditLimitUsage - that will show the percent obtained from total opened balanced and credit limit
* for computing total opened balance, use the logic from org.adempiere.bpartner.service.impl.BPartnerStatsDAO.retrieveTotalOpenBalance(IBPartnerStats)

**Comment by cristinamghita** [comment]
![image](https://user-images.githubusercontent.com/15378036/35631344-5288af24-06ac-11e8-88fe-a318ea1e2939.png)

**Comment by metas-lc** [comment]
IT 
Please check the following NOKs: steps 5, 6 and probably 10

1. open bpartner, select one and go to last subtab: Business Partner Credit Limit
2. add a new line (insurance, amt 100, date from and date to)
3. add a new line, exactly the same as the line above
=> you can still see both lines and there is no red line indicating the Bpartner is not saved (frontend issue) NOK
4. remove the second line
5. set the amount to 0 
=> you get errors (division by 0) and you can't open bparther anymore NOK
6. created some invoices 
=> Credit limit Usage is still 0. NOK the credit limit usage doesn't update if you don't recreate the limit line
7. add a new line with Managing Director, amt 50
=> Credit limit Usage updated OK
8. if you have insurance and managing, always managing has priority OK
9. no matter what currency you have in invoice, the Credit limit Usage updates OK
10. i reverted an invoice and Credit limit Usage didn't update NOK i think
--
11. separate conversion case: have ONLY 2 invoices: one 2.14 EUR and one 1.69 CHF 
12. have one limit amount 100
=> credit limit after the first invoice was 2.24 OK (it's because conversion) and for my second one 1.69+2.24=3.93 OK

**Comment by metas-lc** [comment]
steps 5, 6 and 10 will be solved in https://github.com/metasfresh/metasfresh/issues/3414
step 3: https://github.com/metasfresh/metasfresh-webui-api/issues/827
