### ISSUE TITLE
"Issue only for what was received" not working anymore

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3463]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Issue method "Issue only for what was received" not working:
* product with that issue method set, e.g. Folie, disappears from HU editor after select & issue, although nothing was received yet
* product, with that issue method set, e.g. Folie, disappears from HU editor after receipt, although nothing was issued yet
* HU is not displayed in the HU Editor anymore, but also not shown as issued (Swing: field remains white, WebUI: HU not displayed in the left window), but in HU Editor window, HU is displayed with status: Issued.
#### Which are the steps to reproduce?
Try with product Convenience Salat, have components as real HUs in production warehouse!
1. Have 2 PP_Orders
2. For 1 order, issue the Folie before receive: whole HU disappears, but is not displayed as issued: NOK
3. For the other order, receive: whole HU with Folie disappears, but is not displayed as issued: NOK
4. Check for the HUs of Folie in HU Editor window: status: Issued: NOK
### What is the expected or desired behavior?
Issueing of this type of product shall only be possible after the receipt, and only in the qty needed for production.

**Comment by metas-dh** [comment]
Update:
from last customer e2e:

Steps to reproduce:
2. still happening
3. HU still displayed after Receiving, can be issued and the qty issued is correctly displayed, BUT: whole HU is issued and disappears from HU Selection, the qty issued is not substracted from the overall qty: NOK
4. Check for the HUs of Folie in HU Editor window: status: Issued (whole HU): NOK

**Comment by teosarca** [comment]
### Concept
(we need it only for WEBUI)

In Manufacturing Issue/Receipt have another action called `Issue CUs from source HUs` which shall be similar with `Issue TUs from source HUs` but instead of issuing TUs shall issue CUs.
![image](https://user-images.githubusercontent.com/1244701/40108326-41d6a27c-5903-11e8-9382-572ea8cc8066.png)
![image](https://user-images.githubusercontent.com/1244701/40108410-7206406a-5903-11e8-9bfa-5c602bf8970f.png)


Now, in case we are dealing with a product which shall be issued just to cover the received quantity (using standard proportions), 
We shall calculatate that quantity and set it as default value for the QtyCU parameter.
User shall be allowed to change it.

Technically speaking, check following references:
* de.metas.material.planning.pporder.IPPOrderBOMBL.calculateQtyToIssueBasedOnFinishedGoodReceipt(I_PP_Order_BOMLine, I_C_UOM). Btw, check from where is called. Get rid of swing code which is about this topic and it does not work/it's not used.

* de.metas.handlingunits.pporder.api.impl.hu_pporder_issue_producer.CreateDraftIssues.calculateQtyToIssue(I_PP_Order_BOMLine, IHUProductStorage) - another place where we apply the same algorithm. Chek where they are called. On a quick look they are called by some of current webui processes...

**Comment by metas-rc** [comment]
Regression testing neeed for: 
* All the HU transformations
* Adding HUs with serial numbers

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. New action: `Issue CUs from source HUs` : **OK**

2. Issue CUs when method **Backflush**:
* QtyCU suggested in the modal is the full QtyCU from the source HU, if 1 source HU, even when > QtyCU needed: **OK** for now, checked with metas-mk: to suggest QtyCU needed would be FR
* QtyCU suggested in the modal can be changed by the user: **OK**
* QtyCU suggested in the modal is QtyCU from one of the source HUs, if >1 source HU (have not figured out the pattern for which one is taken), but it's not always the one with the lowest HU ID: **NOK**, shall be the QtyCU of the HU with the lowest ID! (see #3210)
* UOM of QtyCU suggested / issued is the UOM from BOM line: **OK**
* QtyCU after issueing displayed correctly under product line: **OK**
* QtyCU after issueing summed up correctly in product line: **OK**
* QtyCU after issueing is substracted correctly from the source HU: **OK**
* issue a certain QtyCU > QtyCU available in source HU: => nothing is issued: **NOK**, shall issue the QtyCU from >1 source HU, in the order of IDs (see #3210):
   * => e.g. if you have 3 source HUs with QtyCU: 10, IDs: 1, 2, 3, and you issue QtyCU: 20 => HUs with IDs 1 & 2 shall be issued

3. Issue CUs when method **Issue only for what was received**:
* QtyCU of product needed for the QtyReceived is set as default value for the QtyCU: **OK**
* user is allowed to change it: **OK**
* QtyCU is only set after received & processed: **OK**, but: cannot remove that since the action is not available anymore, read-only after process! **NOK** 
   * => the action `Remove HU` shall still be available for those product lines with issue method **Issue only for what was received**, after the manufacturing order was processed
* issue a certain QtyCU > QtyCU available in source HU: => QtyCU available in source HU is issued, **OK**, but: => no more QtyCU can be issued bc the order is processed, and there is no access to the HU Editor anymore! **NOK** 
   * => the action `HU-Auswahlfenster öffnen` shall still be available for those product lines with issue method **Issue only for what was received**, after the manufacturing order was processed, so user can select a new source HU
   * => QtyCU default value set for that new source HU: shall be QtyCU needed - QtyCU already issued

**Comment by metas-lc** [comment]
IT
repeated testcase from 3. Issue CUs when method Issue only for what was received:
=> the qtys for rolle when you issue is calculated using uom coversion OK
1. the action Remove HU is still available for those product lines with issue method Issue only for what was received, after the manufacturing order was processed OK
2. use Remove HU 
=> it removes the CU that was issued  OK
=> it moves it to HUs to issue OK
=> qty is updated to 0 OK
3. issue a certain QtyCU > QtyCU available in source HU: 
=> QtyCU available in source HU is not issued NOK
=> if there is no  available source HU, there is no access to the HU Editor anymore NOK

testcase for no. 3:
1. have some folie as source (doesn't matter how much)
2. receive and process a salad
3. go to folie and issue something like 200 (let's say you need 28886 - that's for 100 salads)
4. select that 200mm of folie and use Remove HU
5. select the line with the source HU and remove it from the source
=> notice that you cannot make other HU as source, because you don't have access to hu editor NOK
6. create a new manufacturing order, just to set the source HU
7. set that 200mm folie as source HU
8. go back to your manufacturing order and issue 28886mm (while you have only 200mm in source HU)
=> nothing happens NOK
(as i understood, QtyCU available in source HU should be issued)

**Comment by metas-dh** [comment]
![2018-07-04 13_52_45-metasfresh](https://user-images.githubusercontent.com/18696715/42275913-19a25804-7f92-11e8-9f52-ce27c8250a2f.png)


![2018-07-04 13_54_35-metasfresh](https://user-images.githubusercontent.com/18696715/42275918-1f6e7a06-7f92-11e8-8104-d9b9d9a9a911.png)

**Comment by metas-rc** [comment]
Errors from IT solved

**Comment by metas-rc** [comment]
I found this issue while testing around manufacturing: https://github.com/metasfresh/metasfresh/issues/4348

**Comment by metas-dh** [comment]
Results of IT4
tested in mf15

3. Issue CUs when method **Issue only for what was received**:
3.4 action "HU-Auswahlfenster öffnen" is still available for those product lines with issue method Issue only for what was received, after the manufacturing order was processed, so user can select a new source HU: **OK**
    * issueing QtyCU > QtyCU on source HU: full source HU was issued, also the next full HU (with correct order of IDs, from lowest to higher ID): **OK** 
    * QtyCU default value set for that new source HU: shall be QtyCU needed - QtyCU already issued: **OK**

problems i had while testing:
1. UOM in PP_Order used for the component with method **Issue only for what was received** is mm; for testing i transformed a HU with UOM: Rolle, so new HU had qty<1: 
=> this HU was fully issued, but the UOM: Rolle was treated like UOM: mm, there was no conversion:
![2018-07-11 10_20_53-notificationsform](https://user-images.githubusercontent.com/18696715/42561350-327c5b2e-84f9-11e8-914f-551f0c746bc4.png)

 the conversion worked fine however when issueing from a HU with qty:1 => substraction was done correctly, 1 Rolle - QtyIssued (in mm) = e.g. 0,70743 Rolle:
![2018-07-11 10_55_17-notificationsform](https://user-images.githubusercontent.com/18696715/42561356-3928ccfa-84f9-11e8-9305-a512108f0ce5.png)


2. the source HUs that were issued fully before processing the PP_Order, are not displayed in the HU Editor anymore once after the order is processed, OK; but the source HUs for method **Issue only for what was received** are only issued after the order is processed, so they remain displayed in the HU Editor (also for future PP_Orders!) until manually taken out: OK?
