### ISSUE TITLE
Div material dispo issues

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3541]
### Is this a bug or feature request?
Both

### What is the expected or desired behavior?

- [x] add the resp sales order in material dispo and allow to zoom from sales order to material dispo
  - [x] same for forecastid and shipmentscheduleid
- [x] show 0 in quantity columns, instead of something like 0+E-16 
- [x] display PP_Product_Planning_ID in details tab
  - [x] @metas-mk the physical column is there..can you pls make sure it's shown in the UI?
- [x] display MD_Candidate.M_AttributeSetInstance_ID
- [x] check what the flag Flag Distributionsauftrag erstellen in production-planning is about
  - [x] do issue https://github.com/metasfresh/metasfresh/issues/3549 Refactor config for Distribution Order/ Movement after Material Receipt
- [x] don't display "Lager" rows. instead, display ATP right in the respective Supply or Demand row
  - [x] @metas-ts integate into master
  - [x] @metas-mk please display the new `Qty_AvailableToPromise` sql column in the webui
- [x] display demand records with a negative qty
  - [x] @metas-ts integate into master
  - [x] @metas-mk please display the new `Qty_Display` sql column in the webui
- [x] solve a bug wrt having a certain event update "later" ATP/Stock records

Note (generally, if i check a checkbox, i mean that it's integrated into `master` )

**Comment by metas-dh** [comment]
*  add the resp sales order in material dispo and allow to zoom from sales order to material dispo: OK
   * same for forecastid: and shipmentscheduleid: OK
*  show 0 in quantity columns, instead of something like 0+E-16: OK
*  display PP_Product_Planning_ID in details tab: OK
   *  @metas-mk the physical column is there..can you pls make sure it's shown in the UI?
*  display MD_Candidate.M_AttributeSetInstance_ID: OK
*  check what the flag Flag Distributionsauftrag erstellen in production-planning is about: => #3409, OK
   * do issue #3549 Refactor config for Distribution Order/ Movement after Material Receipt, Done, OK
*   don't display "Lager" rows. instead, display ATP right in the respective Supply or Demand row: OK
    * @metas-ts integate into master
    * @metas-mk please display the new ```Qty_AvailableToPromise``` sql column in the webui
*   display demand records with a negative qty: OK
    * @metas-ts integate into master
    * @metas-mk please display the new ```Qty_Display``` sql column in the webui
*   solve a bug wrt having a certain event update "later" ATP/Stock records: to check
