### ISSUE TITLE
Sorting defect: Change of Flatrate Term in Sales Orderline after grouping

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3612]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when adjusting a Flatrate Term in Sales Orderline after compensation group creation, the line numbers are recalculated and the sorting breaks. The sum lines are not there where they should be. 
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall remain correctly sorted.

**Comment by metas-ts** [comment]
:cherries: to `20170302-2_hf1`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* set up compensation groups etc. as described in  https://github.com/metasfresh/metasfresh-webui-api/issues/853#issuecomment-366973448
* created a contract period & term (tested that in another sales order: worked fine there)
* created a sales order, and ran Multigroup lines action: sorting acc. to compensation group schema: OK
* set the contract term for one of the products: term was set, but then the value was set back to none: NOK (nothing in console, no error?)

**Comment by metasnw** [comment]
## Regression (verified on current master)
1. have one product
1. run multi group lines (new automatic process) so that one discount line is added
https://w101.metasfresh.com:8443/window/143/1000528
![image](https://user-images.githubusercontent.com/16079655/37056999-4b2ed790-2186-11e8-9a42-f38bc39107c7.png)
1. select a line and use add group process (not the automatic but the old one)
1. add any discount product 
1. NOK: the new discount product replaces the old.
![image](https://user-images.githubusercontent.com/16079655/37057078-7ec1a97a-2186-11e8-8c62-65d3684e51ea.png)
1. NOK: when you run multi group again it replaces the manual discount product

Expectation: Multi group does not have any impact on manual discount lines and vice versa

**Comment by metas-dh** [comment]
=> also happening in mf15cloudit, NOK

**Comment by teosarca** [comment]
@metasnw  @metas-dh  i am on it

**Comment by teosarca** [comment]
update:
Preserve manually added compensation lines.

Also introduced a process to add manual compensation line.
The `Group lines` process shall be used only for grouping not already grouped lines.

**Comment by teosarca** [comment]
note to it: full e2e test for this functionality is needed.

**Comment by metasnw** [comment]
@teosarca did a full e2e including combining automatic and manual discounts.
found one problem:
manual discounts are sorted before the automatic lines but I expect them to be always after the automatic lines.

**Comment by metasnw** [comment]
@teosarca after the fix the sorting works for the manual discounts if you have one group. 
But if you are having two groups the manual discount is sorted at the end of ALL groups.
Expectation: Sort it to the end of its own group.

**Comment by metasnw** [comment]
@teosarca tested on latest master: all cases were fine

**Comment by metas-dh** [comment]
IT successful, see above.
