### ISSUE TITLE
WebUI: New Inventory Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3652]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Inventory Window is missing in WebUI
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the Inventory Window in WebUI Menu and create Window, Grid View, Sidelist, Advanced Edit and Subtab Layout.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: The window Physical Inventory was added to the menu
* OK: The window respects our layout conventions and cornerstones
* OK: The included tab has a white background
* OK: All the fields are translated into English and German.

* NOK: The product and locator cannot be inserted manually in the inventory line because of the callout org.compiere.model.CalloutInventory. This problem should be fixed in #2647.
