### ISSUE TITLE
Lot-No lock & control

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3693]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we don't have a functionality for lot no. lock and control in metasfresh.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
- Allow to record lot no in hu editor/ material receipt (should already be possible).
- New Data structure and window for the recording of product, lot no ... default fields for lots that shall be locked.
- Action in that new Window that searches for all Handling Units with locked Lot No. When found, then creates a new Distribution order entry to be moved to blocked-warehouse. Add a Text to distribution orderline that has the reason for this distribution "product with locked lot no".
- Same functionality in material receipt. When recording a lot no that is found in locked table, then create a distribution order after material receipt to move to blocked-warehouse.

**Comment by metas-rc** [comment]
Open questinos: 
1) Shall the dd_orders be done with one line each? Like we do after receipt complete?
2) If a receipt comes with several products and only one of them has a locked lot number, shall all the products be blocked?

**Comment by metas-rc** [comment]
Update: The Block will be renamed to Quarantine everywhere.

**Comment by metas-lc** [comment]
Part 1
1. create/complete a purchase order with 2 products
2. go to Product LotNo Lock window and create 2 new entries. P1 999 and P2 998. Add description to both
3. go to receipt candidates and open hu editor with both products at the same time
4. transform in such a way that you have 3 TUs for P1 and 2 TUs for P2
5. P1: 1 TU with lotno 999, 1TU lotno 998, 1 TU without lotno
6. P2: 1 TU with lotno 998 and 1 TU with lotno 998 and quality issue
7. select all 5 TUs and create receipt
note: i didn't make any config before, to make sure i get the following errors: 
=> error because no issue wh was found OK 
(added issue wh and made receipt again)
=> error because no quarantine wh was found
Error: Error Processing Document document: Produktanlieferung...
Server error
Error Processing Document document: Produktanlieferung 1000019 Belegverarbeitung: CO Cause: Es konnte kein Sperrlager gefunden werden. (AdempiereException) OK
(added quarantine wh and made receipt again)
=> error because i don't have in transit wh
(added in transit wh and made receipt again)
8. create receipt
=> 1 receipt created for both products. 1 line is quality issue OK
=> 1 distribution order created with 2 lines: for P1 and P2, correct qty: P1 10, P2 20,
wh from = po wh, wh to quarantine
dd orderlines have descriptions like: "desc P2 998; Handling Units: 1000095, 1000097" OK
=> 3 requests created: 2 for the dd orders, summary and bpartner taken from dd order
1 for quality discount, summary taken from quality attribute and bpartner from inout. In rest all 3 requests are the same OK
.

Part 2
9. go to Product LotNo Lock window and run the "quarantine HUs for locked lot number" process, for a line that already has dd order
=> 
Error: org.postgresql.util.PSQLException: ERROR: duplicate key...
Server error
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "dd_orderline_hu_candidate_hu" Detail: Key (m_hu_id)=(1000095) already exists. SQL: INSERT INTO DD_OrderLine_HU_Candidate (AD_Client_ID,AD_Org_ID,Created,CreatedBy,DD_OrderLine_HU_Candidate_ID,DD_OrderLine_ID,IsActive,M_HU_ID,Updated,UpdatedBy) VALUES (1000000,1000000,TO_TIMESTAMP('2018-03-27 14:45:21','YYYY-MM-DD HH24:MI:SS'),2188223,nextval('dd_orderline_hu_candidate_seq'),1000002,'Y',1000095,TO_TIMESTAMP('2018-03-27 14:45:21','YYYY-MM-DD HH24:MI:SS'),2188223) RETURNING DD_OrderLine_HU_Candidate_ID  OK
10. create multiple receipt candidates with lotnos/products (remember the lotnr and the products)
11. go to Product LotNo Lock window, create multiple product lotno locks (for those on step 10) and select all entries and run "quarantine HUs for locked lot number" process
=> new dd orders created (noticed that for different products, you get different dd orders. Else you get 1 dd order with multiple lines)
=> new requests created OK
12. check the invoice candidates for your order
=> both products are in dispute OK
.

Regression
1. went to product planning, selected the one for product P1
2. subtab planning data, set OnMaterialReceiptWithDestWarehouse to create movement and added a network distribution
3. created a new purchase order with P1, created receipt 
=> new movement was created OK
=> no new dd orders or requests OK
4. went to product planning again, selected the one for product P1, set OnMaterialReceiptWithDestWarehouse  to distribution order
5. created a new purchase order with P1, created receipt 
=> new dd order was created OK (it was created with inout bpartner!)
=> no new movement or requests OK

TODO: aggregate dd orders the same way. See step 11 in step 2

**Comment by metas-rc** [comment]
Requirement Update: The request shall be made for the partner from the parent receipt

**Comment by metas-lc** [comment]
IT
1. Request test
1. created 4 POs, 2 different bpartner, each with 2 different addresses
2. created receipts with lotno "aaa"
3. went to lotno lock and created a new one for my product and lotno "aaa"
4. ran Quarantine HUs
=> 4 new requests were created, for each bpartner/location (bp of receipt) OK 
5. created 1 receipt with quality discount. Checked requests 
=> new request was created for the bp of receipt OK

2. regression (testcases from IT1)
part 2 step 11 - i still get 2 different dd orders

**Comment by metas-lc** [comment]
IT
repeated IT1 and 2
=> part 2 step 11 - only 1 dd order OK
=> rest works the same OK

**Comment by metas-ts** [comment]
:cherries:picked to `release`
