### ISSUE TITLE
Contracts: Transform IsAutoRenew and IsAutoExtension flags in a list

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3718]
### Is this a bug or feature request?
FR

**Comment by cristinamghita** [comment]
Follow up [#3669 Create all periods of a contract on creation](https://github.com/metasfresh/metasfresh/issues/3669)

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: In the window Contract Periods, the field Extension Type is now list.

1) If the Extention type is for all periods

* I created 3 Contract Periods pointing to 3 contract terms, 1 year each, first 2 periods have next contract perms.
* I set their extention type to all periods
* I made a sales order and I selected the first, completed
* => OK : I got 3 contracts created for the next 3 years

2) If the Extention type is for Autorenewal

* I created a contract period pointing to a contract term, with Extention type for AutoRenew, 1 month
* I made a sales order and I selected the term, completed
* => OK: I got 1 contract
* => OK: The contract was flagged as IsAutoRenew
* => OK: The master end date was not set
* I extended the contract
* => OK: Got 1 new 1 month contract
* => OK: Both have master end date null
* Canceled the contract with a date (May 1 2018)
* => OK; Master end date mecame May 1 for both of them
* => OK: IsAutoRenew flag turned to false

3) Extention type not set
 * I created a contract period pointing to a contract term, with Extention type null, 1 month.
* I made a sales order and I selected the term, completed
* => OK: I got 1 contract
* => OK: Contract has IsAutoRenew = false
* => OK: Master end date 1 month since now
* I manually extended the contract 
* => OK: I got a new contract
* => OK: Masterenddate for both turned to 2 months from now
