### ISSUE TITLE
Credit Limit Detail Improvements

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3741]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, there are a few details that don't work with credit limit approval workflow:
Limits, also approved ones, can be deleted (shall not)
Kredit OnHold cannot be removed (automatic + action needed)
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Solve the topics above.

**Comment by metas-lc** [comment]
IT
1. go to bpartner and add a credit limit. Do not approve it. Delete it
=> you can delete it OK
2. Add a new credit limit, and ask for approval. Delete it
=> you can delete it OK
3. Add a new credit limit, and approve it. Delete it
=> you cannot delete it OK
4. go to statistics tab and select your line. Go to actions and run Remove hold status
5. set the flag on Y, start
=> credit status is Credit Stop OK
6. go to statistics tab and select your line. Go to actions and run Remove hold status
7. set the flag on N, start
=> credit status is Credit OK (or depending on your credit limits, can be on hold or watch) OK
8. run Remove hold status again, with flag on Y
=> credit status is Credit Stop OK
9. add a new credit limit, that would usually modify the status to credit OK
=> nothing happens, status still on stop OK
10. try to create orders, invoices, payments
=> you can't because of the credit status OK
