### ISSUE TITLE
Automactically process picked CU's

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3778]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the user has to explicitly start the action to process picked HU.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Allow configuring in Picking Configuration, that the processing of a picked CU happens automatically after picking action. When the user picks, then the HU is automatically processed.

**Comment by metas-rc** [comment]
Concept: 

* Add a flag in picking config
* If flag is true, run de.metas.handlingunits.picking.PickingCandidateService.processForHUIds(List<Integer>, int, OptionalInt) in de.metas.ui.web.picking.husToPick.process.WEBUI_HUsToPick_PickCU.pickCUs()

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* not properly implemented, script not included in the db

**Comment by metas-dh** [comment]
Update:
* with the flag unset, i
1. pick CUs: i get back to HU Editor for a split sec, but that closes by itself so i'm back in
2. picking slot automatically, where i have to process the CU: OK

* with the flag set, i 
1. pick CUs: i get back to HU Editor, where the CU is shown as destroyed
2. have to click to get back to picking slots
3. have to process the CU, since it's actually still active: NOK
