### ISSUE TITLE
Improve qty TU calculation for invoice jasper

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3790]
### Is this a bug or feature request?
FR
### What is the current behavior?
The qty TU is usually correct in invoice jasper, but for some corner cases (e.g. different TU types plus >1 LU with different asi in same material receipt) still have incorrect qty TU in invoice jasper.
#### Which are the steps to reproduce?
Example:
material receipt, correct:
![2018-03-29 13_39_18-notificationsform](https://user-images.githubusercontent.com/18696715/38087515-b642486c-3358-11e8-8cce-6cd48feef2fa.png)

purchase invoice, incorrect:

![2018-03-29 13_39_49-notificationsform](https://user-images.githubusercontent.com/18696715/38087522-bbe2d4a8-3358-11e8-9920-ccf1cc2f30bd.png)

### What is the expected or desired behavior?
Improve the way how the qty TU in invoice jasper is calculated.

**Comment by metas-lc** [comment]
the problem is in the last union of Report.fresh_IL_To_IOL_V
we get duplicates if we have 1 IC on 2 inout lines and 2 invoice lines.
.
That sql was made for sales invoice lines that don't have a direkt link - but also for purchase invoices, that have direct link but they don't have match inv for leergut.
.
i think the best solution would be to check first if there is a direct link or not (M_MatchInv - for purchase and invoiceline-inoutline for sales)
.
test: sales and purchase invoices and also invoices that contain returnables
.
est 10h

**Comment by metas-lc** [comment]
please also test (and drag to IT) https://github.com/metasfresh/metasfresh/issues/3554 . It has the same issue behind

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* still had problems when asi were set in material receipt, but not in purchase order: NOK
* had a very similar case as described above in latest e2e, prob. not yet integrated in release? : NOK

**Comment by metas-lc** [comment]
Hi. There is a case, when you do inout with e.g. Frisee. One line has 2 HU, one only CU. 
Somehow, in invoice, they both get in 1 line, qty TU 3 2HU+1CU
that's why in jasper we will see qtyTU 3 instead of 2. 
.
is it correct to have qtyTU 3 in invoice? or the lines to be groupped?
i think we have a task to always set qtyTU to 0 when there is only CU
11:46 AM
right now is 1

**Comment by metas-dh** [comment]
checked with metas-mk: will close this task since the Jasper was improved and the testcase is somewhat of a cornercase, will create a new issue if necessary in the future.
