### ISSUE TITLE
Check if Product is banned in Batch entry/ Document Lines creation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3834]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, all Products can be recorded in document lines as long as they are available on product prices of the price system.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Build a check in Batch entry/ document line creation. If a user tries to record a banned product (shall be recordable in a separate data structure) then the user shall receive an error message (additional info string from ban list). The product shall not be able to be recorded for the given customer + product combination.

**Comment by teosarca** [comment]
### Concept

In C_BPartner_Product table, introduce following fields:
* IsSalesBan
* SalesBanReason - text, 2000, shall not be empty if IsSalesBan=Y

Introduce following AD_Message:
* Value: ProductSalesBanError
* MsgText: Product not allowed to be sold to customer {0} because {1}

When user tries to create an sales order line/sales invoice line and there is a C_BPartner_Product record for given product and bpartner, a record which has IsSalesBan=Y then we shall throw an exception immediately.
The `ProductSalesBanError` shall be used to build the error message.

**Comment by metas-lc** [comment]
IT
1. create/complete a new sales order with 2 different products, bpartner Test Kunde 1
2. go to one of those products, bparter product tab and create a new one, set Exclusion from sales documents on Y
=> Exclusion From Sale Reason field appears and is mandatory OK
3. write a reason in Exclusion From Sale Reason
4. create a new sales order with bpartner Test Kunde 1, add both products
=> a product was added fine, and the one with exclusion was not added (you could select it in batch entry, but you get error)
error: Product not allowed to be sold to customer Test Kunde 1 because <reason>.
5. create a new sales order , bpartner B, same product
=> products were added fine
6. repeat the same testcase with sales/purchase invoice
=> if you do the invoice manually, you cannot add the product (you get the same error) OK
=> if you invoice existing ICs with that product, you can invoice OK
7. repeat the same case with purchase order
=> it works the same - you cannot add that product line and you get error OK??

note: the fields are not translated in de_DE

**Comment by metas-lc** [comment]
found trls: 
Exclusion from sales documents= Produkt Sperre Verkauf, 
Exclusion From Sale Reason= Produkt Sperre Grund

**Comment by metas-lc** [comment]
Exclusion From Sales works the same for sales and purchase order. Shall we make it works only for sales?

**Comment by metas-mk** [comment]
Nope, shall be possible on sales and purchase side.
