### ISSUE TITLE
migration script not logged for creating new ad_ui_section when value is not manually filled

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3847]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?

**Case 1**

1. create a new ui section
1. only fill name
1.save
1. NOK: check migration script:
![image](https://user-images.githubusercontent.com/16079655/38730078-7b73f64a-3f15-11e8-86fa-ce89e3a03b70.png)

**Case 2**

1. create a new ui section
1. fill name AND search key
1.save
1. OK 

![image](https://user-images.githubusercontent.com/16079655/38730038-5943f282-3f15-11e8-8de7-a9f7c2442cf4.png)

### What is the expected or desired behavior?
should always work

**Comment by teosarca** [comment]
Fixed. Now the migration script looks like:
```sql
INSERT INTO AD_UI_Section (AD_Client_ID,CreatedBy,IsActive,AD_UI_Section_ID,AD_Tab_ID,AD_Org_ID,Name,UpdatedBy,Updated,Created,SeqNo) VALUES (0,100,'Y',540722,186,0,'test',100,TO_TIMESTAMP('2018-04-28 12:45:31','YYYY-MM-DD HH24:MI:SS'),TO_TIMESTAMP('2018-04-28 12:45:31','YYYY-MM-DD HH24:MI:SS'),30) 
RETURNING Value
;

INSERT INTO AD_UI_Section_Trl... (not important)
```

Remark the `RETURNING Value`.
That's happening because  in case a mandatory field is not filled on save time, our framework assumes it will be populated on database level so the INSERT is without `Value` but the `Value` is expected to be returned back from database.

In this particular case it's actually happening this because the AD_UI_Section.Value column is defined as
```sql
  value character varying(40) NOT NULL DEFAULT nextval('ad_ui_section_seq'::regclass),
```
If it would not have a default, the INSERT would simply failed.

And failing, IMHO i think it would be better because when producing migration scripts we would like to be as precise as possible and not rely on target database to generate a Value for us.
@metas-ts  @metasnw  @metas-mk  wdyt?

**Comment by metas-ts** [comment]
> And failing, IMHO i think it would be better because when producing migration scripts we would like to be as precise as possible and not rely on target database to generate a Value for us.
@metas-ts @metasnw @metas-mk wdyt?

Aggree. This seems like a hack which ends us up having different `AD_UI_Section.Value`s on different machines. Does anybody know why we have this default in the DDL? 
Maybe this hack just indicates that we have no use for the value column?

**Comment by teosarca** [comment]
hmmm, i think, the process which generates the ui section/columns/elements it is relying on that.... good that u asked :)

**Comment by metas-lc** [comment]
IT
created new UI Section and got the insert + RETURNING Value at the end OK
but created followup for calculating the value
https://github.com/metasfresh/metasfresh/issues/4211
