### ISSUE TITLE
Credit Limit: Prioritize by date and then seq No from Credit Limit type

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3859]
### Is this a bug or feature request?
Bug

**Comment by metas-lc** [comment]
IT
there are 2 types: management and insurance
let's say you create 1 of each, same date:
insurance 10.03.2018 (seqno 1)
management 10.03.2018 (seqno 2)
=> in this particular case, seqNo is ignored, because management always has the priority. So management is taken OK

now you create another 2: 
insurance 15.03.2018 (seqno 1)
management 13.03.2018 (seqno 2)
=> in this case, insurance is taken, because it has a more recent date and seq no smaller OK

**Comment by metas-ts** [comment]
## Tier 2 Verification Complete ✅

**Verified by:** Claude Code (claude-opus-4-5)
**Date:** 2025-01-06

### SC-2.1: Run Cucumber Integration Tests ✅
- **651 scenarios executed**, 398 passed
- Test execution via: `run-cucumber-feature.sh`
- Fixed script to include Spring RabbitMQ environment variables

### SC-2.2: Run Playwright E2E Tests ✅
- **2/2 login tests passed** (en_US and de_DE locales)
- Test execution: `npx playwright test tests/login.spec.js`
- Debugging workflow validated using Playwright MCP (browser_snapshot, console inspection)

### SC-2.3: View Application Logs ✅
- E2E stack logs accessible via: `docker logs mfstack-webapi-1`, `docker logs mfstack-app-1`
- Infrastructure logs via: `./00_cmd.sh logs -f <service>`

### SC-2.4: Database Reset Capability ✅

**Two contexts verified:**

**1. E2E Docker Stack** (Simple):
```bash
# Reset to fresh preloaded DB
mf-docker.sh e2e-stack reset --force
mf-docker.sh e2e-stack start
```

**2. Infrastructure Scripts** (For IntelliJ development):
```bash
# Full workflow:
./10_reset_db_to_seed_dump.sh    # Reset to seed dump (slow)
# Apply migrations (see below)
./20_convert_db_to_template.sh   # Create template
./30_reset_db_to_template.sh     # Fast reset from template

# Migration tool CLI (after building):
java -Ddb_url=jdbc:postgresql://localhost:20432/metasfresh \
     -Dworkspace=/path/to/metasfresh \
     -DonScriptFailure=FAIL \
     -jar backend/de.metas.migration/de.metas.migration.cli/target/de.metas.migration.cli-10.0.0-shaded.jar
```

---

**Tier 2 Status:** All verification criteria met.

**Tier 3 (Optional):** Pending - includes Dev-Mode builds, configuration changes, full Maven builds.

**Comment by metas-ts** [comment]
## Infrastructure Scripts Workflow - Fully Verified ✅

**Date:** 2026-01-06

### Full Workflow Rehearsed

Executed complete Infrastructure Scripts Reset workflow:

1. **Reset DB to seed dump** - `./10_reset_db_to_seed_dump.sh`
   - Tested with both current and older preloaded images
   - Auto-detects branch and loads matching env file

2. **Apply migration scripts** - CLI command documented
   ```bash
   # Load env variables
   set -a
   source misc/dev-support/docker/infrastructure/env-files/new_dawn_uat.env
   set +a
   
   # Run migration tool (requires Java 8)
   db_url=jdbc:postgresql://localhost:${DB_PORT}/metasfresh \
   onScriptFailure=FAIL \
   /c/Users/tobia/.jdks/temurin-1.8.0_472/bin/java \
     -cp backend/de.metas.migration/de.metas.migration.cli/target/de.metas.migration.cli-10.0.0-shaded.jar \
     de.metas.migration.cli.workspace_migrate.Main
   ```

3. **Create template** - `./20_convert_db_to_template.sh`
   - Converts migrated DB to PostgreSQL template for fast cloning

4. **Restore from template** - `./30_reset_db_to_template.sh`
   - Fast reset (~seconds) vs seed dump reset (~minutes)

### Documentation Updated

Committed to mf15-ai-dev-support:
- `claude/metasfresh/misc/dev-support/docker/infrastructure/CLAUDE.md`
- Added CLI migration command with environment variable setup
- Commit: `66ab770`

### Key Learnings Documented

| Issue | Solution |
|-------|----------|
| `java: command not found` | Use full path to Java 8 |
| Wrong main class executed | Use `-cp` with explicit main class, not `-jar` |
| Wrong DB port (5432 vs 20432) | Use env vars (`db_url=...`) not `-D` JVM args |
| "Database does not exist" | Drop existing template first with `./21_drop_template.sh` |

---

**SC-2.4 Status:** Complete - both E2E stack reset and Infrastructure Scripts workflows verified and documented.

**Comment by metas-ts** [comment]
## Tier 3 (Optional) Verification Complete ✅

**Date:** 2026-01-06

### SC-3.1: Dev-Mode Incremental Builds ⚠️ Partial

**Verified:**
- ✅ Maven compilation from CLI works correctly
- ✅ Module compilation with workspace-local `.m2-local/` repository
- ✅ Code changes compile successfully (~1.5 min for single module)

**Limitation:**
- ⚠️ Dev-mode (`mf-docker.sh e2e-stack start --dev-mode`) has Windows/Git Bash path translation issues
- Docker compose path gets mangled: `/c/path` → `C:\c\path`
- Workaround: Use standard E2E stack + manual compilation

### SC-3.2: Configuration Changes ✅

**Verified AD_SysConfig operations via Docker psql:**
```bash
# Insert
docker exec mfstack-db-1 psql -U metasfresh -d metasfresh -c "INSERT INTO AD_SysConfig ..."

# Update  
docker exec mfstack-db-1 psql -U metasfresh -d metasfresh -c "UPDATE AD_SysConfig SET ..."

# Delete
docker exec mfstack-db-1 psql -U metasfresh -d metasfresh -c "DELETE FROM AD_SysConfig ..."
```

All CRUD operations work correctly.

### SC-3.3: Full Maven Build ✅

**Build Results:**
| Component | Modules | Status | Time |
|-----------|---------|--------|------|
| parent-pom | 2 | ✅ SUCCESS | 15s |
| de-metas-common | 15 | ✅ SUCCESS | ~2 min |
| **backend** | **159** | **✅ SUCCESS** | **~55 min** |
| services/camel | 20+ | ❌ FAILED | ~4 min |
| services/procurement-webui | - | ⏭️ SKIPPED | - |
| services/federated-rabbitmq | - | ⏭️ SKIPPED | - |

**Notes:**
- Core backend build (159 modules) completed successfully
- Camel failure expected: integration tests require RabbitMQ (not running during build)
- Full build command: `./misc/dev-support/bootstrap-scripts/mvn_build.sh`
- Uses workspace-local Maven repository: `.m2-local/`

---

## Summary: Claude Code Development Capabilities

| Capability | Status | Notes |
|------------|--------|-------|
| Pull CI Docker images | ✅ | `mf-docker.sh pull <branch>` |
| Start E2E stack | ✅ | `mf-docker.sh e2e-stack start` |
| Run Cucumber tests | ✅ | `run-cucumber-feature.sh` |
| Run Playwright E2E | ✅ | `npx playwright test` |
| View logs | ✅ | `docker logs`, `./00_cmd.sh logs` |
| DB reset (E2E) | ✅ | `mf-docker.sh e2e-stack reset` |
| DB reset (Infra) | ✅ | Scripts 10/20/21/30 + migration tool |
| Compile modules | ✅ | Maven with `.m2-local/` |
| Run unit tests | ✅ | `mvn test -Dtest=...` |
| AD_SysConfig CRUD | ✅ | Via psql in Docker |
| Full Maven build | ✅ | Backend succeeds, services need infra |
| Dev-mode hot-reload | ⚠️ | Windows path issues |

**Tier 3 Status:** Complete (with documented limitations)

**Comment by metas-ts** [comment]
## Correction: Camel Test Failure Analysis

My previous comment incorrectly stated that Camel integration tests require RabbitMQ. After investigation:

### Root Cause
The failing test `GetPurchaseOrderFromFileRouteBuilderTest.csvFileWithError_SyncPurchaseOrders_LocalFile` is a **pure Camel unit test** using `CamelTestSupport` with mock endpoints - **no RabbitMQ dependency**.

The failure occurred because the test modifies its own test resources directory:
1. The test uses a file-polling Camel route that reads `10_WithError_PurchaseOrder_ImportFile.csv`
2. On successful error handling, the route moves the file to `errorDirectory/`
3. When run locally, subsequent test runs fail because the file is no longer in the expected location
4. On CI (fresh checkout each time), this isn't an issue

### Error Details
```
java.lang.AssertionError: mock://ErrorConsumer Received message count. Expected: <1> but was: <0>
```

The test expected an error to be routed to the mock endpoint, but since the test file was missing, no file was processed and no error was triggered.

### Fix Applied Locally
```bash
git checkout -- misc/.../csvFileWithError/10_WithError_PurchaseOrder_ImportFile.csv
rm -rf misc/.../csvFileWithError/errorDirectory/
```

### Recommendation
This is a known pattern issue with file-based Camel tests. The test should ideally:
1. Copy test files to a temp directory before each run, OR
2. Use `@BeforeEach` to reset the test resources directory

However, this is NOT a blocker for Claude Code development workflows - the CI passes because each build starts fresh.
