### ISSUE TITLE
Pharma: Don't allow recording of pricing conditions that are not allowed

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3891]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is allowed to define pricing schema/ discount schema as you want. Same for Sales Orderlines, the user can adjust Prices and discounts freely (in general).
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The following rules shall restrict the recording of sales Orderlines and discount schema (pricing conditions):
- Is about FAM products (Field in M_Product)
- All Products with FAM shall be checked for a minimal allowed price in pricing conditions and sales orderlines.
-- if product is rx product ("Verschreibungspflichtig")
-- if customer has only pharmacy permission
-- Price from certain Pricelist (sysconfig or minimal pricing condition config)
-- plus Fixum amount (sysconfig or minimal pricing condition config)
-- max discount in payment term (sysconfig or minimal pricing condition config)
==> if priceactional - discount from payment term is lower than minimal pricing condition config then not allowed.

==> Dynamic limit price calculation and enforceing

### Configuration
Set following sysconfigs:
* de.metas.order.NoPriceConditionsColorName
* de.metas.order.TemporaryPriceConditionsColorName

**Comment by metas-mk** [comment]
minimal pricing conditions config
==> pricing system? + fixum - discount payment term
==> Grosso + 0,70 EUR - 3%
==> Prod1: 10,00 EUR + 0,70 EUR - 3% = 10,38 (minimal allowed price)


Sales Orderline
Pricing System supercheap
BP1 (is Pharmacy = yes)
Product Prod1 (rx product) -->
==> Prod1: 9,00 EUR - 2% = 9,41 (priceactual - discount from line paymentterm)
==> Prod1: 20,00 EUR - 10% = 18,00 (priceactual - discount from line paymentterm)



Pricing conditions
BP1 (is Pharmacy = yes)
Product Prod1 (rx product) -->
==> Prod1: 9,00 EUR - 2% = 9,41 (priceactual - discount from line paymentterm)
==> Prod1: 20,00 EUR - 10% = 18,00 (priceactual - discount from line paymentterm)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

SetUp:
* created new test pricelist for testing, with:
    * pricelist has force price limit= Y
    * only 1 test product: FAM product, and rx product ("Verschreibungspflichtig") = Y
    * standard price for the test product: 2,00 EUR
* created new bpartner with only pharmacy permission = Y, with that pricelist set as customer pricelist
* set price limit restriction: for this test pricelist, + 0,70 EUR, minus 3% => 2,62 EUR for test product
* discount schema: 10% discount when qty 10 or more, set for bpartner

Test: Sales Order for the bpartner:
* sales orderline with the test product: price set is 2,00: NOK, shall be 2,62
* change the price manually: when manual price is <2,62, then it is set to 2,62: OK (but no info for user?)
* with price 2,62 (qty: 1): set manual discount e.g. 10%, so that effective price overall is <2,62: NOK
* with price 2,62 (qty: 1): set qty: 10: price is set to 2,00 again and discount 10% is added: NOK

**Comment by teosarca** [comment]
> change the price manually: when manual price is <2,62, then it is set to 2,62: OK (but no info for user?)

see https://github.com/metasfresh/metasfresh-webui-frontend/issues/1613

**Comment by teosarca** [comment]
NOTE: requires full regression testing on everything around pricing :(

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

SetUp: as described above

Test: Sales Order for the bpartner:

1. sales orderline with the test product, qty: 1: 
* "price" set is 2,00: OK?
* "net price": 2,62, "line net amt": 2,62: OK i think
* Discount: -31%: OK?
2. change price manually, <2,62, e.g. 1,00: 
* "price" gets changed to 1,81: why? (it was changed again when i tried to set price: 1,00 again, this time to 1,45)
* "net price" & "line net amt" remain 2,62: OK i think
* Discount: changed to -44,75%: OK?
3. change price manually, >2,62, e.g. 3,00: 
* "price" as changed, 3,00: OK
* "net price" & "line net" are changed accordingly as well: 3,00: OK
* Discount: 0: : OK 
4. set qty:10 for Discount Schema: with "price": 2,00:
* "price": 2,00: OK?
* "net price" & "line net amt" remain 2,62: OK i think
* Discount remains -31%: OK?
5. set qty:10 for Discount Schema: with "price": >2,62, e.g. 3,00: 
* "price": 3,00: OK 
* "net price" & line net are set acc. (2,70 / 27.00): OK 
* Discount: 10%: OK
6. manual discount: was possible to set a manual discount of e.g. 10% for price: 2,00, so that the overall price per product is <2,62: NOK i think


ToDo: regression testing on everything around pricing :(

**Comment by metas-dh** [comment]
Update:
checked with metas-mk:

1. sales orderline with the test product, qty: 1:
* "price" set is 2,00: NOK, no price below the price limit restriction (here: 2,62) is allowed as price, must not be shown in the orderline as price

![2018-05-11 16_38_03-metasfresh](https://user-images.githubusercontent.com/18696715/39930074-01548bf0-553a-11e8-815a-cf27c3489f95.png)


2. change price manually, <2,62, e.g. 1,00:
* "price" gets changed to 1,81:  NOK, has to be set to 2,62

![2018-05-11 16_38_28-metasfresh](https://user-images.githubusercontent.com/18696715/39930098-0df0086c-553a-11e8-9fbf-5d8af8ac0de5.png)

6. manual discount: was possible to set a manual discount of e.g. 10% for price: 2,00, so that the overall price per product is <2,62: NOK

**Comment by teosarca** [comment]
Note to IT: full pricing regression is still needed :(

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

SetUp: as described above

Test: Sales Order for the bpartner:

1. sales orderline with the test product, qty: 1: 
* "price" set is 2,62: **OK**
* "net price": 2,62, "line net amt": 2,62: **OK**
* Discount: 0%: **OK**
2. change price manually, <2,62, e.g. 1,00: 
* "price" is set back to 2,62:**OK**
* "net price" & "line net amt" remain 2,62: **OK**
* Discount: remains 0%: **OK**
3. change price manually, >2,62, e.g. 3,00: 
* "price" as changed, 3,00: **OK**
* "net price" & "line net" are changed accordingly as well: 3,00: **OK**
* Discount: 0%: : **OK**
4. set qty:10 for Discount Schema: with "price": 2,62:
* "price": 2,62: **OK**
* "net price" & "line net amt" remain 2,62: **OK**
* Discount remains 0%: : **OK**
5. set qty:10 for Discount Schema: with "price": >2,62, e.g. 3,00: 
* "price": 3,00: **OK**
* "net price" & line net are set acc. (2,70 / 27.00): **OK**
* Discount: 10%: **OK**
6. manual discount: 
* not possible to set a manual discount of e.g. 10% for price: 2,62 (or lower, since that is not possible anymore, see 2.): **OK**
* set manual discount for "price": >2,62: possible until you reach net price 2,62: e.g. with price 3,00, manual Discount is possible up to 12% (=> net price: 2,64), when you want to set it higher than that, it remains at 12.67% which is net price 2,62 (for both qty:1 or higher): **OK**

question:
i could set a group discount, with the actions "Group Lines" / "Add group compensation line" and get an overall price per product <2,62, which is NOK, but afaiu that is not a realistic case for the customer using this feature? @teosarca @metas-mk wdyt?

ToDo: regression testing on everything around pricing :(

**Comment by teosarca** [comment]
> i could set a group discount, with the actions "Group Lines" / "Add group compensation line" and get an > overall price per product <2,62, which is NOK, but afaiu that is not a realistic case for the customer using > this feature? @teosarca @metas-mk wdyt?

IMHO it's OK because that's an overall discount.
You could also add another line with some product and have there an -20EUR net amt.
@metas-mk  wdyt?

**Comment by metas-dh** [comment]
checked with metas-mk: customer is not using the group discounts, so it's OK like this

**Comment by metas-dh** [comment]
no full regression testing done after last changes, checked with metas-mk: move to done, will create new issue when problem with pricing pops up.
