### ISSUE TITLE
Credit limit: treat credit status on NULL as it would be X (No check)

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3910]
### Is this a bug or feature request?
FR
### What is the current behavior?
If somehow, the credit status is null, the credit limit check fails with a NPE
### What is the expected or desired behavior?
When credit status is NULL, no check shall be done regarding credit limit.

**Comment by cristinamghita** [comment]
## Dev test
### Prerequisites
* Configure the partner like this. Partner also should be in agroup with credit satatus *No credit check*
 ![image](https://user-images.githubusercontent.com/15378036/39179278-94316afa-47bc-11e8-9e40-6b540aa2c34a.png)
 ![image](https://user-images.githubusercontent.com/15378036/39179296-a3acd320-47bc-11e8-9c63-705d4a8037b0.png)
### Test
* Create a sales order and complete it
   * The order is complete and credit status in statistics is not changed
### Regression Test - credit status : No credit check
* Configure the partner to have credit status: No credit check 
( Also add a credit limit of 100
* Create a sales order with an amount bigger the 100 and complete it
   * The order is complete and credit status in statistics in not changed
### Regression Test - credit status : OK and amount in the credit limit
* Configure the partner to have credit status: OK
* Create a credit limit of 100
* Create a sales order with an amount of 40 and complete it
   * The order is complete and credit status in statistics is still ok; Amount of credit used is updated.
### Regression Test - credit status : OK and amount over the credit limit
* Configure the partner to have credit status: OK
* Create a credit limit of 100
* Create a sales order with an amount of 110 and complete it
   * The order can not be completed

**Comment by metas-lc** [comment]
IT
1. empty on credit status. Create and complete order and invoice
=> documents completed without errors OK
=> credit status in statistics in not changed OK 

2. empty on credit status. Approved credit limit. Create and complete order and invoice
=> documents completed without errors OK
=> credit status in statistics in not changed OK 

3. No credit check on credit status. Approved credit limit. Create and complete order and invoice
=> documents completed without errors OK
=> open balance was set in statistics (?)
=> credit status in statistics in not changed OK 

4.  credit status : OK. Approved credit limit. Create and complete order and invoice (bigger sums than credit limit)
=> for order you get error message that you can't OK
=> for invoice you can (also for manual one OK? ) OK
=> credit status updated on hold OK 
 
5. create a new credit limit, bigger than credit used
=> credit status updated on "credit OK" OK 

6. create sales order so that credit limit updates to credit watch
=> credit status updated on "credit watch" OK 

7. try to create an order with amount over the credit limit
=> couldn't complete OK

other: 
noticed that if you reactivate/void a sales order, credit used is not updating. You need to create a new credit limit and then it updates OK?
