### ISSUE TITLE
Fail on complete for order lines with no pricing conditions

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3917]
Followup for https://github.com/metasfresh/metasfresh/issues/3835

### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently, when the sys config de.metas.order.NoPriceConditionsColorName is set with a colour name and an orderline with no discount schema break ( which in this context will be called Pricing Conditions) is created, the colour is is set for the orderline.
#### Which are the steps to reproduce?
*  The test cases are all described in https://github.com/metasfresh/metasfresh/issues/3835, which was already ITed.
### What is the expected or desired behavior?
* Now we have to throw an exception when somebody wants to complete an order which contains a line as above, if the said sys config is set.
* The line shall be left untouched. This kind of lines will be dealed with in a future task.

**Comment by metas-lc** [comment]
IT
tested based on IT from https://github.com/metasfresh/metasfresh/issues/3835
=> where i didn't have discount schema, i got the following error: 
<Error: Error Processing Document document: Standardauftrag...
Server error
Error Processing Document document: Standardauftrag 0042 Document Action: CO Cause: The order can not be completed because pricing conditions are missing. Please modify. (AdempiereException)>
OK
.
problem found:
1. make discount schema for product A
2. create purchase order with product A and put it on an HU
3. complete
=> you can't complete because the HU doesn't have schema
(if you add the HU in schema break, then you can complete the order)
is this OK or NOK? 
if NOK how it shall work?
