### ISSUE TITLE
Change Picking Terminal columns and fix auto process picking

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3923]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Using Picking with autoprocess = Y brings the following issues
- after picking a CU the user does not see (sho qtypicked instead of qty picked planned) the qty that he has already picked
- leaving the picking modal the picked qty is not shown in main view
- the shipment schedule qtypicked is not updated
#### Which are the steps to reproduce?
Open, try and 
### What is the expected or desired behavior?
Please fix the issues above.
Follow-Up for https://github.com/metasfresh/metasfresh/issues/3778

New requirements: 

* in Picking Terminal, replace the qtyToDeliver with the QtyOrdered ( this will never change)
* replace qtyPickedPlanned with QtyPicked which will be the sum of the already picked qty and the qty which is planned to be picked.

* Note: m_packageable_v will be changed. The 2 new columns will be added in it

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* in Picking Terminal, replace the qtyToDeliver with the QtyOrdered (this will never change): OK
* replace qtyPickedPlanned with QtyPicked which will be the sum of the already picked qty and the qty which is planned to be picked: OK
* after automatic picking of a CU the user now sees the qty that he has already picked, since it is QtyPicked and not QtyPickedPlanned: OK
* leaving the picking modal the picked qty is shown in main view: QtyPicked and QtyOrdered are missing in main view, NOK:

![2018-04-25 15_32_19-metasfresh](https://user-images.githubusercontent.com/18696715/39249052-06165374-489e-11e8-8b56-ec451319f85f.png)

* the shipment schedule QtyPicked is updated: only for QtyPicked, QtyPickedPlanned is not considered: OK (remaining issue: => QtyPicked not updated in shipment schedule after reactivate & unpick in picking terminal: #3916)

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* QtyPicked: back in main window, but in both en_US and de_DE: pls call it "Kommissionierte Menge" again in de_DE, as before
* QtyOrdered: now in main window, instead of QtyToDeliver: OK, but: "Bestellt/ Beauftragt" in both en_US and de_DE: pls call it "Qty Ordered" in en_US
