### ISSUE TITLE
Lot No Action error when running multiple times

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4013]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When creating a Lot No Lock entry and running the action "Move Lot No to quarantine warehouse" the corresponding HU entries are created in Distribution Editor. Running the same action again lead to an error.

![image](https://user-images.githubusercontent.com/13365687/39706682-760eb482-5212-11e8-9912-b44808be7d4d.png)

#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall not show an error, shall just check again if there are further HU to be moved.

**Comment by metas-lc** [comment]
IT
1. create a new lot control
2. create a purchase order and receipt for that product, with the same lotnumber
=> new distribution order was created OK
3. go to lot control, select "Move lotno. to Quarantine Warehouse"
=> nothing happens, no errors, the dd order was not affected OK
4. create a new receipt, with a new lotnumber e.g. 111
5. create a new lot control, same no like in step 4 (111)
6. run "Move lotno. to Quarantine Warehouse"
=> new dd order created OK
7. run it again
=> nothing happens OK
8. create receipt with at least 2 HUs, without lotno
9. go to handling units and set lot numbers to each. One with 111 and one with what you had at step 1
(i had to use handling units pos from swing, because in webui the attributes are readonly)
10. run "Move lotno. to Quarantine Warehouse" again for both lot controls
=> 2 new dd orders were created OK
