### ISSUE TITLE
Proforma Invoice via Sales Order workflow

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4035]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Prepayment Functionality in Sales Order is deactivated.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Reactivate and adapt the prepayment functionality via sales order.
- User creates a sales order with doctype prepayment order.
- The sales order is completed. No Shipment schedules nor Invoice candidates are created. The sales order document (Proforma Invoice) is sent to the customer for prepayment.
- The customer pays the proforma invoice. The Payment is recorded manually in Payment window.
- The shipment candidates are created. The invoice candidates are created.
- As soon as the invoice is generated, the invoice is marked as paid (because of prepayment allocation).

**Comment by cristinamghita** [comment]
## Dev test
* Create a prepay order
   * Complete the order -> Status is _Waiting for payment_
    ![image](https://user-images.githubusercontent.com/15378036/40305230-4ed82b96-5d02-11e8-9d0c-8ca87c40d7dd.png)
   * No Shipment schedules nor Invoice candidates are created. 
* Now user creates a Payment is recorded manually in Payment window and completes the payment.
   *  No allocations is created, but the shipment candidates are created. The invoice candidates are created.
   ![image](https://user-images.githubusercontent.com/15378036/40305276-7b756d08-5d02-11e8-9d59-363d79fc78f5.png)
* User goes to the shipment schedule and creates the shipment
   ![image](https://user-images.githubusercontent.com/15378036/40305344-d24d2558-5d02-11e8-9d6f-d453ad613d7b.png)
* Then goes in invoice candidates window and generate the invoice.
   *  When the invoice is completed, the payment si allocated against this invoice and the invoice is marked as paid.
   ![image](https://user-images.githubusercontent.com/15378036/40305394-155dac14-5d03-11e8-971e-e7c47289ce54.png)


![image](https://user-images.githubusercontent.com/15378036/40305390-0fec618a-5d03-11e8-9b5b-51458e146c40.png)

**Comment by metas-dh** [comment]
**Update:**

**questions:**
1. => new doctype is created, "Proforma Invoice": **OK**
2. => When the order contains packing items, the ICs for those are only created after the shipment is created, therefore the payment for the order includes the amt for the packing item, which is missing in the invoice => no full allocation, since invoice amt < payment amt. In case the order  does not contain packing items, then the payment is marked as allocated after the invoice is created (before shipment), since invoice amt = payment amt: **OK**
3. => set Over/Under Payment=Y in the payment, befroe completion: => payment can be allocated to other invoices as well, workflow for prepayment remains the same: **OK**
