### ISSUE TITLE
Enhanced Pricing: Discount Break is falsely invalidated

### ISSUE THREAD

**Issue by metas-Kay** [metasfresh/metasfresh#4063]
### Is this a bug or feature request?
BUG

### What is the current behavior?
**Surcharge on Standard Price** is invalidated when switching from value *Pricing System* to *Fixed* and back again in an active Discount Schema/Pricing Conditions Schema, giving a **Not valid reason**:

![ispriceoverride](https://user-images.githubusercontent.com/29163573/40117211-90860300-5916-11e8-9a25-26ae8968ee60.png)

...even though the product *is* on the price list.

#### Which are the steps to reproduce?
**Requirements:**
- a price list (e.g. "Testpreise Kunden (Deutschland)" from price system "Customer Prices") including a product (e.g. "Convenience Salat") and linked to a business partner (e.g. "Test Kunde 1")

**Steps:**
1. Create a discount scheme following http://docs.metasfresh.org/webui_collection/EN/Automatic_volume_discount.html with **Product** "Convenience Salat", **Break Value** and **Break Discount %** = 0.
1. Check **IsPriceOverride**.
1. Select **PriceBase** *Pricing System*.
1. Select **Base_PricingSystem_ID** *Customer Prices*.
1. Enter a **Aufschlag auf Standardpreis**, e.g. 2,50.
1. Go to BP record of "Test Kunde 1" and select the discount scheme in the customer tab. (*Up to this point, when creating a Sales Order afterwards, the enhanced pricing works normally and the surcharge is added.*)
1. Return to the discount scheme window and open the adv.Edit window of the created discount break.
1. Switch **PriceBase** to *Fixed* and back to *Pricing System*.
=> The discount break is invalidated and the **Not valid reason** appears below in read-only.
==> Remove the discount scheme from the BP record customer tab again, repeat the switch: the **Not valid reason** disappears and the discount break is valid again.

### What is the expected or desired behavior?
If the product does exist on the price list that is linked to the customer and everything is in order and you toggle between *Fixed* and *Pricing System*, the discount break should stay valid the whole time.

**Comment by metas-lc** [comment]
e.g. of broken discount schema https://w101.metasfresh.com:8443/window/233/1000025

**Comment by teosarca** [comment]
When you are saving a discount schema break, the line is validated and the limit price, if any, it's enforced (see https://github.com/metasfresh/metasfresh/issues/3891).

### How it worked before
In order to accomplish that, the system is fetching all BPartners which use that schema and all their locations.
In this case it failed for [Testkunde Kunde 1](https://w101.metasfresh.com:8443/window/123/2156425)
had a location which was in Georgia but there was no price list for Georgia.

### How it is working after this task
If the break has base pricing then we fetched all countries from the base pricing system pricelists.
We are enforcing the price limit for those countries.

If the break has a fixed price, we are fetching all the countries from price limit's base pricing system.
We are enforcing the price limit for those countries.

**Comment by metas-lc** [comment]
IT
1. have a bpartner with a country that is not in a pricelist (e.g. ro)
2. create a new discount scheme (see the steps above 1-5)
3. go to your bpartner from step 1 and set the discount scheme in the customer tab
4. go back to discount scheme, edit the line: switch PriceBase to Fixed and back to Pricing System
=> works, the scheme is still valid OK
.
5. create a new pricelist with other country than de or ch. e.g. pl. 
6. Add a pricelist version, don't add any product prices
7. go back to discount scheme, edit the line: switch PriceBase to Fixed and back to Pricing System
=> the scheme is not valid anymore. Message: "Product is not on PriceListProduct: P002737_Convenience Salat 250g, Price List: Testpreise Kunden (PL), Country: Poland, Date: 05/22/2018"
OK
8. add the product on the pricelist
9. go back to discount scheme, edit the line: switch PriceBase to Fixed and back to Pricing System
=> works, the scheme is valid OK
10. create a new sales order, add product, complete 
=> works, no errors OK
