### ISSUE TITLE
Batch entry product ID

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4127]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the product batch entry has a hardcoded feature only showing product value and name.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
It shall respect the product identifier configured.

**Comment by teosarca** [comment]
update: not the product lookup in all quick inputs (order, invoice, forecast) will respect following format:
* regular product identifier string => i.e. the actual requirement of this task
* `_`
* the ProductNo for current BPartner (see https://github.com/metasfresh/metasfresh/issues/2484)
* `_`
* attribute/storage info (see https://github.com/metasfresh/metasfresh-webui-api/issues/663)

**Comment by metas-lc** [comment]
IT
1. set a field isIdentifier to Y and add a seq no (e.g. product category)
=> shown in batch entry OK
2. the ProductNo for current BPartner - taken OK
(also tested without it)
3. attribute/storage info 
=> was not shown NOK
 configs: QueryEnabled is on Y
AttributesKeys on 1000007, 1000011
(those are m_attributevalue(s))

**Comment by teosarca** [comment]
@metas-lc  it's happening because that product has a negative storage and the sysconfig `de.metas.ui.web.window.descriptor.sql.ProductLookupDescriptor.ATP.DisplayOnlyPositive` is set to `Y`es.

To check/chage the sysconfig, i've used following SQL + cache reset (ofc you can do it from UI):
```sql
update AD_SysConfig set value='N' where name='de.metas.ui.web.window.descriptor.sql.ProductLookupDescriptor.ATP.DisplayOnlyPositive';

select name, value
from AD_sysconfig where name='de.metas.ui.web.window.descriptor.sql.ProductLookupDescriptor.ATP.DisplayOnlyPositive'
```

To check the current available to promise (ATP), i've checked the `Material schedule` window, filtered by my product, sorted descending by DateProjected and remark that big fat negative ATP:
![image](https://user-images.githubusercontent.com/1244701/40926575-2ca484ce-6825-11e8-8479-be55a85c723d.png)

**Comment by teosarca** [comment]
Ahh, and btw, even after setting `de.metas.ui.web.window.descriptor.sql.ProductLookupDescriptor.ATP.DisplayOnlyPositive` to `N`o, in Batch Entry you will see ZERO and not that negative number (it's a feature :) )

**Comment by metas-lc** [comment]
@teosarca Thank you. Works now :)
