### ISSUE TITLE
Picking: Show HU Products with not exact Attribute matching

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4146]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, in WebUI, we show only Handling Units in Picking which match exactly. In Swing Client, we also have the possibility to show HU with the same Product but different Attributes.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Also, allow selecting the "fuzzy" mode, showing handling Unit with the same Product but does not care about the same Attributes.

**Comment by metas-rc** [comment]
Mhen picking, there is a new filter that only contains one flag: if the flag is on true, only the HUs that have the attributes from the shipment schedule shall be displayed, otherwise all of them should be available.

**Comment by teosarca** [comment]
@metas-ts integrating it as is. the performance problem can be solved later in https://github.com/metasfresh/metasfresh/issues/3412 as u suggested.

**Comment by metas-lc** [comment]
IT
1. create a sales order with 2 lines: one without attributes, one with 2 attributes A and B
2. create a purchase order with the same product. Do receipt with HUs without attributes, HUs with attributes A and B, attributes A and C, attributes A or B, attributes  A, B and other, attributes C and D
3. from sales order go to picking terminal. Select the line without attributes, open HU editor
=> you can see all HUs (even from other products) NOK. Task: https://github.com/metasfresh/metasfresh/issues/4276
4. filter for attributes on N
=> you can see all available HUs for your product (attributes are ignored) OK
5. filter for attributes on Y
=> you can see all available HUs for your product (attributes are ignored) OK
6.  Select the line with attributes, open HU editor
7. filter for attributes on N
=> you can see all available HUs for your product (attributes are ignored) OK
8. filter for attributes on Y
=> you can see all available HUs for your product and attributes (attributes are considered) OK
.
9. while you have HUs filtered, press on ">>" (next page)
=> the filter is gone NOK https://github.com/metasfresh/metasfresh-webui-frontend/issues/1858
.
10. pick HUs: some from line without attributes: with/without attributes. Some for the line with attributes pick: with (matching and not matching)/without attributes
=> works, no errors OK
11. process HUs
=> works, no errors OK
12. go to sales order, zoom into shipment dispo
=> qty picked is set correctly for each line OK
13. select both lines, run generate shipments, set "Use picked quantity instead of to be deliver.." on Y
=> inout created correctly OK
