### ISSUE TITLE
Improve error message regarding illegal HU status changes

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4161]
### Is this a bug or feature request?
FR
### What is the current behavior?

the message just tells which illegal state transition e.g. (destroyed => shipped) was attempted

### What is the expected or desired behavior?

the message shall also contein the HU in question.

**Comment by metas-lc** [comment]
IT
1. tested on both webui and swing:
2. create new sales order, go to picking terminal and pick an HU (for swing open hu editor)
3. using sql: update the HU you want to pick, to hustatus "D" (destroyed) or "E"(shipped). 
(note: if you use D in webui you'll get other kind of error, because it won't find the HU)
4. pick and process your HU (swing: select your hu, press ok)
=>

```
Illegal M_HU.HUStatus change from E to S; hu=X_M_HU[M_HU_ID=1000101, Value=1000101, trxName=TrxRun_e2ac967c-a72c-4b43-9abb-5b4e4ccaa26b] Additional parameters: HowtoDisableModelInterceptor: Model interceptor method de.metas.handlingunits.model.validator.M_HU#validateStatusChange threw an exception. You can disable this method with SysConfig InterceptorEnabled_de.metas.handlingunits.model.validator.M_HU#validateStatusChange='N' (with AD_Client_ID and AD_Org_ID=0!)
```

OK
