### ISSUE TITLE
If C_DocType_Trl description exists, use this as description in document

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4185]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The text from the normal Description in C_DocType is taken, not description in C_DocType_Trl, in the document.
#### Which are the steps to reproduce?
1. Have description in C_DocType_Trl set, for the language used for your bpartner
2. Have the checkbox 'Copy description to documument'='Y' for the C_DocType
3. Create a document of that C_DocType, with your bpartner, check the Jasper: the translation is not used: NOK
### What is the expected or desired behavior?
Shall take description from C_DocType_Trl in document (e.g. in order.description) if set.

**Comment by metas-lc** [comment]
IT (see step 5)
tested for sales and purchase order and invoice, since inout doesn't have description and descriptionbottom set from doctype. See https://github.com/metasfresh/metasfresh/issues/3304

0. have a default description/document note for sales/purchase order/invoice doctypes. Go to translations: Don't have anything set for de_ch. Set descriptions for en_us

1. Create a new sales order for Bpartner A with language en_us
=> description and description bottom are taken from doctype trl for en_us OK

2. Create a new sales order for Bpartner B with language de_ch
=> description and description bottom are taken from default doctype (no trl) OK

3. Create a new purchase order for Bpartner A with language en_us
=> description and description bottom are taken from doctype trl for en_us OK

4. Create a new purchase order for Bpartner B with language de_ch
=> description and description bottom are taken from default doctype (no trl) OK

5. create invoices for the documents from above
=> description and description bottom are empty NOK

6. Create a new manual sales invoice for Bpartner A with language en_us
=> description and description bottom are taken from doctype trl for en_us OK

7. Create a new manual sales invoice for Bpartner B with language de_ch
=> description and description bottom are taken from default doctype (no trl) OK

8. Create a new manual purchase invoice for Bpartner A with language en_us
=> description and description bottom are taken from doctype trl for en_us OK

9. Create a new manual purchase invoice for Bpartner B with language de_ch
=> description and description bottom are taken from default doctype (no trl) OK

**Comment by metas-rc** [comment]
New requirement: 
Make sure the text is copied from doctype to the invoice no matter how it was generated.
When there is no text defined in doctype it shall work as before.

**Comment by metas-rc** [comment]
Note to IT: 
* Please, do regression testing on all the ways of creating invoices. If the doctype's description / document note are empty, please make sure the description is set as before

**Comment by metas-lc** [comment]
IT
1. repeat the testcases above
=> all work fine, in any case, the doctype description and docnote is set to order/invoice OK

2. regression: go to document type and set "Copy description to document" on N
repeat the testcase above
=> in every case, the doctype description and docnote were not copied to order/invoice OK
