### ISSUE TITLE
Pharma: DeliveryType B disallow Sales Orderline

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4218]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the user receives a Message if trying to record an RX Product and the BPartner only is allowed DeliveryType B.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
After entering the Quantity in batch Entry, then show an Error Message. Don't allow the recording of the line.

**Comment by metas-lc** [comment]
IT
Sales:
1. Have product A - prescription and product B - not prescription
2. have BPartner with shipment pharmacy permission type A 
3. create a sales order and add both products
=> no errors, products are added OK
4. Update shipment pharmacy permission to type B
5. create a new order and add both products
=> product B is added OK
=> product A not: The product A is a prescription medicine and may not be sold to the customer Test Kunde 1. Reason: TYPE_B" OK
6. go to your order from step 3 and use copy with details
=> line is added and you can complete the order OK?
7. create a new sales order "type B" and add the product using add new (not batch entry)
=> line is added OK?
.

Purchase:
1.  have BPartner with receipt pharmacy permission type A 
2. create a new purchase order and add both products
=> you can add them, no errors OK
3. update receipt pharmacy permission to type B
4. create a new purchase order and add both products
=> you can add both products - i would say OK, because the task was made for sales side
.

**Comment by metas-rc** [comment]
Update: Implement the same behaviour for inserting lines with "Add new"

**Comment by metas-rc** [comment]
Followup for copy with details: https://github.com/metasfresh/metasfresh/issues/4325

**Comment by metas-lc** [comment]
IT
repeated the testcase above
=> when you want to add a product using add new, you get the following error right when you press enter after writing product's name
Error: The product P002732 is...
Server error
The product P002732 is a prescription medicine and may not be sold to the customer Test Kunde 1. Reason: TYPE_B 
OK
=> rest works the same OK
