### ISSUE TITLE
Ban Manufacturer Products for a Businesspartner 

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4223]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is possible to ban Products to be sold or bought from/ to a Business Partner.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Allow recording the Manufacturer in the Ban list. All Products of that Manufacturer shall not be traded for the given Business partner.

**Comment by cristinamghita** [comment]
##Concept

* Create a new table M_BannedManufacturer (or other name) with fields
  * Manufacturer - String  and mandatory
  * Reason
* Have a uniques constraint per manufacturer

* Modify this method ```de.metas.purchasing.api.impl.BPartnerProductDAO.getExcludedFromSaleToCustomer(int, int)```, to check also the M_Product.Manufacturer field against the the ban list from M_BannedManufacturer .

**Comment by cristinamghita** [comment]
## Configurati
* Add new tab called Product manufacturer in Partner window
  * Here, the user can ban manufacturers for certain partner
![image](https://user-images.githubusercontent.com/15378036/41669069-934b40aa-74b9-11e8-9b80-a06a2299cd35.png)
* Add new tab called Mnufacturer, in Partner window
  * Here, the user can specify if the partner is a Manufacturer
![image](https://user-images.githubusercontent.com/15378036/41669140-c385c98e-74b9-11e8-904d-5b04a1b77ebe.png)
### Sales order with banned manufacturer
* Choose a partner that you will make it Manufacturer
* Go to product window, choose 'Convenience Salat 250g' and add manufacturer (the one from previous step)
  ![image](https://user-images.githubusercontent.com/15378036/41669256-12e529fc-74ba-11e8-95b8-d111d9730dac.png)
* Go to partner G0001 and in tab Product manufacturer, ban manufacturer from step 1
* Create a sales order for partner G0001 and try to add product convenience salad
![image](https://user-images.githubusercontent.com/15378036/41669383-5a884f96-74ba-11e8-85d4-033f3aa0775e.png)
### Sales order with a manufacturer which is not banned
* Remove the line from Product manufacturer from the previous test
* Create sales order for G0001 with product convenience salad
* The order line cand be added **OK**

**Comment by metas-lc** [comment]
IT
1. BPartner window (123 only), tab Manufacturer
=> flag: Manufacturer, isActive, client and org OK
=> there is a "main" written there - probably follow-up
=> shall it also be added in Busines Partner Pharma window ?
2. Set Manufacturer on Y for BPartner A and B
3. Thare are 2 "Product" tabs in Bpartner window
=> one containing manufacturer and description: this is for banning all products which are manufactured by bpartner you set
=> you can add 2 same bans NOK you get error when you create order
```
"QueryMoreThanOneRecordsFound (TypedSqlQuery{tableName=M_BannedManufacturer, whereClause=(AD_Client_ID=?) AND (IsActive=?) AND (C_BPartner_ID = ?) AND (Manufacturer_ID = ?), parameters=[1000000, true, 2156425, 2156427]})"
```
=> old one contains exclusion reasons
OK
=> needs trl - follow-up
4. Product window (both 140 and 540410)
=> manufacturer field is there, you can set it 
=> only those bpartners that are manufacturers are visible
OK
5. make sure you have 2 manufacturer BPartners: A and B
6. make sure you have product X manufactured by A and Y manufactured by B
7. go to BPartner A and ban products from BPartner B (p. Y)
8. go to BPartner B and ban products from BPartner B (p. Y)
9. create a sales order for BPartner A, add product X and Y
=> X was added correctly, no errors OK
=> Y was not added: 
Error: Product not allowed to...
Server error
Product not allowed to be sold to customer Test Kunde 1 because test. 
(test = the description i set in product tab from bp window)
10. create a sales order for BPartner B, add product X and Y
=> X was added correctly, no errors OK
=> Y was not added - same error with description from bpartner B product ban OK
11. add orderline with a product that doesn't have any manufacturer
=> line is added, no errors OK
12. make an order with Bpartner C (one without ban), add product Y 
=> line added without errors OK
13. repeat the same testcase for purchase side
=> works the same OK
.
Regression:
1. Go to Bpartner A, to to the other product tab and add 1 product, C. Exclude it from sales documents
2. create a sales and purchase order for that bpartner A with that product C
=> you can't add it, you get the message you set at step 1 OK
3. for the same product C, add manufacturer bpartner B and try again (it's like double ban)
=> you get the error from the ban OK

. 
task for trl NOKs: https://github.com/metasfresh/metasfresh/issues/4283
unique index - probably to be solved here

**Comment by metas-lc** [comment]
IT
checked again:  you cannot add 2 same bans anymore OK
(step 3)
