### ISSUE TITLE
Add UC constraints to C_Aggregation

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4237]
### Is this a bug or feature request?
FR
### What is the current behavior?
The system doesn'T prevent you to flag as many C_Aggregation records as "default" as you want.
But if you do, you run into trouble which can e.g. prevent not only invoicing, but also material receipts.

### What is the expected or desired behavior?

System shall not allow more than one defaul record per 
* table
* level
* SO/PO

**Comment by metas-lc** [comment]
IT
1. go to aggregation window
2. try to make one default (all have the same table_id, level and 1 is already default)
=> document is not saved because "There may be just one purchase record per level and table" OK
3. create a new one for the same table, different level, and make it default
=> you can OK
4. now try to set the same level 
=> you can't. Document not saved OK
5. create a new one for another table, make it default
=> you can OK
