### ISSUE TITLE
Invoice Document Outbound eMail enqueing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4285]
### Is this a bug or feature request?
Feature Request/ Bug Fix
### What is the current behavior?
Invoice Doc Outbound >> Action Send eMails to BPartner enqueueing is done by this rules:
- email is not null from c_docoutbound.ad_user_id (bug: its NULL on my cases)
- email is not null of ad_user of partner who has isdefault =Y

Problem:
- billto_user in the invoice is not the same as the default user of the partner.
- Because the default user does not have an email address the email is not enqueued

#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
- Fix the enqueueing.
- Add a Field for Contact User (Invoice = billto_user, order = user_id) and the corresponding email address.
--> This way the user can see in advance if emails can be sent.

**Comment by metas-ts** [comment]
the `de.metas.async.C_QueueC_WorkPackages_Created_1` de_CH AD_Message has a syntax error; this SQL fixes it, pls add it:

```sql
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
UPDATE AD_Message_Trl SET UpdatedBy=100,Updated=TO_TIMESTAMP('2018-07-04 16:14:00','YYYY-MM-DD HH24:MI:SS'),IsTranslated='Y',MsgText='Es wurden {0} asynchrone Arbeitspakete erstellt' WHERE AD_Message_ID=544429 AND AD_Language='de_CH'
;
```

**Comment by metas-ts** [comment]
### Results

#### Added new columns for the email recipient user; and mailaddress

* The respective fields are editable
* When the new `C_Doc_Outbound_Log` is created, the system tries to determin the user an mail address as follows:
  * if the `C_Doc_Outbound_Log` references a `C_Invoice`: 
    * first try C_Invoice.AD_User_ID and if that is not set (or has no EmailAddress)
    * then try the invoice's billTo-User (or default user)
  * otherwise, the system looks for a `AD_Mail_Config` and tries to get the value from the the respective column of the references object

#### Changed the logic for `C_Doc_Outbound_Log.IsInvoiceEmailEnabled`

I didn't fully understand the old logic and what i understood didn't seem to make 100% sense (and seemed a bit contradictory too).

* Now, if a `C_Doc_Outbound_Log` doesn't reference a `C_Invoice`, then the flag is always `N`
* If it references a `C_Invoice` then the flag is taken from C_BPartner, or it it's unset, from the mail recipient-AD_User..if it's also unset there, then 'N' is assumed.

Note that if the C_BPartner has IsInvoiceEmailEnabled='Y' and the system can't find an email recipient, this situation can now be seen by filtering on `C_Doc_Outbound_Log`s

**Comment by metas-dh** [comment]
will test when #4336 is rolled out as well.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. new columns for the email recipient user; and mailaddress in Outbound Doc window: **OK**
2. new columns are editable: **OK**
3. when the new `C_Doc_Outbound_Log` is created, the system tries to determine the user a mail address as follows:
  * if the `C_Doc_Outbound_Log` references a `C_Invoice`: 
      * first try C_Invoice.AD_User_ID: **OK** , and if that is not set (or has no EmailAddress)
      * then try the **bpartner's** billTo-User (or default user): 
  => no user was set in invoice, but a billTo-User with email address was set in bpartner (no user had IsInvoiceEmailEnabled:Y): no email address / email recipient was set in `C_Doc_Outbound_Log`: NOK i think
  => user wihout email address was set in invoice, but a billTo-User with email address was set in bpartner (billTo-User had IsInvoiceEmailEnabled:Y): no email address / email recipient was set in `C_Doc_Outbound_Log`: NOK i think
  * otherwise, the system looks for a `AD_Mail_Config` and tries to get the value from the respective column of the referenced object: **OK** (tested with billTo-User set in `AD_Mail_Config` , for sales order)

4. if a `C_Doc_Outbound_Log` doesn't reference a `C_Invoice`, then the flag `C_Doc_Outbound_.IsInvoiceEmailEnabled` is always `N`: **NOK**

![2018-07-18 14_44_42-metasfresh](https://user-images.githubusercontent.com/18696715/42882521-68bfe03e-8a99-11e8-9e88-0f0ea7a4d29d.png)


=> that testcase had the email address & receipient taken from `AD_Mail_Config`; `C_Doc_Outbound_.IsInvoiceEmailEnabled` was not displayed in the single view!


5. If it references a `C_Invoice` then 
  * the flag is taken from C_BPartner: **OK**
  * or if it's unset, from the mail recipient-AD_User: **OK**, (also if that AD_User has no email address, is that OK? => OK, user can add the email address, but needs to see if the bpartner wants an email for the invoice)
  * if it's also unset there, then 'N' is assumed: **OK**

Note that if the C_BPartner has IsInvoiceEmailEnabled='Y' and the system can't find an email recipient, this situation can now be seen by filtering on `C_Doc_Outbound_Log`s => see IT for #4336

**Comment by metas-ts** [comment]
hi @metas-dh  
about 3.: the code I used to look up the bill contact was a bit problemtic and the way i used it as weel.
..I was unable to reproduce the error, but i believe i fixed it now by re-implementing that code.

about 4.: did you undestand "doesn't"? iit should be clear, but in case it's not: i said "does" :blush: .
Anyways, i think it doesn't hurt this way neither..wdyt?

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

3. when the new `C_Doc_Outbound_Log` is created, the system tries to determine the user a mail address as follows:
  * if the `C_Doc_Outbound_Log` references a `C_Invoice`: 
      * C_Invoice.AD_User_ID is not set, but a billTo-User with email address was set in bpartner (no user had IsInvoiceEmailEnabled:Y): the billTo-User's email address was set in `C_Doc_Outbound_Log`, and this user as email recipient: **OK**
      * C_Invoice.AD_User_ID without email address is set, but a billTo-User with email address was set in bpartner: the billTo-User's email address was set in `C_Doc_Outbound_Log`, and this user as email recipient: **OK**
 => works the same is if there is no billTo-User with email address, but a default user with email address: **OK**

hi @metas-ts :
4. `C_Doc_Outbound_.IsInvoiceEmailEnabled`:
* had a sales invoice A, with C_Invoice.AD_User_ID set, that user had `IsInvoiceEmailEnabled`: `N` (as had bpartner as well), => sales inovice in `C_Doc_Outbound_.IsInvoiceEmailEnabled` also `N`: **OK**
* set `IsInvoiceEmailEnabled`: `Y` for this user in bpartner window, and created a new sales invoice B, with this user as C_Invoice.AD_User_ID:
    * sales invoice A now has `C_Doc_Outbound_.IsInvoiceEmailEnabled`: `Y`
    * sales invoice B has `C_Doc_Outbound_.IsInvoiceEmailEnabled`: `N`: **why?** would have expected `C_Doc_Outbound_.IsInvoiceEmailEnabled`: `Y` either for both invoices or for invoice B

**Comment by metas-ts** [comment]
:cherries: picked commit https://github.com/metasfresh/metasfresh/commit/7375b6b0541766cc8c296510c70e6a71be1a53e1 to `release`

**Comment by metas-ts** [comment]
@metasnw sorry to drag you in, but i hope that a quick talk with me about 
`C_Doc_Outbound.IsInvoiceEmailEnabled` can speed up things.
background: right now the BL is a bit inconsistent and it would be good to decide how it should be

**Comment by metas-dh** [comment]
Update:
checked with metas-nw: 
* `C_Doc_Outbound.IsInvoiceEmailEnabled`: taken out for user, only in bpartner window
* `C_Doc_Outbound.IsInvoiceEmailEnabled` in bpartner: when set there, it is displayed in DocOutbound as well: OK
=> open question from 4. not relevant anymore
