### ISSUE TITLE
metasfresh-app server startup stalls if no activeMQ broker is available

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4314]
### Is this a bug or feature request?
Bug
### What is the current behavior?

main trhread never finished, subsequent invokaction to Adempiere.getBean() wait forever

#### Which are the steps to reproduce?

* `update ad_Sysconfig set value='N' where name = 'de.metas.jms.UseEmbeddedBroker'`
* have no external broker

**Comment by metas-rc** [comment]
Results of IT

* Tested locally

Note:  I know how the problem was because I also had it some days ago so I am doing the same things that let to this problem back then.

* get all up to date on master
* stop eclipse and start it clean ( just to be sure there are no leftovers)
* start the server root and the webui api
* open webui on local

Actual test case: 
* Create a sales order
* Check if a shipment schedule was created for it. => OK It was created
* OK: I was able to also create a shipment out of it.


 => the problem is no more.
