### ISSUE TITLE
consolidate profit related columns in order line and purchase candidate

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4380]
### Is this a bug or feature request?
FR / Bug

### What is the current behavior?
naming and meaning of profit related columns and fields in the BL 
are not clear, and they are cont consistently shown for order line and purchase candidate

Current terminology:
* `C_OrderLine`
  * `PriceGrossProfit` (Rohertragspreis - Endpreis pro Einheit nach Abzug des erwarteten Rohertrages (Skonto, Rückvergütung usw).)
  * `PercentProfit` (Marge %)
* `C_PurchaseCandidate`
  * `PriceGrossProfit`
    * set from `profitInfo.getPurchaseNetPrice`
  * `CustomerPriceGrossProfit` (VK Netto - Effektiver Verkaufspreis minus Skonto und Rückerstattung)
    * set from ProfitInfo.getSalesNetPrice
	  * set from `OrderLineWithGrossProfitPriceRepository.getProfitMinBasePrice`
	    * coming from `C_OrderLine.PriceGrossProfit`
  * `PurchasePriceActual` (EK Netto - Effektiver Einkaufspreis)
    * set from `profitInfo.getPurchaseGrossPrice`

**Comment by metas-ts** [comment]
Suggesion:
* generally prefix with "Profit" 
* try to make the names meaningful
  
PercentProfit => ProfitPercent
PriceGrossProfit => ProfitPriceActual
CustomerPriceGrossProfit => ProfitSalesPriceActual
PurchasePriceActual => ProfitPurchasePriceActual

**Comment by metas-lc** [comment]
Got NPE when tried to open pricing conditions. Order's bpartner had no discount schema. Other bpartner had. 
<details/>
"org.adempiere.exceptions.AdempiereException: NullPointerException: java.lang.NullPointerException"
1
:
"	at org.adempiere.exceptions.AdempiereException.wrapIfNeeded(AdempiereException.java:89)"
2
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:264)"
3
:
"	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:259)"
4
:
"	at sun.reflect.GeneratedMethodAccessor589.invoke(Unknown Source)"
5
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
6
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
7
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
8
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
9
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
10
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
11
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
12
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
13
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
14
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
15
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
16
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
17
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
18
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
19
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
20
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
21
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
22
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
23
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
24
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
25
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
26
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
27
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
28
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
29
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
30
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
31
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
32
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
33
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
34
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
35
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
36
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
37
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
38
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
39
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
40
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
41
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
42
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
43
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
44
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
45
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
46
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
47
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
48
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
49
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
50
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
51
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
52
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
53
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
54
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
55
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
56
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
57
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
58
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
59
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
60
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
61
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
62
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
63
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
64
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
65
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
66
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
67
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
68
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
69
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
70
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
71
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
72
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
73
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
74
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
75
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
76
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
77
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
78
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
79
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
80
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
81
:
"	at java.lang.Thread.run(Thread.java:748)"
82
:
"Caused by: java.lang.NullPointerException"
83
:
"	at de.metas.ui.web.order.sales.pricingConditions.view.PricingConditionsRow.<init>(PricingConditionsRow.java:251)"
84
:
"	at de.metas.ui.web.order.sales.pricingConditions.view.PricingConditionsRow.<init>(PricingConditionsRow.java:66)"
85
:
"	at de.metas.ui.web.order.sales.pricingConditions.view.PricingConditionsRow$PricingConditionsRowBuilder.build(PricingConditionsRow.java:203)"
86
:
"	at de.metas.ui.web.order.sales.pricingConditions.view.PricingConditionsRowsLoader.createPricingConditionsRow(PricingConditionsRowsLoader.java:219)"
87
:
"	at de.metas.ui.web.order.sales.pricingConditions.view.PricingConditionsRowsLoader.lambda$createPricingConditionsRows$4(PricingConditionsRowsLoader.java:201)"
88
:
"	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)"
89
:
"	at java.util.Iterator.forEachRemaining(Iterator.java:116)"
90
:
"	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)"
91
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
92
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
93
:
"	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)"
94
:
"	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)"
95
:
"	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
96
:
"	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)"
97
:
"	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)"
98
:
"	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)"
99
:
"	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)"
</details>

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh-webui-api/commit/b43c3bc9bcdbf262a42875dee3b8c2382e2b9b7d to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

SetUp:
* bpartner vendor & customer, with discount schema for each:
* prices for TestProduct: Sales: 2.00, Purchase: 1.00

Test:
1. sales order for customer, TestProduct, qty: 100:
* new fields in orderline: Ertrag netto & Marge %: **OK**
* price, net price, discount, Ertrag netto set: **OK**
* Marge %: empty: **OK**
2. create purchase candidate for the vendor, qty: 10:
* new fields in purchase cand modal overlay: Sales net, Purchase net, Margin %: **OK**
* Sales net, Purchase net, Margin % all empty: **OK** bc first test, no purchase cand yet??
3. create the purchase order in purchase candidate window
4. check the sales order again:
* Marge %: update to 0,00 %: **NOK**
5. create another purchase candidate for the vendor:
* Sales net, Purchase net, Margin % still all empty: **NOK**

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

problem was indeed too little qty in purchase candidate: 
3. in modal overlay for purchase candidate, set qty > or = qty from pricing condition for vendor
   * Sales net, Purchase net, Margin % are all updated: **OK**
   * Sales net: "Effektiver Preis pro Einheit, minus erwartetem Skonto und vertraglicher Rückerstattung": in my case: price eff.: 2,00 / Skonto: 10%  / 10% discount for qty:100 from pricing condition => 1,62: **OK**
   * Purchase net: "Effektiver Verkaufspreis pro Einheit, minus erwartetem Skonto und vertraglicher Rückerstattung": price eff.: 1,00 / Skonto: 5% / 10% discount for qty:50 from pricing condition => 0,86: **OK**
   * Margin %: 88.5%:  => % from (sales net - purchase net) in relation to purchase net, rounded to 0,5 => @metas-mk is that OK?
4. Margin % in sales order also updated accordingly: **OK**
