### ISSUE TITLE
Fix zoom PrintingQueue=>PrintJob and others

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4400]
### Is this a bug or feature request?
FR
### What is the current behavior?

We have the column `AD_Column.AllowZoomTo` which works for the swingUI, but not the webui.

E.g. the AD_Column of `C_PrintJobDetail.C_Printing_Queue_ID` has it set to `Y`, and this allows to 
zoom from the `C_Printing_Queue` window to the C_PrintJob window (which has a `C_PrintJobDetail` tab).
But that only work woth the SwingUI and it kindof spaghetti.

Besides `C_PrintJobDetail.C_Printing_Queue_ID`, only 19 other columns have it set to `Y`.
And it's sortof complicated to implement it again in a clean way.
So, instead of that, please

* kick out the `AD_Column.AllowZoomTo` column and respective code
* check out those 20 columns and decide which ones currently need a zoom..`C_Printing_Queue => C_PrintJobDetail`, but about the others I'm not sure..
* create AD_RelationTypes for those that are needed.

#### Which are the steps to reproduce?

try to zoom from `C_Printing_Queue` to `C_PrintJob` => doesn't work

### What is the expected or desired behavior?

should work :-)

**Comment by metas-rc** [comment]
Test


TABLENAME | COLUMNNAME | WINDOW | TAB
-- | -- | -- | --
C_Doc_Responsible | Record_ID | Belegansprechpartner | Belegansprechpartner
DIM_Dimension_Spec | Name | Dimension | Dimensionsspezifikation
C_PaySelectionLine | C_Invoice_ID | Zahlung anweisen | Rechnung auswählen
C_Print_Job_Line | C_Printing_Queue_ID | Druck-Jobs | Job-Zeilen
C_Flatrate_Term | C_OrderLine_Term_ID | Laufender Vertrag | Vertragsperiode
C_Flatrate_Term | C_OrderLine_Term_ID | Vertrag | Vertrag
C_Flatrate_Term | C_OrderLine_Term_ID | Geschäftspartner Dist-Orgs | Abos
PP_Product_Planning | M_Product_ID | Produkt Plandaten | Daten Planung
M_HU_Trx_Line | M_HU_ID | HU Transaktion | HU-Transaktionszeile
AD_SchedulerLog | AD_PInstance_ID | Ablaufsteuerung | Protokoll
MD_Candidate | MD_Candidate_Parent_ID | Material Disposition | Materialdispo
M_ProductPrice | M_PriceList_Version_ID | Produkt Pharma | Preis
M_ProductPrice | M_PriceList_Version_ID | Aufwandsart | Preis
M_ProductPrice | M_PriceList_Version_ID | Ressource | Preis
M_ProductPrice | M_PriceList_Version_ID | Produkt | Preis
M_ProductPrice | M_PriceList_Version_ID | Preise | Produkt-Preis
M_ProductPrice | M_PriceList_Version_ID | Produkt Preise | Produkt Preis
MD_Candidate_Dist_Detail | DD_Order_ID | Material Disposition | Bereitstellungsdetail
C_Order_MFGWarehouse_Report | C_Order_ID | Bestellkontrolle | Bestellkontrolle
MD_Candidate_Prod_Detail | PP_Order_ID | Material Disposition | Produktionsdetail
MD_Candidate_Demand_Detail | C_OrderLine_ID | Material Disposition | Bedarfsdetail
MSV3_VerfuegbarkeitsanfrageEinzelne_Artikel | C_OrderLineSO_ID | MSV3 Verfuegbarkeitsanfrage Einzelne | Artikel
MSV3_VerfuegbarkeitsanfrageEinzelne_Artikel | C_PurchaseCandidate_ID | MSV3 Verfuegbarkeitsanfrage Einzelne | Artikel
MSV3_BestellungAntwortPosition | C_PurchaseCandidate_ID | MSV3 Bestellung Antwort | BestellungAntwortPosition
MSV3_BestellungPosition | C_PurchaseCandidate_ID | MSV3 Bestellung | BestellungPosition
MSV3_BestellungAntwortAuftrag | C_OrderPO_ID | MSV3 Bestellung Antwort | BestellungAntwortAuftrag
MSV3_BestellungAnteil | C_OrderLinePO_ID | MSV3 Bestellung Antwort | BestellungAnteil

**Comment by metas-rc** [comment]
Note: The example from the requirements has a typo. It's not about C_PrintJobDetail.C_Printing_Queue_ID but about C_Print_Job_Line.C_Printing_Queue_ID

**Comment by metas-rc** [comment]
Notes for IT:


Test


1) C_Doc_Responsible (Belegansprechpartner) 
If a C_Doc_Responsible entry has a document (e.g. Invoice)  as table-record, you should be able to reach the linked Belegansprechpartner from that C_Order

2) DIM_Dimension_Spec -> Name -> Dimension -> Dimensionsspezifikation - not done. It's too complex because it's based on the Name column. To be implemented if it's really needed.

3) C_Invoice -> C_Payselection: both sales and purchase
* implemented	
	
4) C_Printing_Queue	C_Printing_Queue_ID	C_Print_Job_Line
* implemented

5) C_Order -> C_OrderLine -> C_OrderLine_Term -> C_OrderLine_Term_ID -> C_Flatrate_Term (sales side, I think we don't have flatrate terms for purchase)
* No new relation type needed. This link is covered by the old C_Order -> C_Flatrate_Term relation type that we already have 
* I tested it and it works.

6) M_Product -> PP_Product_Planning shall be covered by an existing relation type (had problems on local but on mf15 I saw it works)

7) M_HU -> M_HU_Transaction 
* implemented

8) AD_PInstance -> AD_SchedulerLog ( on sys admin only)
* implemented

9) MD_Candidate_Parent	MD_Candidate_Parent_ID	MD_Candidate -------------------------------------------------------------------------------------------------
* Implemented, but doesn't work on local. Maybe because it points to the same table/window (?)

10) PriceList -> PriceListVersion -> Product Price 
* Existing. Please, retest

11) DD_Order	DD_Order_ID	MD_Candidate_Dist_Detail 
*implemented


12)  C_Order	C_Order_ID	C_Order_MFGWarehouse_Report 
* Existing . Please, retest

13) PP_Order	PP_Order_ID	MD_Candidate_Prod_Detail
* implemented


14) C_OrderLine	C_OrderLine_ID	MD_Candidate_Demand_Detail
* this should be covered by the relation type C_OrderSO -> MD_Candidate_all


15) C_OrderLineSO	C_OrderLineSO_ID	MSV3_VerfuegbarkeitsanfrageEinzelne_Artikel
* implemented



16) C_PurchaseCandidate	C_PurchaseCandidate_ID	MSV3_VerfuegbarkeitsanfrageEinzelne_Artikel
* implemented. 




17) C_PurchaseCandidate	C_PurchaseCandidate_ID	MSV3_BestellungAntwortPosition
* implemented



18)C_PurchaseCandidate	C_PurchaseCandidate_ID	MSV3_BestellungPosition
* implemented



19)C_OrderPO	C_OrderPO_ID	MSV3_BestellungAntwortAuftrag
* implemented



20)C_OrderLinePO	C_OrderLinePO_ID	MSV3_BestellungAnteil
* implemented

**Comment by metas-lc** [comment]
IT see 3?, 11, 14, 15?, 

1. create a new invoice (sales or purchase), complete. Check related documents
=> link to Belegansprechpartner OK
2. select Belegansprechpartner 
=> the corresponding C_Doc_Responsible (Belegansprechpartner) opens OK
.
3. DIM_Dimension_Spec - is it needed? shall i create a new task?
.
4. create a new sales/ purchase invoice. Create new payment selection for the bpartner (use create from action, don't check anything, use alle, and make sure you use correct currency). Check the invoices
=> both sales and purchase invoices have Payment Selection as ref. documents OK
=> if you select Payment Selection, the corresponding one opens OK
.
5. find a printing queue for an etikett. Go to Related Documents (or create a receipt)
=> there is a link to Druck-Jobs OK
6. open Druck-Jobs
=> the according print job opens OK
.
7. created a sales order with an abo that extends the contract 3 times
=> 3 new contracts created OK
8. in sales order go to Related Documents 
=> link to the 3 contracts is there OK
9. open the link
=> corresponding contracts open OK
.
10. go to product planning, pick a product and add a line (data planning)
11. go to product window, select the same product, go to Related Documents 
=> no link to corresponding product planning NOK
(on swing is nothing in zoom into)
.
12. go to Handling Units Editor, go to Related Documents 
=> link to HU Transactions OK
=> HU Transactions for corresponding HU opens OK
.
13. login as sysadmin, open PInstance (Prozess Revision), select one, go to Related Documents 
14. select Ablaufsteuerung (SchedulerLog)
=> error NOK
Error: ERROR: invalid reference to...
Server error 

<details/>
ERROR: invalid reference to FROM-clause entry for table "ad_schedulerlog" Hint: Perhaps you meant to reference the table alias "sl". Position: 623 SQL: INSERT INTO T_WEBUI_ViewSelection ( UUID, Line, IntKey1) SELECT ? , row_number() OVER (ORDER BY (Name) ASC NULLS LAST, (AD_Scheduler_ID) ASC NULLS LAST) , AD_Scheduler_ID FROM AD_Scheduler master WHERE 1=1 AND /* security-client */ master.AD_Client_ID=0 /* security-org */ AND master.AD_Org_ID=0 /* security-record */ AND master.AD_Scheduler_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 688 AND AD_User_ID <> 100 AND IsActive = 'Y' ) AND ( /* filters */ ( /* MQuery-b962a843-5722-45b2-9120-7f18edfd7e9d */((exists (select 1 from AD_SchedulerLog sl where sl.AD_SchedulerLog_ID = AD_SchedulerLog.AD_SchedulerLog_ID and sl.AD_PInstance_ID = 1000513)))) ) LIMIT ? SQL params: [305-BM, 2000]
</details>

.
15. open Material Schedule, open one that is parent for other Material Schedule, go to Related Documents 
=> nothing appears. Needed? 
.
16. open Price List window, go to Price List Version tab, right click: select Product Prices
=> Product Prices window opens with corresponding prices OK
.
17. create/complete a new distribution order,  go to Related Documents 
=> link to material schedule, opens correctly OK
.
18. create/complete a new sales order,  go to Related Documents , open Order Control
(there are sysconfigs to enable ordercheckup)
=> link to Order Control, opens correctly OK
.
19. Manufacturing order -> Material schedule
create/complete a new Manufacturing order. Go to Related Documents 
=> link to Material schedules.  Opens correctly OK
.
20.

**Comment by metas-rc** [comment]
2 and 9 are not needed, as I discussed with metas-ts.

**Comment by metas-rc** [comment]
6 done

**Comment by metas-rc** [comment]
8 done

**Comment by metas-rc** [comment]
15 done

**Comment by metas-lc** [comment]
IT
6. M_Product -> PP_Product_Planning
=> works OK
(the relations also appear now in swing)

8. AD_PInstance -> AD_SchedulerLog
=> opens correctly, no errors OK

15. C_OrderLineSO C_OrderLineSO_ID MSV3_VerfuegbarkeitsanfrageEinzelne_Artikel
=> works OK
