### ISSUE TITLE
New Dunning trigger for flatrate terms

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4411]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the dunning candidates are calculated based on due-date and settings in dunning Type.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
A new dunning trigger is needed that allows to create dunning candidates based on
- Invoices without lines with flatrate terms: Due Date as usual
- Invoices with flatrate terms and new contract (1st contract period): Due Date as usual
- Invoices with flatrate terms and contract from 2nd contract period): Due Date is the start date of the new contract period
- Invoices with flatrate terms and contract prolongation: Due Date is the start date of the new contract period
  - unless we have **https://github.com/metasfresh/metasfresh/issues/4547** some users might feel that   we have no such thing as "contract prolongation"
    - note: we do have a process to extend a contract,, i.e. create another "single" C_Flatrateterm and link it to its predecessor. In this case, the due date ist set as required.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Set Up:
* payment schedule for bpartner: immediately
* dunning type: step 1: 0 days after due date
* normal sales order A without flatrate term
* sales order B with flatrate term (1 contract period)
* sales order C with flatrate term (3 contract periods, term duration for 3 days each)

Test:
1. Invoices without lines with flatrate terms: Due Date as usual:
* normal sales invoice A: Due Date: date of invoice: **OK**

2. Invoices with flatrate terms and new contract (1st contract period): Due Date as usual:
* sales invoice B: Due Date: date of invoice: **OK**
* sales invoice C, 1st period: Due Date: date of invoice: **OK**

3. Invoices with flatrate terms and contract (from 2nd contract period): Due Date is the start date of the new contract period:
* sales invoice C, 2nd period: Due Date: start date of 2nd period: **OK**
* sales invoice C, 3rd period: Due Date: start date of 3rd period: **OK**

4. Invoices with flatrate terms and contract prolongation: Due Date is the start date of the new contract period
* extend flatrate term manually
* sales invoice B & C, new period: Due Date: start date of new period: **OK**

5. Create dunning candidates:
* after updating manually (problem with exception was fixed by metas-ts): candidates created 1 day after due date (=> dunning grace): **OK**

ToDo:
* check the process for updating / creating dunning cands for the future invoices of contract periods 2 & 3
* check #4554 (dunning doc shall include original invoice, see customer task)

**Comment by metas-dh** [comment]
checked dunning candidates after process was running the night before:
* no dunning cand was created for the invoice where the due date was reached: NOK
* ran process to update / create dunning cands manually: dunning cand for the resp. invoice was created: OK

**Comment by metas-dh** [comment]
created sales invoice that shall be dunned tomorrow => ToDo: check tomorrow if process for creating dunning cands ran properly over night

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* process ran as set: OK
* dunning candidates created, with due  date & dunning date set correctly: OK
