### ISSUE TITLE
Material Receipt Dispo Adjustment

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4419]
### Is this a bug or feature request?
FR

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

from customer issue:

1. Ersteller der Bestellung in Grid View: got that in Swing ("Aussendienst"?), but not in WebUI, will that be added?
2. Nach Wareneingang "Einlagerung" Aktion autom. Lagerort als zusatz Parm.: 
* Lagerort is selectable in the Einlagerung action: OK
* Lagerort is shown for the resp. HU in HU Editor, after receipt: OK i think? 
3. Pflichtfeld Charge/ Verfallsdatum: "Verfall" is an attribute in the HU Editor, in material receipt cands, but read-only?
4. Aus Verfallsdatum auf Prüfung und setzen von VERFALL Attribut: need to test this further
5. Einbau in Fenster Bestellung Grid View: Ersteller, Zugesagten Liefertermin, Anzahl Positionen: the first 2 are included in Swing, but not the 3rd one; none of them are shown in WebUI

**Comment by metas-ts** [comment]
assigned to @metas-mk because afaiu both issues are going to be solved by him in #4490

**Comment by metas-dh** [comment]
Update:

3. Pflichtfeld Charge/ Verfallsdatum: received the resp. migration script to test that from metas-ts:
* Lot and Mindesthaltbarkeitsdatum are mandatory in material receipt dispo: OK
* no action for creating material receipt available before both attributes are set: OK
* when both attributes are set, material receipt (only with "Einlagerung"!) becomes available: OK

=> the remaining NOKs will be fixed in #4490
