### ISSUE TITLE
Implement support for MSV3 version 1

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4511]

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db 

see testcase in https://github.com/metasfresh/me03/issues/295

1. connection test, with Version 1 set in vendor configuration: OK
2. connection test, with Version 2 set in vendor configuration: error as in testcase, afais that's ok since the server is set up with Version 1: OK
3. checked Bestelldispo overlay for a sales order:
* vendor from the vendor config was available for creating Bestelldispos: OK
* available qties?
