### ISSUE TITLE
Implement inbound E-Mail support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4524]

**Comment by metasnw** [comment]
IT

## Scope of first iteraion

- OK: Setup inbound Email Server
- OK: c_mail is created for inbound email => window Email
- OK: email is lined to ad_user 
- OK: request was created
- OK: reference from request to Email was created
- NOK: request is not linked to the c_bpartner althout the To: ad_user is linked to a partner

**Comment by metasnw** [comment]
new IT:

## IT - Scope of first Iteration

- OK: Setup inbound Email Server
- OK: c_mail is created for inbound email => window Email
- OK: email is linked to ad_user 
- OK: request was created
- OK: reference from request to Email was created
- OK: request is not linked to the c_bpartner although the To: ad_user is linked to a partner
- OK: I could not find the original e-mail as file 
- NOK: File Attachments are not stored in metasfresh


### Issues found beyond scope. Just here for reference

- Outgoing E-Mails do not create a request
- Outgoing E-Mails do not store email in the new table c_mail
- Single E-Mails like from order do use user email settings but to have it harmonized it would be important to use the email outbound settings in order to configure the mailbox on document type level. e.g. send email from sales order via personal e-mail but the ones from invoice window using invoicing@company.com
- user can not answer to e-mails from request window

**Comment by metasnw** [comment]
IT on 5.92.1-14034+master
* OK: Request Date is not set. That one is critical because nobody will find the email ever.
