### ISSUE TITLE
Show Product note as tooltip in order line

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4556]
### Is this a bug or feature request?
FR
Note: this issue can be ITed when https://github.com/metasfresh/metasfresh-webui-frontend/issues/1952 is ready

### What is the expected or desired behavior?

If `M_Product.DocumentNote` ("Notiz / Zeilentext") is set for a given product and that product in a sales or purchase order line,
then the note shall be accessible as a tool tip.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Show Product note as tooltip in order line:

* small document icon in product field in orderline (after double clicking the product!): **OK**
* clicking on document icon opens text in a small box, with scroll bar in case of longer text: **OK**
* text from `M_Product.DocumentNote` ("Notiz / Zeilentext") is fully displayed, no cut-offs (tested with ~1.900 characters), not too small to read: **OK**
* document icon only displayed after double clicking the product: imho that's counter intuitive to the one in bpartner fields, since those are displayed right away, without having to double click: how does the user know there is more info available for product?  **NOK** imho

**Comment by metas-ts** [comment]
> document icon only displayed after double clicking the product: 

@metas-dh I just quick-checked, this works now

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

Show Product note as tooltip in order line:

* small document icon in product field in orderline, **directly** displayed, not just after double clicking the product: OK
* clicking on document icon opens text in a small box, with scroll bar in case of longer text: OK
* text from M_Product.DocumentNote ("Notiz / Zeilentext") is fully displayed, no cut-offs, not too small to read: OK
