### ISSUE TITLE
Reference to HU Attributes instead of identical copies

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#460]
Reference to HU Attributes instead of identical copies.
Idea here is even to abstain from HU Attributes on Virtual PI, TU Level already has pure content (same product, same attributes, same packing instructions).
This would direclt fit to the new representation logic for the user and will reduce the amount of data transactions and records up to hundreds per LU. This should be a great performance gain.

**Comment by metas-ts** [comment]
Inserting the concept written by @teosarca here:

# Draft concept (version 2)

The idea to optimize the number of records created when we receive identical HUs is to keep the information as compressed as possible.
(i.e. don't create 10000TUs when they are not needed because under a certain point, user don't care about that information or is not relevant or is not needed).

To better understand the idea, let's take following example.
We are receving 2LUs of 40TUs each. An TU will contain 10Kg of Tomatoes. We consider having 12 attributes.

In the example below there are 2 parts: the "compresed part" and the "exploded items".
Initially we will create one LU with the "compressed part" and having the "exploded items" part missing because we are not exploding now.
We will exploded only when needed and if needed.

Now take a look at the "exploded part". That's basically how our LUs are looking now, before this change.
The "exploded part" can cohexist with the "compressed part".
If we will explode something from compressed part, we will subtract the Qty and the packing materials from our compressed special VHU and we will create new LU_Item node(s) with the exploded TUs.


```
LU
	LU_Attribute x 12
	
	//
	// Compressed part (the bag)
	//
	
	LU_Item
		VHU(Special VHU!)
			VHU_Attribute x 0 <-shall not be needed
			VHU_Item (Material)
				VHU_Item_Storage: Product=Tomatoes, Qty=2x40x10Kg
			VHU_Item(Packing): Qty=2, M_HU_PI_Item.M_HU_PackingMaterial_ID=Palet
			VHU_Item(Packing): Qty=2x40, M_HU_PI_Item.M_HU_PackingMaterial_ID=IFCO

	//
	// Exploded items: 40 TUs (NOTE: we can explode maximum, one LU, that's why we don't have here 80 TUs)
	//
	
	LU_Item <-included TUs
		TU x 40
			TU_Attribute x 12
			TU_Item
				VHU
					VHU_Attribute x 12
					VHU_Item
						VHU_Item_Storage: Product=Tomatoes, Qty=10Kg
			TU_Item(Packing): Qty=1, M_HU_PI_Item.M_HU_PackingMaterial_ID=IFCO
	
	LU_Item(Packing): Qty=1, M_HU_PI_Item.M_HU_PackingMaterial_ID=Palet
```	
## Related issues:
* M_ReceiptSchedule_Alloc links to LU_ID, TU_ID and VHU_ID -> will be fine because we will actually link to our special VHU_ID
* M_ShipmentSchedule_QtyPicked also links to LU/TU/VHU -> will be fine for same reason; more, in most of the cases, i think at this point we will deal with exploded HUs anyways

* HUPackingMaterialsCollector.addOrRemoveHU shall be able to count the TUs. Atm this information is not stored in "compressed part" and +we shall store it+ somehow

* HU editor: we have to introduce a special HUKey similar with composed HUKey which will display something like 40TUsx10kg, same as the composed HUKey, but it will not be navigable (i.e. greyed out)
 


# Another functional example: receiving one LU and then issuing one TU from it to manufacturing

```
LU=1234
	VHU1
		400kg
		40xIFCO1 packings
		
		
ReceiptSchedule=400kg
	Alloc: LU=1234, TU=VHU1, VHU=VHU1 | Qty=400kg
	
InOutLine:
	M_HU_Assignment: LU=1234, TU=VHU1, VHU=VHU1 | Qty=400kg
	
	
Action Issue:
	* issue 1 IFCO from LU=1234
	
=> 
* a new M_HU is created, Value=666 of type IFCO1
* and the LU=1234 will be changed as:
	LU=1234
		VHU1
			400-10kg
			40-1xIFCO1 packings

InOutLine:
	M_HU_Assignment: LU=1234, TU=VHU1, VHU=VHU1 | Qty=400kg => stays as it is
```

**Comment by metas-ts** [comment]
# Draft concept version 3

What we try to achieve beyond v2 is to make the concept of "compressed" (a.k.a. *aggregated*) VHUs more generic. 

Usage examples: 
* HU hierarchies that don't have an LU (=>paloxe)
* HU hierarchies that are partially aggregated at the top level, but also have a few "detailed" nodes within them.

**Differences to version 2:** at the end of the day, the main differences are not so big..
* HU-Items with `type = PackingMaterial` are assigned to the respective HU if that HU is materialized, even if their Qty is > 1. if version 2, they were in the bag. I think that i's better this way, because if that packing material item would also be created within the bag, it would be more of a hassle to figure out which of the "bagged" PMs belong the already "exploded" HU(s)
* there is no distinction between "special" VHUs and ordinary ones. We/I might have to revise this when i better understand the corner cases of VHUs (so i certainly won't start by dropping that newly introduced flag), but right now, i don't see the need.

**Example 1 (taken from v2)**: a fully compressed LU that consist of two palets with 80 IFCOs and  800Kg Tomatoes

```
LU-1
	LU-1_Attributes (e.g. two SSCC18 attributes) 
	LU-1_Item(Packing): Qty=2, M_HU_PI_Item.M_HU_PackingMaterial_ID=Palet
	
	// Compressed part (the bag)
	LU-1_Item(HU)
		VHU
			VHU_Item (Material)
				VHU_Item_Storage: Product=Tomatoes, Qty=2x40x10Kg
			VHU_Item(Packing): Qty=2x40, M_HU_PI_Item.M_HU_PackingMaterial_ID=IFCO
```

Note that as we know that we are dealing with a bunch of palets that contain IFCOs, but we don't yet care which IFCO is standing on which palet.


**Example 2**: the user splits one LU off of LU-1 from example 1.<br>
```
LU-1 
	LU-1_Attributes (e.g. one SSCC18 attribute) 
	LU-1_Item(Packing): Qty=1, M_HU_PI_Item.M_HU_PackingMaterial_ID=Palet
	
	// Compressed part (the bag of LU-1)
	LU-1_Item(HU)
		VHU
			VHU_Item (Material)
				VHU_Item_Storage: Product=Tomatoes, Qty=40x10Kg
			VHU_Item(Packing): Qty=40, M_HU_PI_Item.M_HU_PackingMaterial_ID=IFCO

LU-2
	LU-2-HU_Attributes (e.g. the other SSCC18 attribute) 
	LU-2_Item(Packing): Qty=1, M_HU_PI_Item.M_HU_PackingMaterial_ID=Palet
	
	LU-2-HU_Item(HU)
		VHU
			VHU_Item (Material)
				VHU_Item_Storage: Product=Tomatoes, Qty=40x10Kg
			VHU_Item(Packing): Qty=40, M_HU_PI_Item.M_HU_PackingMaterial_ID=IFCO
```
Note that as the LU conglorate is split, also the attributes are distributed.

**Example 3**: the user splits one **TU** off of LU-1 from example 1:
```
LU-1
	LU-1_Attributes (e.g. two SSCC18 attributes)
	LU-1_Item(Packing): Qty=2, M_HU_PI_Item.M_HU_PackingMaterial_ID=Palet
	LU-1_Item(HU)
		VHU
			VHU_Item (Material)
				VHU_Item_Storage: Product=Tomatoes, Qty=(40+39)x10Kg
			VHU_Item(Packing): Qty=(40+39), M_HU_PI_Item.M_HU_PackingMaterial_ID=IFCO

TU-1
	TU-1_Attributes (no SSCC18 attribute, but others that belong to the split IFCO) 
	TU-1_Item(Packing): Qty=1, M_HU_PI_Item.M_HU_PackingMaterial_ID=IFCO
	TU-1_Item(HU)
		VHU
			VHU_Item (Material)
				VHU_Item_Storage: Product=Tomatoes, Qty=1x10Kg
```

**Example 4**: the user does *not* split off anything, but drills deeper into LU-1..for example because she needs to set a particular quantify within one of the 80 IFCOs.

```
LU-1
	LU-1_Attributes (e.g. two SSCC18 attributes) 
	LU-1_Item(Packing): Qty=2, M_HU_PI_Item.M_HU_PackingMaterial_ID=Palet
	LU-1_Item(HU)
		VHU
			VHU_Item (Material)
				VHU_Item_Storage: Product=Tomatoes, Qty=(40+39)x10Kg
			VHU_Item(Packing): Qty=(40+39), M_HU_PI_Item.M_HU_PackingMaterial_ID=IFCO

			LU_Item(HU) 
				VHU // the LU's bag with the remaining 39 IFCOs the user did not materialize
				VHU_Item (Material)
					VHU_Item_Storage: Product=Tomatoes, Qty=10Kg
				VHU_Item(Packing): Qty=39, M_HU_PI_Item.M_HU_PackingMaterial_ID=IFCO

	LU-1_Item(HU) 
		TU-HU // the one IFCO that the user did materialize. we still don't care on which of the two palets it stands
			TU_Item(Packing): Qty=1, M_HU_PI_Item.M_HU_PackingMaterial_ID=IFCO
			TU_Item(HU)
				VHU
					VHU_Item (Material)
						VHU_Item_Storage: Product=Tomatoes, Qty=9.32Kg (qty altered by the user)
```

Notes about example 4:

* we take out of the "bag" and "materialize (i.e. convert into "explicit/exploded") HUs everything we need in order to reach the point within the HU hierachy that needs to be specified.<br>In example 4, this is the quantiy of tomatoes within one particular IFCO
* the rest which we don't have to touch remains in the bag.

**Comment by metas-ts** [comment]
also cherry-picked the fix (last 3 commits, most importantly the last one) to branch `release-2016-06`

**Comment by metas-dh** [comment]
tested once more during last e2e, swing sp80:

* problems we had in the past were already addressed in this task with fixes or in new tasks
* we will create further new issues and follow ups for future HU-related problems
