### ISSUE TITLE
provide doc-outbound mail receiver for dunning docs

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4613]
### Is this a bug or feature request?

FR
Follow-up of https://github.com/metasfresh/metasfresh/issues/4593

### What is the current behavior?

the mail recipient for dunning docs in "Ausgehende Belege" is by default empty

### What is the expected or desired behavior?

* if all dunned invoices have the same invoice contact (`C_Invoice.AD_USer_ID`) and that user has a mail-address, then use that one as mail recipient.
* otherwise the mail recipient shall be filled with the bill-contact based on the dunning's bPartner and bPartner-location.
* Note that we don't have a dunning-contact field in {@code C_DunningDoc}.

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh/issues/4613 to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* if all dunned invoices have the same invoice contact (C_Invoice.AD_USer_ID) and that user has a mail-address, then use that one as mail recipient: **OK**

* otherwise the mail recipient shall be filled with the bill-contact based on the dunning's bPartner and bPartner-location: had no contact set in the resp. sales invoice, but a contact was set as sales and invoice contact in bpartner: contact was not set in dunning doc, but in C_DocOutBoundLog ("Ausgehende Belege") for the entry of this dunning doc, and sending email worked fine: **OK**
