### ISSUE TITLE
Turn C_DunningDoc into a real document

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4615]
### Is this a bug or feature request?
FR
### What is the current behavior?

C_DunningDoc  "looks" like a document, but it's not an `IDocument`.
This causes different problems. e.g.
* you can't just "print" it, but need a dendicated print-process
* the user needs to run a dedicated "process" pricess, instead of using complete/reactivate
* in C_DocOutBoundLog ("Ausgehende Belege"), there is no (Document-)date and also no C_DocType, which makes it really hard to select dunnings in order to mail them

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh/issues/4615 to `release`

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh/issues/4615 to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in release

1. you can't just "print" it, but need a dendicated print-process: still cannot print a dunning document, need to use the process "Mahnbrief Jasper" or the one for concatenated  dunning doc and invoice: is that wanted? (action print is not available, shortcut causes Whitelabel Error)

2. the user needs to run a dedicated "process" pricess, instead of using complete/reactivate: complete/reactivate are now available for dunning document as well, and work fine: **OK**
=> reactivating / completing creates new entries in printing queue, and increases the no. of PDFs in DocOutbound for the resp. dunning doc, but when sending the PDF per email only 1 is sent (=> the one where sth was changed in the document, e.g. dunning date): **OK**

3. in C_DocOutBoundLog ("Ausgehende Belege"), there is no (Document-)date and also no C_DocType, which makes it really hard to select dunnings in order to mail them: (Document-)date and C_DocType now included in C_DocOutBoundLog ("Ausgehende Belege"), filtering works fine: **OK**

4. regression testing docactions:
* had a problem when invoicing after reactivating a shipment: "HasChanges" Error, IC for packing item had qty: 0, although shipment was completed again

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

1. dunning document can now be printed like other documents: "Print" action available, shortcut working as well (process for concatenated dunning doc and invoice still available: OK
2. & 3. still OK
4. fixed in #4624
