### ISSUE TITLE
Clone Quotation, switch Sales Order. Wrong Document No

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#4644]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* Currently, there are 2 sequences that go to C_Order, sales: One for doctype Sales Order and one for doctype Quotation. These sequences are identical => some of the document numbers will be similar for 2 documents of the 2 doc types.
The problem is that we also have a unique index / partner and / C_DocType_ID. But the C_DocType_ID is only set on completion, before that it's always 0 => 2 drafts ( 1 quotation and 1 sales order)  with the same doctumber will cause an error.
#### Which are the steps to reproduce?
* Try and see
### What is the expected or desired behavior?
* Improve the index to only apply the clause on completed  or closed orders. This way, we make sure the validation is done after the C_Doctype  is actually set.

**Comment by metas-rc** [comment]
Dev test: 

* A sales order of the same org, doctype and documentNo as another completed sales order shall throw an error when trying to complete it;
* the document number shall be correctly updated when you clone an order and change it doctype.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* sales order of the same org, doctype and documentNo as another completed sales order shall throw an error when trying to complete it: OK
*  document number shall be correctly updated when you clone an order and change it doctype: it's set to the next available no. of the sequence (e.g. clone sales order no. 17 => you get no. 18, set quotation: you get e.g. no. 04, since there are already 3 quotations): OK
* create 2 drafts ( 1 quotation and 1 sales order) with the same docnumber: no error, you only get an error when you try to complete and the no. is already set for a completed document of the resp. type: OK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* re-tested the new testcase: working fine, OK
* regression: i changed the doctype sev. times in the same document, and each time the document no. was increased,:
 => e.g. when i set doctype: sales order, the document no. first was 0003, which was correct, 
=> then i changed it to quotation and then back to sales order: document number now was 0004: is that OK? shouldn't it be 0003 again since it is still the same document? @metas-rc wdyt?

**Comment by metas-rc** [comment]
This is happening because the sequence increases and doesn't care if you save or not. It will never decrement back.
See https://www.postgresql.org/docs/current/sql-createsequence.html

``` 
Because nextval and setval calls are never rolled back, sequence objects cannot be used if “gapless” assignment of sequence numbers is needed. It is possible to build gapless assignment by using exclusive locking of a table containing a counter; but this solution is much more expensive than sequence objects, especially if many transactions need sequence numbers concurrently.
```

**Comment by metas-rc** [comment]
Followup created: https://github.com/metasfresh/metasfresh/issues/4758
