### ISSUE TITLE
AD_Element based Names and Translations for AD_Tab, Window, Menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4662]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, AD_Elements are used for Field Names, Descriptions and Translations. Fieldnames and Translations shall only be done via AD_Elements. Tab Names still have to be done in AD_Tab and their Translations in the corresponding _trl table.
Same for , Window, Menu entries.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The Name setting and Translation recording of Tabs shall be similar to AD_Fields and be done via AD_Elements. Same for Window, Menu.
Please be aware that Names and Translations in AD_Field are already readonly.

Later this concept shall be extended for all application dictionary Translations (e.G. Process ...).

**Comment by metas-ts** [comment]
We need to take care about migrating existing systems;
The work that was done until now is reverted from `master`, and is not in the branch `gh4662_mig`

Suggestion/Idea

Add a DB-function that makes the new AD_Element_IDs non mandatory.

Add a startup-houskeeping-task and a process that both run the same code

The code shall iterate the tables in question and:
* find records with empty AD_Element_IDs
* check if an AD_Element exists, that fits with the respective table record;
  * create an AD_Element if none exists
* set the AD_Element_ID
* when all records of the respective tables are done, it makes AD_Element_ID mandatory again

That way, if there is a problem applying migration scripts because of this issue, the admin can 

* invoke the DB-function
* do the rollout (where "AD_Element_ID = null" records will be created)
* watch metasfresh clean up un its next startup

Also, we can prepend that DB function to existing migration scripts which don't yet have the required AD_Elemets

**Comment by metas-rc** [comment]
Testing

* Log in as sys admin in swing

1) The Application Dictionary changes
1.1
* Go to Windows Management and create a new window
* => There should be a field for System Element (AD_Element_ID)
* => The field shall now be mandatory
* Set an element there
* => The window shall receive the name, description and help from the AD_Element
* => The Name, Description and Help shall become readonly
* Save the entry
* Go to translations tab
* => The translations shall be the ones from AD_Element_Trl of the respective languages
* => The name, description and help shall be readonly.
* Go to the element you set
* Change the element name
* Go back to your window
* => The name shall be changed
* Go to the element translation, change something in a language ( e.g. the name in Italian)
* Go to the window translation and check the same language
* => The translation from the element shall be also set here

1.2 Same with AD_Tab ( extra column here: CommitWarning)

1.3 Same with AD_Menu ( this one has some extra columns for webui. They all start with Browse. And it lacks the Help column) 




1.4 Misc
* => When searching for an element now you can type in the name and you should find it. The columnname is no longer mandatory so it would be a pain to keep it as the unique identifier.

2) The process

* Go to the pg admin and run this function: 
```
select Element_ID_Not_Mandatory_ApplicationDictionaryTables()
```
* This function makes the AD_Element columns not mandatory in the tables AD_Menu, AD_Tab and AD_Window

* Optional: For fully testing the process itself you would need to update all the menus, tabs and windows and set the AD_Element_ID = null. I don't think this is needed. The script with the existing entries was already generated and provided in this issue.


2.1
* Create a new window and don't set any element for it.
( Due to an old bug we are able to set the name, description and help even if they are readonly, by copy-pasting them from somewhere. 
I suggest to do it this way.
Another option would be to insert the entry via database)
* Save the entry
* Go to the Element window ( doesn't matter what line you select) 
* Open the gear
* => The process "Create Missing AD_Elements" shall be available 
* Run this process
* Go back to your window 
* => The window entry now has an element . 
* This element was generatedby the process with all the details of the window: name, description, help and all the translations
* => From now on, this new element shall work as described in step 1, like any other element.

2.2 Same for AD_Tab

2.3 Same for AD_Menu

**Comment by metas-rc** [comment]
Please, review and test together with https://github.com/metasfresh/metasfresh/issues/4663

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* AD_Element name cannot be changed, see IT for #4663 (did not test any further, shall be fixed together with that task by metas-rc soon)

**Comment by metas-rc** [comment]
Could not reproduce the bug.

**Comment by metas-dh** [comment]
Results of IT2
tested in release / mf15

most of the things described above worked fine:
1. Application Dictionary changes:
* worked fine for AD_Window & AD_Menu, with System Element being mandatory, changes in AD_Element_Trl etc. worked fine too, all changes were propagated correctly: OK
* only had problems with AD_Tab, see https://github.com/metasfresh/metasfresh/issues/4663#issuecomment-459388804


2. Process:
* AD_Element_ID was not mandatory anymore after running the query in db: OK
* "Create Missing AD_Elements" was available and worked fine:
    * AD_Elements were created correctly, as described above: OK
    * all corresp. new Application Dictionary entries were linked by the resp. AD_Element: OK
    * AD_Element_ID was then mandatory, as described above: OK
* again, only had problems with AD_Tab, see https://github.com/metasfresh/metasfresh/issues/4663#issuecomment-459388804

* migration script was created: OK
