### ISSUE TITLE
New Window "Application Elements"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4664]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, a customizer must maintain the names, descriptions, notes in windows/ Tabs like "Window", "Tab", "Field", "Menu". The same is valid for the corresponding Translations.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a new generic Window "Application Elements". This window shall show all infos that allows the easy translation of all ad_elements.
- Columnname, Language, Name, description, istranslated, Attributefield with windowname

**Comment by metas-rc** [comment]
Docu

1) AD_Element_Link table 
* I added the table AD_Element_Link.  It has the columns AD_Element_ID and AD_Window_ID ( and also the defaults columns)
* This table will link the AD_Element with the AD_Window entries where it is used ( AD_Window.AD_Element_ID) 
* I created a process called "Create Missing AD_Element_Links". When ran, it created entries in AD_Element_Link for all the window-element pairs that are missing.
8 I ran this process and provided the script that was generated by it. It creates AD_Element_Link entries for all the window-element pairs that are currently existing in the database.
* I also made the link create after the AD_Element_ID is set in the AD_Window.
* Normally, the process above shall not be really needed. But nevertheless, if links are needed in other customer systems that have specific  element-window pairs then this process is an easy way to create them and generate the scripts.

2) AD_Element_Trl
* I introduced the columnsql "ColumnName" in AD_Element_TRL. It points to the columnname of the parent AD_Element.

3) Application Elements window
* I created the Application Elements window that contains all the AD_Element_TRL entries together with all the editable fields.
* I also added the tab AD_Element_Link so I can have it in the webui as label element.
* =>  Each Application Elements entry shall contain: 
 * The Element_ID  (when zooming in,  this should lead to the parent AD_Element. To be solved in https://github.com/metasfresh/metasfresh-webui-api/issues/1099 )
 * The Element's ColumnName
 * Language and IsTranslated
 * All the translatalbe fields : name, print name, description, help, po_name, po_PrintName, po_description, po_help, commitWarning, Webui_Browseame, WEBUI_NewRecordName, WEBUI_NewRecordName (breadcrumb) 
 * A label field for the AD_Element_Link entries. Here, we shall see all the AD_Windows that have this AD_Element set in AD_Window.AD_Element_ID.
* There should be an entry for each language present in AD_Element_Trl
* When changing the translatable fields from thi window, the change shall be propagated to the database ( check if it is also present in the window Element, tab Translations)
* We should be able to filter by the label fields, too. At the moment this is broken. Should be fixed in https://github.com/metasfresh/metasfresh-webui-api/issues/1098 )
* The label field's content is not displayed in grid view. Talked with @teosarca and he said this is not yest implemented. We shall decide if/when this should be implemented. Until then, the linked windows will only be displayed in single view.

**Comment by metas-rc** [comment]
Version_release: 5.81.2_12964_gh4664

**Comment by metas-rc** [comment]
This task also fixes the IT fail in https://github.com/metasfresh/metasfresh/issues/4652

**Comment by metas-rc** [comment]
Version_release: 5.82.2_12992_gh4664

**Comment by metas-ts** [comment]
🍒 picked PR https://github.com/metasfresh/metasfresh/pull/4808 to `release`

**Comment by metas-ts** [comment]
🍒 picked commit https://github.com/metasfresh/metasfresh/commit/253dda2c6033ccd0e6d7b872483320add540d6ed to `release`

**Comment by metas-dh** [comment]
related tasks #s 571, 572 are failed, will test all together again when those are back in IT and document then.

**Comment by metas-dh** [comment]
Results from IT
tested in release

tested Application Elements window:
* in WebUI, all of the above worked fine: all fields were displayed correctly, all languages were included, all changes were propagated correctly etc.: OK
* in Swing the window was empty: no. of entries was displayed, but the content was not: OK this way, since the window is to be used in WebUI only!
