### ISSUE TITLE
Product traceability

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#484]
Product traceability

Input parms v1.0:
- Product Value, Name or customer product value
- Shipment No., Shipment Date
- external Reference No. (PO Reference Sales Order)

Input parms v1.1:
- Product Value, Name or customer product value
- Producer (BPartner)
- Material Receipt No., Material Receipt Date, Material Receipt Label (Etikett)

Results/ gathered informations needed:
- Where does the product come from (Purchase Order, Producer, Receipt Date, Quantity)?
- Which are the customers that were delivered with this product (also action issues as raw material for finished goods)?
- Where are local quantities of this product?

Input parms v2.0:
- Manufacturing Ressource
- Manufacturing Date+Times between
- Material Receipt No., Material Receipt Date, Material Receipt Label (Etikett)

Results/ gathered informations needed:
- Which other products were produced on the selected Manufacturing Ressource at the selected time?
- Which are the customers that were delivered with these manufactured goods (also action issues as raw material for finished goods)?
- Where are local quantities of this product?

--> Result must be window/ report with possibility for excel export. Result must be selectable in short timeframe (max. 2hours)

**Comment by metas-ts** [comment]
Note: issues #1496 and #1761 have explicity some requirements that belong to this task as well

**Comment by metas-ts** [comment]
Implemented the "backend"..i.e. new Table `M_HU_Trace` with a "default" AD_Window etc.
In case of tproblems, tracing can be switched off via sysconfig `de.metas.handlingunits.trace.interceptor.enabled`

**Comment by metas-ts** [comment]
cherry-picked two bugfixes into the `release` branch

**Comment by metas-lc** [comment]
1. go to handling units editor window and select a random CU. Use transform and try to move it on an exiting TU
https://w101.metasfresh.com:8443/window/540189?viewId=540189-8874796a03df4465a06fbb6fba6d655e&page=1

Select a TU => error
Error: org.postgresql.util.PSQLException: ERROR: null value...
Server error
org.postgresql.util.PSQLException: ERROR: null value in column "m_hu_id" violates not-null constraint Detail: Failing row contains (1000000, 1000000, 2017-08-09 17:51:35+02, 2188223, Y, null, 1000029, null, null, null, 2017-08-09 17:51:35+02, 2188223, 2017-08-09 17:51:35+02, TRANSFORM_LOAD, null, null, null, 1000697, null, P, 1002026, null, 2005577, -10). SQL: INSERT INTO M_HU_Trace (AD_Client_ID,AD_Org_ID,Created,CreatedBy,EventTime,HUTraceType,IsActive,M_HU_Trace_ID,M_HU_Trx_Line_ID,M_Product_ID,Qty,Updated,UpdatedBy,VHU_ID,VHUStatus) VALUES (1000000,1000000,TO_TIMESTAMP('2017-08-09 17:51:35','YYYY-MM-DD HH24:MI:SS'),2188223,TO_TIMESTAMP('2017-08-09 17:51:35','YYYY-MM-DD HH24:MI:SS'),'TRANSFORM_LOAD','Y',nextval('m_hu_trace_seq'),1002026,2005577,-10,TO_TIMESTAMP('2017-08-09 17:51:35','YYYY-MM-DD HH24:MI:SS'),2188223,1000697,'P') RETURNING M_HU_Trace_ID

**Comment by metas-lc** [comment]
SWING
1. purchase order -> inout (5 TU x 10).
I got 2 M_HU_Traces: one for Wareneingang and one for Warenbewegung
a+b. (why is doubled? just different IDs)
typ Wareneingang
VHU 18057421. The one i did inout with
doctype Produktanlieferung
inout 1229598. my inout
trx NULL
cost collector NULL 
ursprungs-vhu NULL
produkt Topinambour_P000290
menge 50
zeitpunkt 15.09.2017 12:27
HU 18057420
status Active
docstatus Fertiggestellt
movement NULL
Lieferdispo NULL
Produktionsauftrag NULL
c.
typ Warenbewegung
VHU 18057421
doctype Warenbewegung
inout NULL
trx NULL
cost collector NULL 
ursprungs-vhu NULL
produkt Topinambour_P000290
menge 50
zeitpunkt 15.09.2017 12:27
HU 18057420
status Active
docstatus Fertiggestellt
movement 1272203
Lieferdispo NULL
Produktionsauftrag NULL


2. Split an Active HU (e.g. take the one from step 1, split 2 TUs on new LU) 
=> 2 new HU Trace are created: 
a.
typ HU-Transformation
VHU 18057421
doctype NULL
inout NULL
trx 36192987
cost collector NULL 
ursprungs-vhu NULL
produkt Topinambour_P000290
menge -20
zeitpunkt 15.09.2017 12:35
HU 18057420
status Active
docstatus NULL
movement NULL
Lieferdispo NULL
Produktionsauftrag NULL
b.
typ HU-Transformation
VHU 18057425
doctype NULL
inout NULL
trx 36192987
cost collector NULL 
ursprungs-vhu 18057421
produkt Topinambour_P000290
menge 20
zeitpunkt 15.09.2017 12:35
HU 18057424
status Active
docstatus NULL
movement NULL
Lieferdispo NULL
Produktionsauftrag NULL
 
3. PP Order -> issue HUs
=> i got 2 HU-Gebinde-Änderung types 
a.
typ HU-Gebinde-Änderung
VHU 18057423
doctype NULL
inout NULL
trx NULL
cost collector NULL 
ursprungs-vhu NULL
produkt Frisée Industrie
menge -30
zeitpunkt 15.09.2017 12:40
HU 18057422
status Active
docstatus NULL
movement NULL
Lieferdispo NULL
Produktionsauftrag NULL
b. same, but HU 18057423 (the VHU), menge 30
questions:
There are cost collectors for "Component Issue". Shouldn't i have traces for them?
Gebindestatus shouldn't be Destroyed (probbaly Issued in the future)?  

4. PP Order -> receive the main product
=> 1 new TU trace
type Produktionsentnahme
vhu the ones i received 18057427
doctype Manufacturing Cost Collector
inout NULL
trx NULL
cost collector AB Alicesalat 250g_1234567890148_P000787
ursprungs-vhu NULL
produkt AB Alicesalat 250g
menge 100
zeitpunkt 15.09.2017 12:45
HU 18057426 the ones i received
status Active
docstatus Fertiggestellt
movement NULL
Lieferdispo NULL
Produktionsauftrag 1046355_Stöckenteilen

5. Bereitstellung pos - moving the product from 1 wh to another
=> 2 new hu traces were created, for movements: from w1 to transit and from transit to wh2
typ Warenbewegung
VHU 18057427
doctype Warenbewegung
inout NULL
trx NULL
cost collector NULL 
ursprungs-vhu NULL
produkt AB Alicesalat 
menge 100
zeitpunkt 15.09.2017 12:47
HU 18057426
status Active
docstatus Fertiggestellt
movement 1272207, 1272208
Lieferdispo NULL
Produktionsauftrag NULL

6. auftrag -> komm terminal (use the HU from step 4)
=> 1 new hu trace was created
type Kommissionierung
vhu the one i picked 18057427
doctype NULL
inout NULL
trx NULL
cost collector NULL
ursprungs-vhu NULL
produkt AB Alicesalat 
menge 100
zeitpunkt 15.09.2017 12:51
HU 18057426 the one i picked
status Active
docstatus NULL
movement NULL
Lieferdispo - my inout (i can zoom in)
Produktionsauftrag NULL

7. lieferdispo - create inout with the picked HUs
=> 1 new hu trace was created
type Kommissionierung
vhu the one i picked 18057427
doctype NULL
inout NULL
trx NULL
cost collector NULL
ursprungs-vhu NULL
produkt AB Alicesalat 
menge 100
zeitpunkt 15.09.2017 12:53
HU 18057426 the one i picked
status Picked
docstatus NULL
movement NULL
Lieferdispo 10 (i can zoom in)
Produktionsauftrag NULL

8. do another auftrag and use kommissionier terminal and hinzuf/verteilen, then use Verdichtung POS 
=> error regarding qtys (i think it's related with trace)

9. dispose
go to first inout you created at 1st step (wareneingang pos), press on korrektur and seletc your hu + dispose
=> 2 HU-Gebinde-Änderung were created, nothing for movements to gebindelager (probably because the movements are not linked with the document/hus)!!!!!!!!!!!!!!!
typ HU-Gebinde-Änderung
VHU 18057421
doctype NULL
inout NULL
trx NULL
cost collector NULL 
ursprungs-vhu NULL
produkt Frisée Industrie
menge -30
zeitpunkt 15.09.2017 12:40
HU 18057422
status Active
docstatus NULL
movement NULL
Lieferdispo NULL
Produktionsauftrag NULL
b. same, but HU 18057421 (the VHU), menge 30
questions:
Gebindestatus shouldn't be Destroyed?  

10. revert the disposal
no new hu trace... i would have expected similar to step 9..???

11. return vendor 
go in wareneingang pos at the same HU and instead of dispose do vendor return
- NO HU trace was created! would have expected something like this:
type Warenlieferung 
vhu the one i moved 
doctype Produktrücklieferung
inout - my vendor return 
trx NULL
cost NULL
ursprungs-vhu NULL
produkt radiesli
menge 10
zeitpunkt 15.09.2017 13:10
HU  the one i moved
status Active
docstatus Fertiggestellt
movement NULL
Lieferdispo NULL
Produktionsauftrag NULL

12.quality movement OK

type Warenbewegung
vhu the one i moved 
doctype Warenbewegung
inout NULL
trx NULL
cost NULL
ursprungs-vhu NULL
produkt Topinambour
menge 10
zeitpunkt 15.09.2017 13:32
HU  the LU i moved
status Active
docstatus Fertiggestellt
movement 810920
Lieferdispo NULL
Produktionsauftrag NULL

12. materialentnahme OK
same as quality

13. customer return 
did customer return for inout step 7
type Wareneingang
vhu the one i returned 
doctype Kundenwarenrückgabe
inout - my return (btw i can't zoom in !!!!!!!!!!!!!!)
trx NULL
cost collector NULL
ursprungs-vhu NULL
produkt salad
menge 100
zeitpunkt 15.09.2017 13:36
HU  the LU i returned
status Active
docstatus Fertiggestellt
movement NULL
Lieferdispo NULL
Produktionsauftrag NULL

type Warenbewegung
vhu the one i returned 
doctype Warenbewegung
inout NULL
trx NULL
cost collector NULL
ursprungs-vhu NULL
produkt salad
menge 100
zeitpunkt 15.09.2017 13:36
HU  the LU i returned
status Active
docstatus Fertiggestellt
movement 1272219
Lieferdispo NULL
Produktionsauftrag NULL


WEBUI

**Comment by metas-lc** [comment]
IT
WEBUI
1. purchase order with 5 TUs on 1 LU wh1 -> inout wh2
=> 1 hu trace, for wareneingang OK
![1_purchase_inout](https://user-images.githubusercontent.com/16001666/31545127-c8a07da4-b026-11e7-8c54-22a8f0587a07.png)

2. split out 2 TUs from LU to another LU
=> 2 HU trace, for Transform OK
![2_transform_split](https://user-images.githubusercontent.com/16001666/31545432-1755fd2e-b028-11e7-81aa-e5a0cddcc594.png)
![2_transform_split_2](https://user-images.githubusercontent.com/16001666/31545436-1a0b56ea-b028-11e7-8b62-686a8b5ae3ca.png)

3. PP Order -> issue HUs (1 LU with 3 TUs)



4. PP Order -> receive main product
