### ISSUE TITLE
Different improvements around MSV3 server synchronization

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4881]
### Is this a bug or feature request?
bug / FR

See https://github.com/metasfresh/metasfresh/issues/4881#issuecomment-457202376 for details

**Comment by metas-ts** [comment]
Drop the msv3server's table `msv3_user`, start the msv3 server
=> there is a new column:
![image](https://user-images.githubusercontent.com/1264789/51457527-f74bb080-1d51-11e9-8578-0f8356ea4e9e.png)

create or edit the userId of an existing record in metasfresh (MSV Customer Config - https://hostname/window/540423 ):
![image](https://user-images.githubusercontent.com/1264789/51457721-b86a2a80-1d52-11e9-97b9-70d82de907ca.png)

check the msv3server's table `msv3_user`: record is there
![image](https://user-images.githubusercontent.com/1264789/51457792-097a1e80-1d53-11e9-98a8-eba015e6f9d9.png)

Change data in metasfresh again 
=> the msv3server's table `msv3_user` is updated

**Comment by metas-ts** [comment]
# Results

* use MSV3_Customer_Config_ID as external user ID within the msv3 server
  * => allows us to edit the user name and an existing msv3 server record is updated
* msv3-user is deleted also if the customer config record is *deactivated* on metasfresh
* semi-related improvements to field name and descriptions
  * warehouse picking-group
  * the description text contains a warning for MSV3_Server not to have an empty picking group
* we can now send large numbers of products to the msv3-server
  * sending is done in batches
    * the batch size is set via `de.metas.vertical.pharma.msv3.server.peer.metasfresh.services.MSV3StockAvailabilityService.publishAll_StockAvailability.BatchSize`
  * the data to send is stored in a temporary table `T_MD_Stock_WarehouseAndProduct` (to allow iterateAndStream while the actual stock might change)
  * concurrent stock changes that happen during normal metasfresh use are send in parallel
    * the "last" batch updates (with an "old" stock info) won't override the more recent events that had happened in between
* The msv3 server by default now justs request the *config* on startup, and not all the stock availability data
* The msv3 server by default now does not reset the local DB anymore
* The msv3 server's JVM now uses memory infos from Docker instead of requiring a static `-Xmx` parameterisation
* The msv3 server avoids flooding the metasfresh-app server log in case no auth token was specified
