### ISSUE TITLE
BPartner Product statistics: LastShipmentDate, LastReceiptDate

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4894]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?
* Introduce a new table, called C_BPartner_Product_Stats where we shall store the last shipment and last receipt date for each product/bpartner.
* The table shall be updated after each completed M_InOut.
* The feature shall be disableable
* An easy to use API shall be provided to get the stats for a given set of product IDs.

### Note to IT:
* check the Product Proposals modal views which can be opened from Sales/Puchase Order and from BPartner. The last column of those views is about how many days passed from last shipment/receipt. TO compute that we use this task.
* additionally, pls make sure material balance is still updated when completing shipments/receipts

### Troubleshooting/fixing: fully refresh the statistics
```sql
select C_BPartner_Product_Stats_refresh();
```

**Comment by teosarca** [comment]
removed branch:master and branch:release because where were set by mistake (nothing committed on this task yet)

**Comment by metas-dh** [comment]
Results of IT1
tested in release

Products Proposal in sales / purchase order:
* shows all available products: => all that have a price set for purchase / sales side (e.g. product w/ only sales price is not displayed in PO proposal): OK
* days passed from last shipment/receipt: correctly displayed: 0 for last shipment on the same day, 1 for last receipt on the day before: OK
* qty: was not set, i think that's NOK
* attributes: also empty, although there were shipments / receipts where attributes were set for products: NOK
* no trl for de_DE, only Products Proposal: NOK

**Comment by teosarca** [comment]
> * qty: was not set, i think that's NOK

That's OK. The qty shall be entered by the user. When he/she presses OK, all those rows where the Qty is set will become order lines.

When opening the Products Proposal from BPartner, the Qty column won't be available.

**Comment by teosarca** [comment]
> * attributes: also empty, although there were shipments / receipts where attributes were set for products: NOK

The Attributes are shown from Price List. If there are no attributes, no attributes will be shown here.

PS: imagine this Product Proposals view more like an "Ordering form".

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* trl for de_DE: OK
* attributes displayed if set in price list: OK
* qty can be changed in the overlay, in order to create orderlines: setting a qty was possible, but did not test further since that wasn't the scope of this task: OK
* days passed from **last shipment** / **last receipt** displayed in sales order / purchase order or in bpartner window: 
     * when action was called in sales order, days passed were displayed: OK
     * when action was called for bpartners that were only customer, days passed were displayed: OK
     * when action was called in purchase order, days passed were displayed: OK
     * when action was called for bpartners that were only vendor or vendor & customer the days passed remained empty: why?

* days passed correctly for products with attributes:
=> material receipt for a product with and without attribute set: OK

![2019-02-07 14_06_23-metasfresh](https://user-images.githubusercontent.com/18696715/52413601-62cba700-2ae2-11e9-9835-d06082c1705b.png)



   => shipment for a product without attribute only: days passed for the product **with** attribute was displayed too, although that was not included in any shipment: why?

![2019-02-07 14_06_43-metasfresh](https://user-images.githubusercontent.com/18696715/52413690-94dd0900-2ae2-11e9-9b9a-ac055352657e.png)

**Comment by metas-dh** [comment]
checked with teosarca:

* bpartner that has no shipment / receipt yet shows no days passed from **last shipment** / **last receipt**: OK
* bpartner that is both customer and vendor: => system considers Customer if possible, if not Vendor:
    * for bpartner that is both customer & vendor, has only receipt but no shipment: days passed from **last shipment** are all empty: OK
    * for bpartner that is both customer & vendor, has both receipt and shipments: days passed from **last shipment** are set correctly: OK
    * bpartner that is not customer, only vendor: days passed from **last receipt** are set correctly: OK
