### ISSUE TITLE
Migration: Create Requests for all inout lines with quality issues

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#500]
Create an sql that inserts entries in R_Request for all the inout lines that have quality issues, from the last year and a half.

Follow logic from https://github.com/metasfresh/metasfresh/issues/361

**Comment by metas-rc** [comment]
Extra requirements about R_Request windows: 

a) delete all request types which are not those 2 and email)
b) move field request type to the top #1
c) rename request type "Lieferantenreklamation" to "Lieferantenbeanstandung"
d) make request type "Kundenbeanstandung" as default value

**Comment by metas-rc** [comment]
QualityNotice shall be a list with all the quality notice attribute values and result in a dropdown ( similar with wareneingang pos)

**Comment by metas-rc** [comment]
Add a callout that automatically sets the dateDelivered as the movement date of an inout if the request was created based on that inout.
This applies to requests created from the "add request" button in icon bar from Shipment.

**Comment by metas-rc** [comment]
New requirements: 

1) New request type: Konsumentenreklamation
* Add internal name + display logic
2) Migration -> status to closed
3) Mare Vorgang and Vorgang (alle) transaction windows transactional window
4) Add an intermediate table containing the quality notes, containing also the Performance Type column
* The performance type in R_Request will be automatically set based on the performance type in Quality Note entry
* TODO for later: Use this new table also in M_InOutLine, to get rid of the string QualityNote
5) There are only 5679 inout lines in the customer db, too. To decide what to do regarding the async migration

**Comment by metas-rc** [comment]
Additional things that were needed

* migration of the qualitynotes ( performance type not yet set. waits for Mark's expertise)
* val rule on performance type 
* callout on qualityNote change for the performance type value
* unique index on name for M_QUalityNote
* dao for retrieving the fit one

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: erptest-app
* Buildno: #620

* request for sales inout, created from shipment:
** Kundenbeanstandung, inout & bpartner set: OK
** Noitz: to be filled manually, product not set since >1 inoutlines possible: OK
** Auftrag not set, no relation from Auftrag: was probably like that before, OK

* new request created manually:
** doytype: Kundenbeanstandung: OK
** Beanstandung field: empty initially, values from quality note selectable in dropdown: OK

* Bericht Reklamationen:
** 1 orderline, >1 receiptline, 1 quality issue: 1 line with inout no.: OK
** 1 orderline, >1 receiptline, >1 quality issue: 1 line with inout no. ff.: OK

* Migration:
** 5.273 new requests created by SuperUser, 27.10., at  22:06, doctype: Lieferantenbeanstandung, Notiz: Qualitätsabzug Wareneingang, status: closed: OK (not 5.679, probably because erptest is older than erpprod)

* request for material receipt:
** if quality issue set, new request is created, doctype: Lieferantenbeanstandung, Notiz: Qualitätsabzug Wareneingang, with resp. bpartner, product, inout no.: OK
** request created for receipt with quality issue: quality note set in Wareneingang POS is not displayed in Beanstandung, remains empty (can be set manually): NOK
** set performance type for 2 different quality notes in M_QualityNote, selected in Wareneingang POS: not set in request: NOK
** checked with ts: the last 2 points might be related to sth wrong in cherry picking / rollout
