### ISSUE TITLE
Possibility to define multiple Washing Testcycles for Carrots

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#505]
Possibility to define multiple Washing Testlevels for Carrots
- In material Receipt HU Editor have a Dropdpwn for 1st, 2nd Washing Test
- These attributevalues shall already be setable in Purchase Order (each seperate line in Purchase Order)
- This shall be shown on Material Receipt Label, and as Attribute in Material Receipt Line.
- Show the different Washing Testlevels in RV_M_Material_Tracking_HU_Details instead of just Flag
- Only Allow Action Issue for document type "Washprobe" for HU which are marked as 1st, 2nd Washing Testlevel
- In Material Receipt automatically move the HU into fixed Warehouse-Locator when marked as 1st, 2nd level, depending on level.

**Comment by metas-dh** [comment]
Results of IT 1

  *  App.Server: erptest-app
  *  Buildno: #620

* SysConfig set for warehouse destination, based on Quality Inspection Cycle:
** destination warehouse is set for resp. orderline with WP 1 / 2 in Wareneingangsdispo / Wareneingang POS: OK

* Attribute values Waschprobe 1 & 2:
** selectable in purchase order: OK
** displayed correctly in HU Editor, Wareneingang POS: OK
** can be changed in dropdown, HU Editor, Wareneingang POS: OK
** displayed ad Waschprobe 1 / 2 in Wareneingangsetikett: OK
** displayed ad Waschprobe 1 / 2 in receiptline: OK
** not displayed in Produktanlieferung (receipt Jasper): OK

* Washing Testlevels in RV_M_Material_Tracking_HU_Details:
** Waschprobe 1 / 2 displayed in  RV_M_Material_Tracking_HU_Details: OK
** old "Waschprobe" still displayed in  RV_M_Material_Tracking_HU_Details: OK for now, necessary for existing, old HUs

* Material Receipt: automatically move the HU into fixed Warehouse-Locator:
** destination warehouse is set for resp. orderline with WP 1 / 2 in Wareneingang POS, acc. to Sysconfig (s. above): OK
** HUs are moved to this destination warehouse, (if it's not changed  in Wareneingang POS): OK

* Only Allow Action Issue for document type "Waschprobe 1 / 2" for HU in Produktion Fertigstellung POS:
** only HUs with Waschprobe 1 or 2 are displayed in HU Editor, Action Issue, NOT with Waschprobe alt: OK
** no difference between Waschprobe 1 or 2, for 1st or 2nd Waschprobe: OK atm
** PP_Order button in  Produktion Fertigstellung POS now displayes "Waschprobe" or "Produktionsauftrag": OK

* Remaining issues:
** old Waschprobe attribute still selectable in purchase order: NOK, shall be taken out, BUT: flag shall still be displayed in HU Editor for old HUs, where it was set!
** old "Waschprobe" button in Wareneingang POS: Sysconfig for that was set manually on erptest, so the button did not appear anymore; shall be done by migration script
** HUs with Waschprobe 1 / 2 not considered for qty of Anzahl HUs für Waschprobe, in the 1st tab of Material-Tracking, only the ones with old Waschprobe flag: NOK
** all 3 issues are fixed by teo, shall be ok with next release (s. task chat)

**Comment by metas-dh** [comment]
Results of IT 1

  *  App.Server: erptest-app
  *  Buildno: #620

* SysConfig set for warehouse destination, based on Quality Inspection Cycle:
** destination warehouse is set for resp. orderline with WP 1 / 2 in Wareneingangsdispo / Wareneingang POS: OK

* Attribute values Waschprobe 1 & 2:
** selectable in purchase order: OK
** displayed correctly in HU Editor, Wareneingang POS: OK
** can be changed in dropdown, HU Editor, Wareneingang POS: OK
** displayed ad Waschprobe 1 / 2 in Wareneingangsetikett: OK
** displayed ad Waschprobe 1 / 2 in receiptline: OK
** not displayed in Produktanlieferung (receipt Jasper): OK

* Washing Testlevels in RV_M_Material_Tracking_HU_Details:
** Waschprobe 1 / 2 displayed in  RV_M_Material_Tracking_HU_Details: OK
** old "Waschprobe" still displayed in  RV_M_Material_Tracking_HU_Details: OK for now, necessary for existing, old HUs

* Material Receipt: automatically move the HU into fixed Warehouse-Locator:
** destination warehouse is set for resp. orderline with WP 1 / 2 in Wareneingang POS, acc. to Sysconfig (s. above): OK
** HUs are moved to this destination warehouse, (if it's not changed  in Wareneingang POS): OK

* Only Allow Action Issue for document type "Waschprobe 1 / 2" for HU in Produktion Fertigstellung POS:
** only HUs with Waschprobe 1 or 2 are displayed in HU Editor, Action Issue, NOT with Waschprobe alt: OK
** no difference between Waschprobe 1 or 2, for 1st or 2nd Waschprobe: OK atm
** PP_Order button in  Produktion Fertigstellung POS now displayes "Waschprobe" or "Produktionsauftrag": OK

* Remaining issues:
** old Waschprobe attribute still selectable in purchase order: NOK, shall be taken out, BUT: flag shall still be displayed in HU Editor for old HUs, where it was set!
** old "Waschprobe" button in Wareneingang POS: Sysconfig for that was set manually on erptest, so the button did not appear anymore; shall be done by migration script
** HUs with Waschprobe 1 / 2 not considered for qty of Anzahl HUs für Waschprobe, in the 1st tab of Material-Tracking, only the ones with old Waschprobe flag: NOK
** all 3 issues are fixed by teo, shall be ok with next release (s. task chat)

**Comment by metas-dh** [comment]
tested again on sp80adit, #s 551, 557: all issues fixed
