### ISSUE TITLE
Short term availability check for sales orders

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#5108]
### Is this a bug or feature request?
FR

# Raw concept with 🤓 comments and 🔨 results

When user tries to complete an Sales Order, we need to make sure that the qty from order lines while be available on DatePromised.

We need a quick but efficient way to do that.
* 🤓 comment-ts:
  * totally true; quick but efficient. So don't consider it done when you only know that it runs on a DB with 5 products and 10 order lines; note: we same sufficently large DBs to the this with, so no need to try and generate some artificial data yourself
  * that probably also means that we need to the following stuff for `n` order lines with just one query (i.e. *not* 1 query for each order line) in order to avoid the dreaded `n+1` problem
* 🔨 **result-ts**: done via function `de_metas_material.retrieve_available_for_sales` which uses the view `de_metas_material.MD_ShipmentQty_V` and `MD_Stock`.

Basically, for each sales order line for current sales order, we shall calculate:

* **STOCK**: current stock level (i.e. MD_Stock table)
  * 🔨 **result-ts** done
* **SCHEDULED_RECEIPTS**: sum of all M_ReceiptSchedule until order's DatePromised (date+time!)
  * 🔨 **result-ts**: decided with mark to **not** include `M_ReceiptSchedule` because these items might or might not be delivered on time
* **SCHEDULED_SHIPMENTS** (firm): sum of all M_ShipmentSchedule(s) open quantities which are in progress (NO MATTER which is their date)
  * 🤓 comment-ts:
    * here i suggest to introduce an optional parameter (SysConfig): "number of days"
    * only consider scheduled shipments with a planned date before `now() + number-of-days`
    * the value of number of day can be set to reflect the time it usually takes to replentish missing products
    * why: otherwise there might be planned shipments (e.g. for subscriptions) that are not relevant to the user; 
      * background: she only needs to be notified if a current sales order could cause a "direct" problem; planned shipments that are sufficiently far in the future will be a addressed using material-dispo, purchase-order-disposition, production etc and shall not bother her
  * 🔨 **result-ts**: intrduced lookahead (hrs) in the dedicated config window for this feature
      
* **PLANNED_SHIPMENTS**: sum of all draft sales order lines created before our sales order line (it's enough to compare by `C_OrderLine_ID` to get the ordering); make sure this figure is excluding our current order line!
  * 🤓 comment-ts:
    * likewise, i suggest to have a (SysConfig) to make sure the don't look into the past too far. because some users have a number of stale sales orders..ofc if would be better if they cleaned those op
    * so instead of comparing by `C_OrderLine_ID`, we could add an index on `Updated` (if it's not yet there) and then compare by that
  * 🔨 **result-ts**: intrduced lookbehind (hrs) in the dedicated config window for this feature

Now, having those we can calculate if we can fulfill the current order line:
**Available to Promise (ATP)** = STOCK + SCHEDULED_RECEIPTS - SCHEDULED_SHIPMENTS - PLANNED_SHIPMENTS
 * 🤓 comment-ts: 
   * i think we need to use another term because we already have ATP and afaiu (looked on wikipedia and talked to a supply-chain expert I know) we even use it fairly correctly.
   * we might call it [CTP](https://de.wikipedia.org/wiki/Capable-to-promise) but i'm not sure...actually i think the term "CTP" would promise to much
   * => wdyt about calling it "Available to sale"
  * 🔨 **result-ts**: added two read-only field to the sales order line window
     * "kurzfr. Verfügbar" / "Available at short notice" ( =  STOCK + SCHEDULED_SHIPMENTS - PLANNED_SHIPMENTS )
     * there is also color field "Nicht kurzfr. Verfügbar" / "Not avail. on short term" that is set to a predefined color if there is a problem

Comparate the ATP with order line's QtyOrdered.
If the ATP >= QtyOrdered => OK
else => throw exception because we cannot promise that Qty.
* 🤓 comment-ts:
  * we need to notify the user, not prevent him for closing the order. to that end, i think we need to
    * display the "Available to sale" quantity in the product lookup, like we currently display the ATP. Ofc, it needs to be configurable if and which of the two one we display.
    * when user tries to complete the sale order *do not prevent that", but show a notification. Show it in a way that the user can't oversee (requires API + frontend improvements)
      * the use shall be able to complete the sale order, but need to know that she has to take immediate action.
  * 🔨 **result-ts**: user is notified via the color field in newly crated or changed sales order lines

### ASI storage key
Make sure all quantities above are computed by matching the ASI storage key.
The ASI storage key contains only the attributes which are relevant from storage point of view.

To create an ASI storage key, see org.adempiere.mm.attributes.api.AttributesKeys.createAttributesKeyFromASIStorageAttributes(int)
* 🤓 comment-ts:
  * "matching" means not only "equal". I.e. if you have a storage key in an `MD_Stock` record and you have a storage key from your order line, then the order-line-key can also be a substring of the `MD_Stock`'s key
  * for the case that it somehow turn out we need to do this directly on the DB: afair there is also a DB function which does this
* 🔨 **result-ts**: done

### UOMs
Make sure you compare the Qtys using stocking UOM.
* 🔨 **result-ts**: 
  * we ignore QtyOrdered, but convert the available qty into the sales order line's UOM and then compare with Qtyentered.
  * why: the check is done on qtyEntered-change (amonth other columns) and the user can't even see QtyOrdered. I wanted to avaoid making assumptions about the value of QtyOrdered

**Comment by metas-ts** [comment]
# Dev-Test WIP

![image](https://user-images.githubusercontent.com/1264789/55529257-c0264380-56a0-11e9-8fd5-b8f734af5d0a.png)
------------------------------

Config window. Note that meanwhile i changed the layout to follow our canconical conventions
![image](https://user-images.githubusercontent.com/1264789/55529515-11830280-56a2-11e9-8ea9-b7607c30a210.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in medios.metasfresh

(Tested with 2 sales orders, each 1 orderline, for the same product)

1. 2 new fields in orderline: 
* Nicht kurzfr. Verfügbar: red dot when no short term availability for a product: **OK**
* kurzfr. Verfügbar: shows qty available at short term for this sales orderline: **OK**

2. red dot is displayed when qty for short term availability is not enough for the resp. orderline: **OK**

3. qty in kurzfr. Verfügbar is updated correctly, with **other** sales order(lines) considered:
* attributes: are correctly considered, only available qty with matching attributes (storage relevant!) are considered: **OK**
* material receipt: after qty in stock is increased bc of receipt, the qty in kurzfr. Verfügbar is increased correctly: **OK**
* Reverse: after reverse of material receipt, the qty in kurzfr. Verfügbar is increased correctly: **OK**
* production: after qty is received and PP_Order is processed, the qty in kurzfr. Verfügbar is increased correctly: **OK**
* did not test with qty decreased when product issued & detroyed in PP_Order, bc we know the qty in stock is not updated correctly after that, see #1032 
* shipment: after qty in stock is decreased bc of receipt, the qty in kurzfr. Verfügbar is decreased correctly: **OK**

4. DatePromised of other sales order(lines) correctly considered:
* orderlines are not considered if DatePromised is +72 days in the future: **OK**
* orderlines are not considered if they were not touched for +8hrs: **OK**

5. Error notifiaction:
* notification with link to the System Error Report pops up when the asynchronous operation runs into timeout (see dev test): **OK**
* checked with metas-ts: the "normal" will not have access to that report window, but the URL will be provided and can be sent to an Admin or metasfresh: **OK**


problems:
* UOM considered correctly: tested with different UOMs (Stk as product UOM, and set Kg as UOM in orderline per db): the qty in kurzfr. Verfügbar was updated correctly, but only after the qty in the orderline was changed; just updating the order (by changing DatePromised) the qty in kurzfr. Verfügbar was updated, but not correctly; discussed with metas-ts: this case is very unrealistic, different UOMs will be set from the beginning before the orderline is created, changing it afterwards is not possible since it
s read-only.
