### ISSUE TITLE
Switch Manufacturing and Distribution to Dispo Framework

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#523]
Switch Manufacturing to Dispo Framework
- BOM explosion directly after Sales Order complete (dispolines created) Lot4Lot
- Generic WebUI Window in Table view, all possibilities to Filter, Search, Select available
- Filter or select and create Manufacturing Orders from dispo window. here also possibility to decide if BOM Products shall be aggregated into 1 Manufacturing Order (e.g. POQ) or further Lot4Lot.
- DD Lines candidates directly after Sales Order complete (dispolines created)
- As soon as dependant manufaturing orders are created also generate and complete the DD Orders.
- Already existing automatisms must be available (e.g. direct create Lot4Lot manufacturing Orders ...)

Just rough ideas. More to come.

**Comment by metas-ts** [comment]
# Notes about the existing MRP system

* generally the existing MRP does 2 things in turn, until everything was computed
  * explosion, according to BOM
  * balancing: fullfill the demand from the neewly exploded BOM

* projected QtyOnHand: QtyOnHand which will probably be available on the given date
  * e.g. an order with a datepromised affects it

* LLC code in M_Product: column name is "LowLevel" lowest level where a given product is in any a BOM we have
  * an "absolute" raw material product has LLC = 0
  * a product that contains the raw-product, that product's LLC will be 1
  * in the balancing, MRP sorts all the products by LLC descending
  
  
# Notes about the production disposition framework

* for starts, basically, for a given order line, a user who knows how the real production is done (in reality) needs to 
  * see (zoom to, filter by etc) one production-order-candidate-record for each BOM, i.e. for each real-life production step
  * be able to drill deeper, to understand what is really happening *if* he/she wants to
  * to achieve this, we problably need a dedicated widget (maybe similar to the HU-editor one), i.e. we problably can't do it just with the standard AD stuff

## Candidate records
  
* The disposition framework's data will mostly consist of *candidate* records that are created by the system in an *incremental* fashion, accordingly to the system's master data (BOMs, Distribution networks etc)
and that can be inspected and changed by users.
* In a nutshell, candidates have different types. They consitute trees and the siblings on each tree level all have the same type
* A candidate record can have the following properties (fields/columns)
	* timestamp: the (future) time to which the given record relates
	* M_Locator
	* Product
	* quantity (also uom, maybe piip, tu-qty etc)
	* type: can be 
	  * `stock`: 
		 * Used to manage the projected quantity at 'timestamp'.
		 * The projected qty of a 'stock' record is increased by it's child 'supply' candidates and decreased by it's parent 'demand' candidates
		 * A `stock` candidate can have a negative qty if the MRP system does not know how to balance the respective demand. That information (negative qty/"unbalanced demand") can be displayed in the MRP product info window used by the purchase department, so they know what to order for which date.
		 * When a `stock` record for given product, locator and timestamp is changed, this change is propagated to other `stock` records that have the same product and locator but later timestamps.
	  * `demand`: a demand record can directly relate to a shiment schedule, or to the "source" part of a distribution order, or to the "issue" part of a production order.
	  it *decreases* the quantity of its child's `stock` record
	  * `supply` (also see supplyType): a supply record can directly relate to a receipt schedule or to the "destination" part of a distribution order or to the "receive" part of a production order
	  it *increases* the quantity of its parent `stock` record
	* link to a parent-record.
	  * records constitute trees
	  * all records within the same level have the same type. the types per level alternate like this: demand - stock - supply - demand - stock - supply ...
	* supplyType: only relevant if type=supply; can be 
	  * "purchase"
	  * "distribution"
	  * "production"
	* a link to the related record. 
	  * for `demand` candidates this might be
	    * M_ShipmentSchedule (!)
	    * M_Replenish (in future)
	    * M_RequisitionLine (in future)
		* DD_OrderLine (for the distribution's source)
		* PP_Order_BOMLine (for the stuff to issue)
	  * for `supply` candidates, this might be
	    * M_ReceiptSchedule
		* DD_OrderLine (for the distribution's destination)
		* PP_Order_BOMLine or PP_Order (for the stuff to receive)

## Workflow

Notes:
* The system will proceed incrementally. Each one of the following "=>" items is an independent step, that was triggered by some event and potentially triggers further steps.
* Those changes or events don't just propagate down as in the example, but also "horizontally" between `stock`candidate records, as sketched further up. E.g. if the quantity is changed in one candidate, 
this might invaldiate a bunch of other candidates. I think, that technically we can do this with something similar to the `de.metas.storage.IStorageSegment`
* I neglected the "time" dimension in the example, but i think it can be fit in. Easily nothe that different candidates withing the same tree can easily have different timestamps, due to planned production and distribution durations.


OK, now let's sketch some sample workflows

### Workflow 1

* the user created and completed C_OrderLine with
 * 23kg Salad
 * Datepromised 2017-03-22

=> the system creates a shipment schedule (ofc we already have this)

=>the system creates a candidate "1_de" with
* link to the shipment schedule
* type=`demand`
* quantity = 23kg 
* product = Salad
* locator from where the shipmentschedule shall be shipped (locator or warehouse, we'll see)
* timestamp=the shipmentschedule's DatePromised

=>the system creates a candidate "2_st" which is a child of candidate "1" with 
* type=`stock`
* quantity = -23kg 
* product = Salad
* locator and timestamp from its parent

At this point in the (hypothetical) workflow the system does not know what else to do, because there is not distribution-network, BOM etc configured.
Therefore the negative projected quantity remains unbalanced. However, the information is shown (in the MRP product info window). 
Now someone creates a purchase order with 

a datepromised that is before the sales order's datepromised.
 * 100kg Salad
 * Datepromised 2017-03-21 (i.e. one day before the sale order)
 * locator which in this example is the same locator that the sales order has

=> the system creates a receipt schedule accordingly (ofc we already have this)
 
=> The system then creates a candidate "3_su_rs" with
* link to the receipt schedule
* type=`supply`
* quantity = 100kg 
* product = Salad
* locator where the goods will be received, which in this example is the same locator that the sales order has
* timestamp=the shipmentschedule's DatePromised

=> the system then creates a candidate "4_st" which is the *parent* of "3_su", with
* link to the receipt schedule
* type=`supply`
* quantity = 100kg 
* product = Salad

=> the system then updates all candidates with type `stock` that have the same locator and product and have a later timestamp (namely "2_st") and adds +100 to their quantity.
* that way, the quantity of "2_st" is now changed from -23 to +77 and the demand was balanced

### Workflow 2

a sales order, shipment schedule, as well as candidates "1_de" and "2_st" are creates as in workflow 1

=>the system then creates up to two more candidates, all with
* type=supply
* parent='stock'-candidate "2_st"
* and the candidates are with
  * supply type="production-order"
    * but this one is only created if there is a related BOM which says how to produce that product (also as co-product)
  * supply type="distribution-order"
    * but this one is only created if there is some distribution-network-cofig
    * the locator of this new candidate is the respective locator of the *source*

=> further for a production-order "supply"-candidate, the system then creates further "demand"-child-candidates one for each BOM component. 

=> also further, for a distribution-order "supply"-candidate, the system 
* allocates available on-hand-quantity, similar to the way it does in shipment schedule (i.e. first-come-first served, qty_override etc etc)
* creates additional "demand"-child-candidates for the quantities that are not on stock

=> for each new "demand"-candidate, the system then creates another `stock` candidate and then (if it can) further `supply` candidates etc, etc

**Comment by metas-ts** [comment]
didn'T intent to close the issue :blush:

**Comment by metas-ts** [comment]
WTF...i really need to be carefull with the word "fixes"

**Comment by metas-ts** [comment]
closing this issue now. @metas-mk feel free to repoen if you want
