### ISSUE TITLE
Calculated DailyLotNo in Material Receipt Candidates

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#653]
Calculated DailyLotNo in Material Receipt Candidates
- base information from additional date field in Purchase Order
- when completeing the order the calculation shall be triggered (same as in HU Editor for that field) and set into attributes for material receipt candidates
- shall be used initially in material receipt, but can be adjusted by user

**Comment by metas-rc** [comment]
The LotNumber is not calculated anywhere yet. 
We will have to create the logic in this task.  
The lot Date is saved in the HUAttributes. 
I will have to make some configs for the lot date to be relevant in the receipt schedule and also create some callouts on attributes so that, if the user changes the lot date in wareneingang pos, the lot number to be also change accordingly.

**Comment by metas-ts** [comment]
Hi, 
some tests are failing: https://jenkins.metasfresh.com/job/metasfresh/job/FRESH-934/4/testReport/. Please check out and fix

**Comment by metas-ts** [comment]
@metas-rc 
I integrated the change, but didn't yet delete the branch.
Please add the documentation fabout which i talked in the PR when you have time

**Comment by metas-dh** [comment]
Results of IT 2 

* App.Server: sp80clouditdb
* Buildno: #s 1.275, 1.303
* DB: declouddb001 : 5432 / sp80_cloud_it_db

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-934.md: OK
