### ISSUE TITLE
Process Parm Keyboard navigation lost after last release

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#782]
Process Parm Keyboard navigation lost after last release. Example: Check Process "create Invoice" in Invoice Candidates. Before focus was on first flag on opening and could be changed via <space>. Then TAB would lead to <start> button when one could start the process with <enter>.
Thats all not possible anymore.

**Comment by metas-dh** [comment]
Results of IT 1

* when opening the window for process parameters, the cursor was never focused on the first flag or first parameter, always on the last one (e.g. in invoicing, on Abw. Referenz): NOK
* starting the process with Enter wasn't possible, although it worked with space: NOK
* i also had exceptions in console everytime i opened one of the processing windows: NOK

**Comment by metas-ts** [comment]
changed milestone to next week after consulting @metas-mk

**Comment by metas-dh** [comment]
Results of IT 2

checked again on windows:
* when opening the window for process parameters, the cursor was always focused on the first flag or first parameter, checking / unchecking the checkbox worked with space (e.g. in invoicing): OK
* starting the process with CTRL & Enter worked fine: OK
* no exceptions: OK

=> checked with mk, ts: not working on x2go might be Linux problem, since it's working fine on Windows, it's ok and we can put the task in done.
