### ISSUE TITLE
Vendor empty returns missing in invoice cand when negativ qty

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#785]
Vendor empty returns missing in invoice cand when negativ qty

**Comment by metas-rc** [comment]
Steps to reproduce:
* Go to Wareneingang POS, create a leergut for 2 boxes
* => at this point there are 2 invoice candidates for this inout.
* Go to the created inout, reactivate it
* Copy a line, change its product and set its qty to a negative number
* Complete the inout
* => NOK: Still only 2 invoice candidates instead of 3.

**Comment by metas-dh** [comment]
Integrated, built and deployed for integration test

**Comment by metas-dh** [comment]
Results of IT 1 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23785.md: OK
