### ISSUE TITLE
Fact Account WebUI Window Readonly

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#796]
Fact Account WebUI Window Readonly
- Define a generic window for Fact Account searching and browsing.
- This window shall also be opened with filter when selecting the referenced documents to accounting (previous button "posted")

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* generic window for Fact Account searching and browsing, readonly: OK
@metas-mk:
* This window shall also be opened with filter when selecting the referenced documents to accounting (previous button "posted"): did not find that, where can i test that? or is it not implemented yet?

**Comment by teosarca** [comment]
> This window shall also be opened with filter when selecting the referenced documents to accounting (previous button "posted"): did not find that, where can i test that? or is it not implemented yet?

implemented it now :)

**Comment by metas-lc** [comment]
IT2
* about referenced docus:
1. in webui: made sales order -> shipment -> invoice
2. went in swing to post my invoice because right now we can't post it in webui
3. had to do a cache reset
4. webui: go to invoice created in step 1, see referenced documents: "Accounting Fact Details" OK
5. select "Accounting Fact Details" => Buchführungs-Details window opens, only with the fact_accts for your invoice OK

**Comment by metas-lc** [comment]
the task for documents not being posted: https://github.com/metasfresh/metasfresh/issues/1215
and the one for caching: https://github.com/metasfresh/metasfresh-webui-api/issues/19
