### ISSUE TITLE
New role added .. login not possible after that

### ISSUE THREAD

**Issue by nebergd** [metasfresh/metasfresh#912]
I define a new role... 
![image](https://cloud.githubusercontent.com/assets/24392763/22542817/0c32c7ea-e92e-11e6-98be-c2222903caa8.png)

After that it is no longer possible to login ... Error
![image](https://cloud.githubusercontent.com/assets/24392763/22542855/2d05dfde-e92e-11e6-9f47-f1fa73f28897.png)
Dieter

**Comment by teosarca** [comment]
Pls check the Organisation-Zugriff (Assigned orgs). Make sure you have at least one entry there.
Assigning organization "*" would totally OK.

**Comment by metasnw** [comment]
problem is that as soon as there is one role which does not have assigned orgs as teo described it no login is possible any more.
there are two things that make this a real headache:
1. isaccessallorgs is ignored and does not seem to work anymore
2. isactive = N roles are also considered

I suggest:
1. instead of blocking anyone of login in we just do not show the roles which are incomplete and show an info message as we did somewhere in the past (role incomplete)
2. we fix checkbox isaccessallorgs 
3. we make sure inactive roles are really ignored no matter if there are subroles or not

**Comment by metasnw** [comment]
@nebergd this is how it looks like when you configure the org access of the role:

![image](https://cloud.githubusercontent.com/assets/16079655/22854278/19e1e724-f06b-11e6-900d-42af64d25593.png)

**Comment by teosarca** [comment]
anyways, i think we shall generate that record automatically when a new role is created, for convenience.

**Comment by metasnw** [comment]
and we shouldnt block access to the system just because one role fails

**Comment by nebergd** [comment]
Hi the problem is back again
I check it like described.
![image](https://cloud.githubusercontent.com/assets/24392763/23061513/7e3d1cc0-f502-11e6-9616-22164ceecf82.png)

Dieter

**Comment by metasnw** [comment]
IT is fine. Problem is solved.
