### ISSUE TITLE
have a way to control which contact is used on addresses in order 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#928]
case No 1 - Partner with one contact which I do not want to show
1. have partner with one contact e.g. "zentrale" which I do not want as part of order address
2. isdefault = N, purchase and sales = N
3. NOK: contact "zentrale" is used automatically in order addresses (order, delivery, invoice)

case No 2 - Partner with two contacts where I want to show one of
1. have partner with two contact e.g. "zentrale" and "Mr. T". I want to show "Mr. T"
2. "Mr. T" isdefault = Y
2. OK: contact "Mr. T" is used automatically in order addresses (order, delivery, invoice)

**Comment by metas-rc** [comment]
I introduced 2 new flags in AD_User: IsSalesContact_Default and IsPurchaseContact_Default.
Only one user can be sales default or purchase default.
Only a purchase user can be purchase default and only a sales user can be sales default.
When an order is created, its AD_User and Bill_User are set only if there is a default set for the given SOTrx. Otherwise, the values will not be set.
For sales orders, oyu can check this in the database, because the AD_User and Bill User are not displayed.
They are displayed in Purchase Order.
Even if a default was already set in a purchase order, you can still go to the dropdown and select any other user you like.

**Comment by metas-lc** [comment]
created follow-up https://github.com/metasfresh/metasfresh/issues/989

**Comment by metas-lc** [comment]
IT. OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23928.md
