### ISSUE TITLE
weighing and receiving LUs changes the amount of TUs and their structure

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#943]
aggregated TU change the qty of TUs if we weigh the LU, but only after we receive them.

Example: made an order with 5 TUx5 
in receipt POS, i put them on 1 LU => on LU was writing 5TUs 25x25
set gross weight to 150 => net = 125. So now on LU was writing 5TUs 25x125
i received =>checked my LU in HU POS => 25 TU 125x125
so the Tu changed from 5 to 25 NOK

**Comment by metas-ts** [comment]
Hi @metas-lc , i have trouble understanding the issue (not doubt that there is one). can you please explain it deeper?

> Example: made an order with 5 TUx5

ok, got it

> in receipt POS, i put them on 1 LU => on LU was writing 5TUs 25x25

so the "25x25" is already wrong, correct? or where is the "25" coming from?

> set gross weight to 150 => net = 125. So now on LU was writing 5TUs 25x125

the net=125 is not OK, right? because the LU alone is 25, but there is also the TUs' weights..

I think it makes sense for me to first help me understand these first parts. 
I'll also look at it myself, maybe i can figure it out, but if you have time, please ping me :-)

**Comment by metas-lc** [comment]
You are right. It wasn't ok from the start, because the weights of the TUs were not considered. The tare weight was wrong, therefore gross weight wasn't calculated well.

25 x kg and 25 kg that it was writing on the LU i think it's fine. It's what we have in storage and in the attribute for net weight. 

What is not ok is that after receipt, the aggregated 5TUs transformed into 25 TUs. Somehow the net weight got into storage weight and became 125, which means 25 TUs x 5

**Comment by metas-dh** [comment]
Results of IT1:

* no more added TU because of overall weight (> than ordered): OK
* qty TU after receipt not correct in M_ReceiptSchedule and in receiptline in Wareneingang POS: all aggregated TUs are counted = 1, no matter how many are aggregated: NOK

**Comment by metas-dh** [comment]
Results of IT 2 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23943.md: OK
