### ISSUE TITLE
Empties Returns for Vendors and Customers in Material Receipt Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#957]
### Is this a bug or feature request?
Feature Request.
Already described in https://github.com/metasfresh/metasfresh-webui/issues/121.
### What is the expected or desired behavior?
Create the 2 Windows and menu entries for Customer & Vendor Return in WebUI.

**Comment by teosarca** [comment]
note to IT: to be tested on w101

**Comment by metas-lc** [comment]
IT:
- both windows are in menu OK
- the following i am not sure it's task related:
- if you create empties return the bpartner does not have address NOK 
- in purchase order, if you go to related documents you have material receipt and shipment, which want to open material receipt/shipment instead of Returns NOK
