### ISSUE TITLE
Allow subscription without shipment

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#992]
Today I do not have a way to define a flatrate condition that only generates invoice candidates but no shipment schedules.
For cases like memberships (´#987) there is no delivery and just the invoice candidate is needed.

Wish:
Have a contract type like "abonnement_leistung" and rename the existing into "abonnement_lieferung"

![image](https://cloud.githubusercontent.com/assets/16079655/23093315/faa16d42-f5df-11e6-90f8-da395211116f.png)

**Comment by metas-ts** [comment]
hi @metasnw,
is thi task still up-to-date? 
Asking because I *think* I remember you having mentioned that you somehow might have solved (or just circumvented?) the problem. 
Aparent from, that, we might want to consider also to not introduce a new contract type, but somehow use the product types like "service"...

**Comment by metasnw** [comment]
hi @metas-ts 
that topic is still how as the workaround is to set invoice rule to immediately thus creating unnecessary shipment schedule lines.
I agree to your idea to have a product type service which implies a product which is not be shipped physically. 

Any idea for an estimation to provide this feature?

**Comment by metas-ts** [comment]
* Development would be somewhere less or equal to 3hrs.
* Plus IT (1hr?)

We already have this thing for invoice candidtes: if `M_Product.ProductType` is not "Item", then set the invocie rule to "Immediate". So all we need is to exclude "not-Item" products when creating shipment schedules for order lines. I'm going to do this now..it's almost quicker done than explained

**Comment by teosarca** [comment]
>  So all we need is to exclude "not-Item" products when creating shipment schedules for order lines.

(not sure if we would still need it, but adding it here for reference)
If we exclude the non-Item products from shipment, because we will not be able to "ship" services, in case that's needed.
So, somehow we assume the service was delivered on invoice.

**Comment by metas-mk** [comment]
Hm, not sure about this. The workaround is ok from what I understood, but we shall set up the use cases. Generally spoken, for me, a membership can also be "delivered"/ "started" together with the shipment of the membership badge. Same for services. I can contract services, they should be in shipment shedule for the moment where I decide to do the service. Instead of an inout "shipment", i can create an inout "service hours note".

**Comment by metasnw** [comment]
I agree that we need to look at the cases.
Becauses there are cases with subscriptions where there is really no service or product delivered for this case it would be efficient to not create shipment schedules.
But there are other cases where you want to determine the time and amount of delivery (hours, newspaper, traffic volumes).
So I am also not sure if it is a good idea to use the existing product type service.

We could link it to the flatrate condition or introduce a new product type "virtual" / "no delivery" whatever...
